force-app/main/default/objects/Customer_Cashbook__c/Customer_Cashbook__c.object-meta.xml
<CustomObject>
    <label>Customer Cashbook</label>
    <nameField>
        <displayFormat>CB-{0000}</displayFormat>
        <label>Cashbook Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Cashbooks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Cashbook__c/fields/Closing_Balance__c.field-meta.xml
<CustomField>
    <fullName>Closing_Balance__c</fullName>
    <label>Closing Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Customer_Cashbook__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Cashbooks</relationshipLabel>
    <relationshipName>Customer_Cashbooks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>REC-{0000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <label>Bank Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SBI</fullName>
            </value>
            <value>
                <fullName>HDFC</fullName>
            </value>
            <value>
                <fullName>ICICI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Cheque_Trasaction_Number__c.field-meta.xml
<CustomField>
    <fullName>Cheque_Trasaction_Number__c</fullName>
    <label>Cheque/Trasaction Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Approval_Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Mode_of_payment__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_payment__c</fullName>
    <label>Mode of payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>UPI</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Bank Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Sales_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Invoice</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (2 AND 3)</booleanFilter>
        <filterItems>
            <field>Sales_Invoice__c.Pending_Amount__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <filterItems>
            <field>Sales_Invoice__c.Customer__c</field>
            <operation>equals</operation>
            <valueField>$Source.Customer__c</valueField>
        </filterItems>
        <filterItems>
            <field>Sales_Invoice__c.Pending_Amount_SAP__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Sales_Invoice__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Return__c/Return__c.object-meta.xml
<CustomObject>
    <label>Return</label>
    <nameField>
        <label>Return Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Returns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Return__c/fields/Grand_Total__c.field-meta.xml
<CustomField>
    <fullName>Grand_Total__c</fullName>
    <label>Grand Total</label>
    <summarizedField>Return_Item__c.Total__c</summarizedField>
    <summaryForeignKey>Return_Item__c.Return__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Return__c/fields/Grand_Total_Discounted__c.field-meta.xml
<CustomField>
    <fullName>Grand_Total_Discounted__c</fullName>
    <formula>IF( New_Flow__c == true,
			Grand_Total__c,
			IF(TEXT(Sales_Invoice__r.Payment_Type__c )==&apos;Credit&apos;,
						Grand_Total__c ,
						IF(Grand_Total_after_discount__c != 0.0 ,
									Grand_Total_after_discount__c - (Grand_Total_after_discount__c * Customer__r.Cash_Discount__c),
									Grand_Total__c - (Grand_Total__c * Customer__r.Cash_Discount__c)
								)
					)
		)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Grand Total (Discounted)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Return__c/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <formula>Sales_Invoice__r.Doc_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Return__c/fields/Return_Date__c.field-meta.xml
<CustomField>
    <fullName>Return_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Return Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Return__c/fields/Sales_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Invoice</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Sales_Invoice__c.Sales_Invoice_Status__c</field>
            <operation>notEqual</operation>
            <value>Cancelled</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Sales_Invoice__c</referenceTo>
    <relationshipLabel>Returns</relationshipLabel>
    <relationshipName>Returns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice__c/Sales_Invoice__c.object-meta.xml
<CustomObject>
    <label>Sales Invoice</label>
    <nameField>
        <label>Sales Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Invoice__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Invoices</relationshipLabel>
    <relationshipName>Sales_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice__c/fields/Grand_Total__c.field-meta.xml
<CustomField>
    <fullName>Grand_Total__c</fullName>
    <label>Grand Total</label>
    <summarizedField>Sales_Invoice_Item__c.Total__c</summarizedField>
    <summaryForeignKey>Sales_Invoice_Item__c.Sales_Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice__c/fields/Grand_Total_Discounted__c.field-meta.xml
<CustomField>
    <fullName>Grand_Total_Discounted__c</fullName>
    <formula>IF( New_Flow__c == true,
			Grand_Total__c,
			IF(TEXT(Payment_Type__c)==&apos;Credit&apos;,
						Grand_Total__c ,  
						IF(Grand_Total_after_discount__c != 0.0 , 
									Grand_Total_after_discount__c - (Grand_Total_after_discount__c *  Customer__r.Cash_Discount__c), 
									Grand_Total__c - (Grand_Total__c *  Customer__r.Cash_Discount__c) 
								)
					)
			)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Grand Total (Discounted)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/DevSnacksPdfController.cls
public class DevSnacksPdfController {
    
    public Decimal totalDebit {get; set;}
    public String customer {get;set;}
    public Date fDate {get;set;}
    public Date tDate {get;set;}
    public Decimal totalCredit {get; set;}
    public Decimal totalDebitwithOB {get;set;}
    public Decimal OpeningBalance{get;set;}
    public Decimal ClosingBalance{get;set;}
    public list<wrapper> wraplist{get;set;}
    
    
    public DevSnacksPdfController(){
        
        Id recordId = ApexPages.currentPage().getParameters().get('id');
        String fromDate = ApexPages.currentPage().getParameters().get('from'); 
        String toDate = ApexPages.currentPage().getParameters().get('to'); 
        Date fromdate1 = date.valueof(fromDate);
        Date todate1 = date.valueof(toDate);
        
        fDate = fromdate1;
        tDate = todate1;
        
        Date fromdate2 = date.valueof(fromDate).addDays(-1);
        Date todate2 = date.valueof(toDate).addDays(-1);
        
        system.debug('fromDate:' + fromdate1);
        system.debug('toDate:' + todate1);
        
        wraplist = new list<wrapper>();
        
        OpeningBalance = 0;
        ClosingBalance=0;
            
        totalDebit = OpeningBalance; 
        totalCredit = 0;
        List<Account> accList = [select id, Name from Account where id=:recordId Limit 1];  
        if(accList.size()>0){
            customer = accList[0].Name;
        }
        
        
        
        List<Customer_Cashbook__c> cbList = [select Id,Name,Date__c,Customer__c,Opening_Balance__c,Closing_Balance__c,CreatedDate from Customer_Cashbook__c where Customer__c = :recordId and (Date__c=:fromDate1  or Date__c=:toDate1) ];
            if(cbList.size() > 0){
                for(Customer_Cashbook__c cb: cbList){
                   if(cb.Date__c == fromDate1){
                        OpeningBalance = cb.Opening_Balance__c;
                    }
                    if(cb.Date__c == toDate1){
                        ClosingBalance = cb.Closing_Balance__c;
                    }
                }
            }
        
        totalDebit = OpeningBalance; 
        
         List<Sales_Invoice__c> salesInvoices = [SELECT id,Name,Invoice_Date__c,Customer__c,Grand_Total_Discounted__c,CreatedDate FROM Sales_Invoice__c where Customer__c=:recordId and (DAY_ONLY(createdDate)>=:fromDate1  and DAY_ONLY(createdDate)<=:toDate1) ];
        
        if(salesInvoices.size() > 0){
                for(Sales_Invoice__c ct: salesInvoices){
                    if(ct.Grand_Total_Discounted__c !=null){
                        wrapper w = new wrapper();
                        w.transDate = Date.valueOf(ct.Invoice_Date__c);
                        w.Debit = ct.Grand_Total_Discounted__c;
                        w.objest = true;
                        w.Remarks = 'Sales GST';
                        w.VocherNum = ct.Name;
                        w.VocherType = 'TVM2 Sales';
                        w.CreatedDate = ct.CreatedDate;
                       // w.Status = ct.From__c == 'Branch' && (ct.To__c == 'Route' || ct.To__c == 'Head Office' ) ? 'Debited' :(ct.From__c == 'Route' || ct.From__c == 'Head Office' ) && ct.To__c == 'Branch' ? 'Credited' : '';
                        wraplist.add(w);
                        totalDebit = totalDebit + w.Debit;

                    }
                    
                }
            }

        List<Receipt__c> receipts = [SELECT id,Amount__c,Bank_Name__c,Receipt_Date__c,Cheque_Trasaction_Number__c,Mode_of_payment__c, Customer__c, Name,CreatedDate FROM Receipt__c where Customer__c=:recordId and (DAY_ONLY(createdDate)>=:fromDate1  and DAY_ONLY(createdDate)<=:toDate1) ];
        if(receipts.size() > 0){
            for(Receipt__c ct: receipts){
                if(ct.Amount__c !=null){
                    wrapper w = new wrapper();
                    w.transDate = Date.valueOf(ct.Receipt_Date__c);
                    w.Credit = ct.Amount__c;
                    w.objest = false;
                    //w.Remarks = ct.Mode_of_payment__c +'-'+ct.Bank_Name__c+'-'+ ct.Cheque_Trasaction_Number__c;
                    w.Remarks = ((ct.Mode_of_payment__c != null && String.isNotBlank(String.valueOf(ct.Mode_of_payment__c))) ? ct.Mode_of_payment__c  : '') +
                        ((ct.Bank_Name__c != null && String.isNotBlank(String.valueOf(ct.Bank_Name__c))) ?  '-' + ct.Bank_Name__c  : '') +
                        ((ct.Cheque_Trasaction_Number__c != null && String.isNotBlank(String.valueOf(ct.Cheque_Trasaction_Number__c))) ?  '-' + String.valueOf(ct.Cheque_Trasaction_Number__c) : '');
                    w.VocherNum = ct.Name;
                    w.VocherType = 'TVM2 Receipt';
                    w.CreatedDate = ct.CreatedDate;
                    // w.Status = ct.From__c == 'Branch' && (ct.To__c == 'Route' || ct.To__c == 'Head Office' ) ? 'Debited' :(ct.From__c == 'Route' || ct.From__c == 'Head Office' ) && ct.To__c == 'Branch' ? 'Credited' : '';
                    wraplist.add(w);
                    
                    totalCredit = totalCredit + w.Credit;
                    
                }
                
            }
        }
        
        List<Return__c> retList = [SELECT id,Name,Return_Date__c,Customer__c,Grand_Total__c,CreatedDate FROM Return__c where Customer__c=:recordId and (DAY_ONLY(createdDate)>=:fromDate1  and DAY_ONLY(createdDate)<=:toDate1)];
        if(retList.size() > 0){
            for(Return__c ct: retList){
                if(ct.Grand_Total__c !=null){
                    wrapper w = new wrapper();
                    w.transDate = Date.valueOf(ct.Return_Date__c);
                    w.Credit = ct.Grand_Total__c;
                    w.objest = false;  
                    w.Remarks = 'Sales Returns';
                    w.VocherNum = ct.Name;
                    w.VocherType = 'Credit Note';
                    w.CreatedDate = ct.CreatedDate;
                    // w.Status = ct.From__c == 'Branch' && (ct.To__c == 'Route' || ct.To__c == 'Head Office' ) ? 'Debited' :(ct.From__c == 'Route' || ct.From__c == 'Head Office' ) && ct.To__c == 'Branch' ? 'Credited' : '';
                    wraplist.add(w);
                    
                    totalCredit = totalCredit + w.Credit;
                    
                }
                
            }
        }

        ClosingBalance = totalDebit - totalCredit;
        wraplist.sort();
    }
    public class wrapper implements Comparable{
        
        public String Branch{get;set;}
        public String Route{get;set;}
        public String Customer{get;set;}
        public String VocherNum{get;set;}
        public String VocherType{get;set;}
        public String From1{get;set;}
        public boolean objest{get;set;}
        public String To1{get;set;}
        public Decimal Amount{get;set;}
        public Decimal Debit{get;set;}
        public Decimal Credit{get;set;}
        public String Remarks{get;set;}
        public DateTime CreatedDate{set;get;}
        public String Status{get;set;}
        public Date transDate{get;set;}
        
        public  Integer compareTo(Object anotherObject){
            wrapper wso2=(wrapper) anotherObject;
            if(CreatedDate>wso2.CreatedDate){
                return 1;
            }else if(CreatedDate<wso2.CreatedDate){
                return -1;
            }
            return 0;
        }
    }

}