force-app/main/default/objects/Customer_Cashbook__c/Customer_Cashbook__c.object-meta.xml
<CustomObject>
    <label>Customer Cashbook</label>
    <nameField>
        <displayFormat>CB-{0000}</displayFormat>
        <label>Cashbook Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Cashbooks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Cashbook__c/fields/Closing_Balance__c.field-meta.xml
<CustomField>
    <fullName>Closing_Balance__c</fullName>
    <label>Closing Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Customer_Cashbook__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Cashbooks</relationshipLabel>
    <relationshipName>Customer_Cashbooks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/UpdateCustOpeningBalance.cls
global class UpdateCustOpeningBalance implements Database.Batchable<sObject>,Database.Stateful,Schedulable{

     public Database.QueryLocator start(Database.BatchableContext BC){
        String query='Select Id,Name from Account where Account_Status__c = \'Approved\'';
      return Database.getQueryLocator(query);
   }

    public void execute(Database.BatchableContext BC, List<Account> scope){
        Set<Id> accIds = new Set<Id>();
        
        for(Account acc : scope){
            accIds.add(acc.Id);
        }
        Map<Id,Customer_Cashbook__c> cbMap = new Map<Id,Customer_Cashbook__c>();
         List<Customer_Cashbook__c> cbList = [select Id,Name,Customer__c,Opening_Balance__c,Closing_Balance__c,CreatedDate from Customer_Cashbook__c where CreatedDate = yesterday and Customer__c IN:accIds];
        List<Customer_Cashbook__c> cbListToUpdate = new List<Customer_Cashbook__c>();
        if(cbList.size() != 0){
            for(Customer_Cashbook__c cb: cbList){
                cbMap.put(cb.Customer__c,cb);
            }
        }
        else{
             for(Account acc: scope){
                Customer_Cashbook__c cb1 = new Customer_Cashbook__c();
                cb1.Customer__c = acc.Id;
                cb1.Opening_Balance__c = 0;
                 cbListToUpdate.add(cb1);
            }
        }      
        
        
        if(cbMap.size() != 0){
            for(Account acc: scope){
                if(cbMap.containsKey(acc.Id)){
                    Customer_Cashbook__c cb1 = new Customer_Cashbook__c();
                    cb1.Customer__c = acc.Id;
                    cb1.Opening_Balance__c = cbMap.get(acc.Id).Closing_Balance__c;
                    cbListToUpdate.add(cb1);
                }
                else{
                    Customer_Cashbook__c cb1 = new Customer_Cashbook__c();
                    cb1.Customer__c = acc.Id;
                    cb1.Opening_Balance__c = 0;
                    cbListToUpdate.add(cb1);
                }
              
            }
             
             
         }
     system.debug('cbListToUpdate:' + cbListToUpdate);
       insert cbListToUpdate;
    }
    
    public void finish(Database.BatchableContext BC){
   }
    
     global void execute(SchedulableContext SC){
        database.executeBatch(new UpdateCustOpeningBalance(),100);
      
    } 

}