force-app/main/default/objects/Item_Replacement__c/Item_Replacement__c.object-meta.xml
<CustomObject>
    <label>Item Replacement</label>
    <nameField>
        <displayFormat>IR-{0000}</displayFormat>
        <label>Item Replacement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Item Replacements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item_Replacement__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Item Replacements</relationshipLabel>
    <relationshipName>Item_Replacements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Replaced_Item__c/Replaced_Item__c.object-meta.xml
<CustomObject>
    <label>Replaced Item</label>
    <nameField>
        <label>Replaced Item Name (Damged Item)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Replaced Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Replaced_Item__c/fields/Item_Replacement__c.field-meta.xml
<CustomField>
    <fullName>Item_Replacement__c</fullName>
    <label>Item Replacement</label>
    <referenceTo>Item_Replacement__c</referenceTo>
    <relationshipLabel>Replaced Items</relationshipLabel>
    <relationshipName>Replaced_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Replaced_Item__c/fields/New_Stock__c.field-meta.xml
<CustomField>
    <fullName>New_Stock__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Replaced Stock</label>
    <referenceTo>Stock__c</referenceTo>
    <relationshipLabel>Replaced Items (New Stock)</relationshipLabel>
    <relationshipName>Replaced_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Replaced_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Replaced Items</relationshipLabel>
    <relationshipName>Replaced_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Replaced_Item__c/fields/R_Type__c.field-meta.xml
<CustomField>
    <fullName>R_Type__c</fullName>
    <formula>text(Item_Replacement__r.Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>R_Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Replaced_Item__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <formula>Item_Replacement__r.Route__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Route</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Replaced_Item__c/fields/RouteLKP__c.field-meta.xml
<CustomField>
    <fullName>RouteLKP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Replaced Items</relationshipLabel>
    <relationshipName>Replaced_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>Stock-{00000}</displayFormat>
        <label>Stock Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/fields/Available_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Available_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Available Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Damaged_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Damaged_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Damaged Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Free_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Free_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Free Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_History__c/Stock_History__c.object-meta.xml
<CustomObject>
    <label>Stock History</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Stock History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock History</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_History__c/fields/Available_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Available_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Closing Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock_History__c/fields/Ext_ID__c.field-meta.xml
<CustomField>
    <fullName>Ext_ID__c</fullName>
    <label>Ext. ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock_History__c/fields/Free_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Free_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Free Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock_History__c/fields/Initial_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Initial_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Received Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock_History__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Stock History</relationshipLabel>
    <relationshipName>Stock_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_History__c/fields/Replaced_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Replaced_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Replaced Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock_History__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Stock History</relationshipLabel>
    <relationshipName>Stock_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_History__c/fields/Sold_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Sold_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sold Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock_History__c/fields/Unsealed_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Unsealed_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Unsealed Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ReplacedItemTriggerHandler.cls
public with sharing class ReplacedItemTriggerHandler {

    
    public static void updateStockHistory(list<Replaced_Item__c> replacedItems){
       list<Id> listReplaceId =new List<Id>();
        Map<String,Decimal> availMap = new Map<String,Decimal>();
        Map<String,Decimal> damagedMap = new Map<String,Decimal>();
        Set<String> extids = new Set<String>();
        for(Replaced_Item__c ir : replacedItems){
            // if(ir.R_Type__c == 'Replacement') {
            listReplaceId.add(ir.Item_Replacement__c);  
            //  }
            string ext = String.valueOf(ir.Product__c) + String.valueOf(ir.RouteLKP__c) + system.today();
            extids.add(ext);   
            damagedMap.put(ext,ir.Quantity__c);
        } 
        if(listReplaceId.size() > 0){
            List<AggregateResult> avaggList = [select New_Stock__r.Product__c prod,Item_Replacement__r.Route__c rt, SUM(Quantity__c) replQty from Replaced_Item__c where createddate=today AND Item_Replacement__c IN :listReplaceId group by New_Stock__r.Product__c,Item_Replacement__r.Route__c]; 
            
            for(AggregateResult agg:avaggList){
                string ext = String.valueOf(agg.get('prod')) + String.valueOf(agg.get('rt')) + system.today();
                extids.add(ext);
                availMap.put(ext,(Decimal)agg.get('replQty'));
            }  
        }
        system.debug(extids);
        List<Stock_History__c> hisList = [select Id,Name,Route__c,Product__c,Available_Quantity__c,Initial_Quantity__c,
                                          Damaged_Quantity__c,Free_Quantity__c,Sold_Quantity__c,
                                          Replaced_Quantity__c,Unsealed_Quantity__c,CreatedDate,Ext_ID__c from Stock_History__c where  Ext_ID__c IN:extIds];
        List<Stock_History__c> hisListToUpdate = new List<Stock_History__c>();
        if(hisList.size() > 0){
            for(Stock_History__c his : hisList){
                if(availMap.containsKey(his.Ext_ID__c) ){
                    his.Replaced_Quantity__c = availMap.get(his.Ext_ID__c);
                    
                }
                if(his.Damaged_Quantity__c != null && damagedMap.containsKey(his.Ext_ID__c)){
                    his.Damaged_Quantity__c = (damagedMap.get(his.Ext_ID__c) +  his.Damaged_Quantity__c ); 
                }else if(damagedMap.containsKey(his.Ext_ID__c)){
                    his.Damaged_Quantity__c = damagedMap.get(his.Ext_ID__c);
                }
                hisListToUpdate.add(his);
            }
        }
        try {
            upsert hisListToUpdate;
        }
        catch (System.Exception ae) { 
            ExceptionHandler.addLog(ae,String.valueOf(hisListToUpdate) );
        }    
        
    }
}