force-app/main/default/objects/Item_Replacement__c/Item_Replacement__c.object-meta.xml
<CustomObject>
    <label>Item Replacement</label>
    <nameField>
        <displayFormat>IR-{0000}</displayFormat>
        <label>Item Replacement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Item Replacements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item_Replacement__c/fields/Company_Id__c.field-meta.xml
<CustomField>
    <fullName>Company_Id__c</fullName>
    <formula>TEXT( Customer__r.CompanyId__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Item_Replacement__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Item Replacements</relationshipLabel>
    <relationshipName>Item_Replacements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Company_Id__c.field-meta.xml
<CustomField>
    <fullName>Company_Id__c</fullName>
    <label>Company_Id</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Company</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/CompanyId__c.field-meta.xml
<CustomField>
    <fullName>CompanyId__c</fullName>
    <label>Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Company</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Replaced_Item__c/Replaced_Item__c.object-meta.xml
<CustomObject>
    <label>Replaced Item</label>
    <nameField>
        <label>Replaced Item Name (Damged Item)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Replaced Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Replaced_Item__c/fields/Item_Replacement__c.field-meta.xml
<CustomField>
    <fullName>Item_Replacement__c</fullName>
    <label>Item Replacement</label>
    <referenceTo>Item_Replacement__c</referenceTo>
    <relationshipLabel>Replaced Items</relationshipLabel>
    <relationshipName>Replaced_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Replaced_Item__c/fields/New_Created_Stock__c.field-meta.xml
<CustomField>
    <fullName>New_Created_Stock__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Created Stock</label>
    <referenceTo>Stock__c</referenceTo>
    <relationshipLabel>Replaced Items (New Created Stock)</relationshipLabel>
    <relationshipName>Replaced_Items2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Replaced_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Replaced Items</relationshipLabel>
    <relationshipName>Replaced_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Replaced_Item__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <formula>Item_Replacement__r.Route__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Route</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Route__c/fields/CompanyId__c.field-meta.xml
<CustomField>
    <fullName>CompanyId__c</fullName>
    <label>Company Id</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Company</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Invoice__c/Sales_Invoice__c.object-meta.xml
<CustomObject>
    <label>Sales Invoice</label>
    <nameField>
        <label>Sales Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Invoice__c/fields/CompanyId__c.field-meta.xml
<CustomField>
    <fullName>CompanyId__c</fullName>
    <formula>TEXT( Customer__r.CompanyId__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Sales Invoices</relationshipLabel>
    <relationshipName>Sales_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice__c/fields/Sales_Invoice_Status__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice_Status__c</fullName>
    <defaultValue>&apos;Generated&apos;</defaultValue>
    <label>Sales Invoice Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Generated</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Invoice_Item__c/Sales_Invoice_Item__c.object-meta.xml
<CustomObject>
    <label>Sales Invoice Item</label>
    <nameField>
        <displayFormat>ITEM-{0000}</displayFormat>
        <label>Sales Invoice Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Invoice Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Invoice_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Sales Invoice Items</relationshipLabel>
    <relationshipName>Sales_Invoice_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice_Item__c/fields/Sales_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice__c</fullName>
    <label>Sales Invoice</label>
    <referenceTo>Sales_Invoice__c</referenceTo>
    <relationshipLabel>Invoice Items</relationshipLabel>
    <relationshipName>Invoice_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice_Item__c/fields/Stock__c.field-meta.xml
<CustomField>
    <fullName>Stock__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stock</label>
    <referenceTo>Stock__c</referenceTo>
    <relationshipLabel>Sales Invoice Items</relationshipLabel>
    <relationshipName>Sales_Invoice_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>Stock-{00000}</displayFormat>
        <label>Stock Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/fields/Available_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Available_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Available Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Damaged_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Damaged_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Damaged Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Free_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Free_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Free Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Intial_Stock__c.field-meta.xml
<CustomField>
    <fullName>Intial_Stock__c</fullName>
    <label>Intial Stock</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Stock_Type__c.field-meta.xml
<CustomField>
    <fullName>Stock_Type__c</fullName>
    <label>Stock Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Return</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
            </value>
            <value>
                <fullName>Manufacturing Defect</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stock_History__c/Stock_History__c.object-meta.xml
<CustomObject>
    <label>Stock History</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Stock History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock History</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_History__c/fields/Available_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Available_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Closing Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock_History__c/fields/Initial_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Initial_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Received Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock_History__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Stock History</relationshipLabel>
    <relationshipName>Stock_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_History__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Stock History</relationshipLabel>
    <relationshipName>Stock_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unsealed__c/Unsealed__c.object-meta.xml
<CustomObject>
    <label>Unsealed</label>
    <nameField>
        <displayFormat>U-{0000}</displayFormat>
        <label>Unsealed Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unsealeds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unsealed__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipName>Goods_Issues</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unsealed_Item__c/Unsealed_Item__c.object-meta.xml
<CustomObject>
    <label>Unsealed Item</label>
    <nameField>
        <displayFormat>UI-{0000}</displayFormat>
        <label>Unsealed Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unsealed Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unsealed_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipName>Goods_Issue_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unsealed_Item__c/fields/Stock__c.field-meta.xml
<CustomField>
    <fullName>Stock__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stock</label>
    <referenceTo>Stock__c</referenceTo>
    <relationshipName>Goods_Issue_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unsealed_Item__c/fields/Unsealed__c.field-meta.xml
<CustomField>
    <fullName>Unsealed__c</fullName>
    <label>Unsealed</label>
    <referenceTo>Unsealed__c</referenceTo>
    <relationshipLabel>Unsealed Items</relationshipLabel>
    <relationshipName>Unsealed_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/StockTrackerBatch.cls
global class StockTrackerBatch  implements Database.Batchable<sObject>,Database.Stateful,Schedulable{
    
    public Database.QueryLocator start(Database.BatchableContext BC){
        String query='select Id,Name,Product_Code__c,Company_Id__c from Product__c';
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<Product__c> scope){
        Set<String> pIds = new Set<String>();
        
        List<Route__c> rtList = new List<Route__c>();
        
        rtList = [select Id,Name,CompanyId__c,OwnerId from Route__c ];
        
        
        for(Product__c pro : scope){
            for(Route__c rt:rtList){
                if(pro.Company_Id__c == rt.CompanyId__c){
                    string ext = String.valueOf(pro.Id) + String.valueOf(rt.Id) + system.today();
                    pIds.add(ext);
                }
                
            }
        }
        
        List<AggregateResult> avaggList = [select Product__c prod,Route__c rt, SUM(Available_Quantity__c) availQty from Stock__c where  Stock_Type__c='New' and Product__c IN:scope  group by Product__c,Route__c];
        Map<String,Decimal> availMap = new Map<String,Decimal>();
        for(AggregateResult agg:avaggList){
            string ext = String.valueOf(agg.get('prod')) + String.valueOf(agg.get('rt')) + system.today();
            availMap.put(ext,(Decimal)agg.get('availQty'));
        }
        
        List<AggregateResult> inaggList = [select Product__c prod,Route__c rt, SUM(Intial_Stock__c) initQty from Stock__c where CreatedDate = TODAY AND Stock_Type__c='New' and Product__c IN:scope  group by Product__c,Route__c];
        Map<String,Decimal> initMap = new Map<String,Decimal>();
        for(AggregateResult agg:inaggList){
            string ext = String.valueOf(agg.get('prod')) + String.valueOf(agg.get('rt')) + system.today();
            initMap.put(ext,(Decimal)agg.get('initQty'));
        }
        
        List<AggregateResult> damaggList = [select Product__c prod,Route__c rt, SUM(Available_Quantity__c) availQty from Stock__c where  Stock_Type__c='Damaged' and Product__c IN:scope  AND CreatedDate = TODAY  group by Product__c,Route__c];
        Map<String,Decimal> damMap = new Map<String,Decimal>();
        for(AggregateResult agg:damaggList){
            string ext = String.valueOf(agg.get('prod')) + String.valueOf(agg.get('rt')) + system.today();
            damMap.put(ext,(Decimal)agg.get('availQty'));
        }
        
        List<AggregateResult> avaggListSold = [select Product__c prod,Sales_Invoice__r.Route__c rt, SUM(Quantity__c) soldQty from Sales_Invoice_Item__c where createddate=today AND Sales_Invoice__r.Sales_Invoice_Status__c !='Cancelled' and Product__c IN:scope group by Product__c,Sales_Invoice__r.Route__c];
        Map<String,Decimal> soldMap = new Map<String,Decimal>();
        for(AggregateResult agg:avaggListSold){
            string ext = String.valueOf(agg.get('prod')) + String.valueOf(agg.get('rt')) + system.today();
            soldMap.put(ext,(Decimal)agg.get('soldQty'));
        }
        
        List<AggregateResult> avaggListFree = [select Product__c prod,Unsealed__r.Route__c rt, SUM(Quantity__c) freeQty from Unsealed_Item__c where createddate=today  and Product__c IN:scope group by Product__c,Unsealed__r.Route__c];
        Map<String,Decimal> freeMap = new Map<String,Decimal>();
        for(AggregateResult agg:avaggListFree){
            string ext = String.valueOf(agg.get('prod')) + String.valueOf(agg.get('rt')) + system.today();
            freeMap.put(ext,(Decimal)agg.get('freeQty'));
        }

         List<AggregateResult> avaggListRep = [select New_Created_Stock__r.Product__c prod,Item_Replacement__r.Route__c rt, SUM(Quantity__c) repQty from Replaced_Item__c where createddate=today  and New_Created_Stock__r.Product__c IN:scope group by New_Created_Stock__r.Product__c,Item_Replacement__r.Route__c];
        Map<String,Decimal> repMap = new Map<String,Decimal>();
        for(AggregateResult agg:avaggListRep){
            string ext = String.valueOf(agg.get('prod')) + String.valueOf(agg.get('rt')) + system.today();
            repMap.put(ext,(Decimal)agg.get('repQty'));
        }
        
        List<Stock_History__c> hisList = [select Id,Name,Route__c,Product__c,Available_Quantity__c,Initial_Quantity__c,
                                          Damaged_Quantity__c,Free_Quantity__c,Sold_Quantity__c,
                                          Replaced_Quantity__c,Unsealed_Quantity__c,CreatedDate,Ext_ID__c from Stock_History__c where  Ext_ID__c IN:pIds];
        List<Stock_History__c> hisListToUpdate = new List<Stock_History__c>();
        if(hisList.size() > 0){
            for(Stock_History__c his : hisList){
                his.Available_Quantity__c = availMap.containsKey(his.Ext_ID__c) ? availMap.get(his.Ext_ID__c) : his.Available_Quantity__c;
                his.Initial_Quantity__c = initMap.containsKey(his.Ext_ID__c) ? initMap.get(his.Ext_ID__c) : his.Initial_Quantity__c;
                his.Damaged_Quantity__c = damMap.containsKey(his.Ext_ID__c) ? damMap.get(his.Ext_ID__c) : his.Damaged_Quantity__c;
                his.Unsealed_Quantity__c = freeMap.containsKey(his.Ext_ID__c) ? freeMap.get(his.Ext_ID__c) : his.Unsealed_Quantity__c;
                his.Sold_Quantity__c = soldMap.containsKey(his.Ext_ID__c) ? soldMap.get(his.Ext_ID__c) : his.Sold_Quantity__c;
                his.Replaced_Quantity__c =  repMap.containsKey(his.Ext_ID__c) ? repMap.get(his.Ext_ID__c) : his.Replaced_Quantity__c;
                hisListToUpdate.add(his);
            }
        }
        
        try {
            update hisListToUpdate;
        }
        catch (System.Exception ae) { 
            ExceptionHandler.addLog(ae,String.valueOf(hisListToUpdate) );
        }  
    }

    
    public void finish(Database.BatchableContext BC){
    }
    
    global void execute(SchedulableContext SC){
        database.executeBatch(new StockTrackerBatch(),1);
        
    } 
    
}