force-app/main/default/objects/Sales_order__c/Sales_order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{0000}</displayFormat>
        <label>Sales order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DeleteRecordsWithinDateRange.cls
global class  DeleteRecordsWithinDateRange implements Database.Batchable <Sobject>{
    global string query;
    Date startDate;
    Date endDate;
    string objectName;
    integer count=0;
    integer successCount=0;
    integer failedCount=0;
    global DeleteRecordsWithinDateRange(Date startDate, Date endDate,string objectName,integer count) {
        this.startDate = startDate;
        this.endDate = endDate;
         this.objectName = objectName;
         this.count = count;
        query = 'SELECT Id FROM '+objectName +' WHERE CreatedDate >= :startDate AND CreatedDate <= :endDate';
        if(objectName == 'Sales_Order__c'){
            query += ' AND Status__c = \'Converted\'';
        }
        system.debug(query);
    }
    Global Database.QueryLocator Start(Database.BatchableContext bcontext) {
        return Database.getQueryLocator( query);
    }
    Global void Execute(Database.BatchableContext bcontext,list<Sobject> recordToProcess){
        Database.DeleteResult[] results = Database.delete(recordToProcess, false);
        for (Database.DeleteResult res : results) {
    if (res.isSuccess()) {
        successCount++;
    } else {
        failedCount++;
    }
}

System.debug('Success: ' + successCount + ', Failed: ' + failedCount);
    }
    global void finish(Database.BatchableContext BC) {
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[] {'nanma@fingertipplus.com','mayuri.patel@fingertipplus.com','networkadmin@seraphinedevimpex.com'};//'mayuri.patel@fingertipplus.com',
        mail.setToAddresses(toAddresses);
        mail.setSubject('Batch Job Complete');
        string htmlbody ='The batch job to delete .<br/>Object Name: '+objectName+'<br/>  Date range : '+startDate +' to '+endDate +'<br/> Data Count :'+count ;
        mail.setHtmlBody(htmlbody);
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }
}