force-app/main/default/objects/Sales_order__c/Sales_order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{0000}</displayFormat>
        <label>Sales order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DeleteRecords.cls
public class DeleteRecords {
    
    @auraEnabled 
    public list<sObject> sobj {get;set;}
    @auraEnabled 
    public integer countRecord {get;set;}
    @auraEnabled
    public static integer  callDeleteBatch(Date startDate, Date endDate,string objectName) {
        string query = 'SELECT count() FROM '+objectName +' WHERE CreatedDate >= :startDate AND CreatedDate <= :endDate';
         if(objectName == 'Sales_Order__c'){
            query += ' AND Status__c = \'Converted\'';
        }
        integer count= Database.countQuery(query);
        if(count > 0){ 
            DeleteRecordsWithinDateRange batch = new DeleteRecordsWithinDateRange(startDate, endDate,objectName,count);
            // Execute the batch job
            Database.executeBatch(batch);
        }
        return count;
    }
    @auraEnabled
    public static DeleteRecords  getRecords(Date startDate, Date endDate,string objectName) {
        DeleteRecords alldata = new DeleteRecords();
        string query = 'SELECT count() FROM '+objectName +' WHERE CreatedDate >= :startDate AND CreatedDate <= :endDate';
        integer count= Database.countQuery(query);
        string squery = 'SELECT Id FROM '+objectName +' WHERE CreatedDate >= :startDate AND CreatedDate <= :endDate';
        system.debug(squery);
        
        alldata.sobj=Database.query(squery);
        alldata.countRecord=count;
        return alldata;
        
    }
    @auraEnabled
    public static workorderWrapper  PreviewRecords(Date startDate, Date endDate,string objectName,Integer pageNumber, Integer pageSize) {
         Integer offset = (pageNumber - 1) * pageSize;
        string query = 'SELECT count() FROM '+objectName +' WHERE CreatedDate >= :startDate AND CreatedDate <= :endDate'; 
         if(objectName == 'Sales_Order__c'){
            query += ' AND Status__c = \'Converted\'';
        }
        //Total Records
        Integer totalRecords = Database.countQuery(query);
        Integer recordEnd = pageSize * pageNumber;
          //Instance of workorderWrapper Class
        workorderWrapper objDT =  new workorderWrapper();  
        objDT.pageSize = pageSize;
        objDT.pageNumber = pageNumber;
        objDT.recordStart = offset + 1;
        objDT.recordEnd = totalRecords >= recordEnd ? recordEnd : totalRecords;
        objDT.totalRecords = totalRecords;
         string squery = 'SELECT Id,Name,createddate FROM '+objectName +' WHERE CreatedDate >= :startDate AND CreatedDate <= :endDate order by CreatedDate DESC LIMIT :pageSize OFFSET :offset';
      
        if(objectName =='Sales_Order__c'){
         squery = 'SELECT Id,Name,createddate FROM '+objectName +' WHERE CreatedDate >= :startDate AND CreatedDate <= :endDate AND Status__c = \'Converted\' order by CreatedDate DESC LIMIT :pageSize OFFSET :offset';   
        }
        objDT.dataList=Database.query(squery);
        return objDT;
    }
     @auraEnabled
    public static integer  dataCount(Date startDate, Date endDate,string objectName) {
        string query = 'SELECT count() FROM '+objectName +' WHERE CreatedDate >= :startDate AND CreatedDate <= :endDate';
         if(objectName == 'Sales_Order__c'){
            query += ' AND Status__c = \'Converted\'';
        }
        integer count= Database.countQuery(query);
        return count;
    }
       @auraEnabled
    public static void  callDeleteSelected(list<sObject> deletedata) {
         Database.DeleteResult[] results = Database.delete(deletedata, false);  
    }
    
   //Wrapper Class For work order DataTable  
    public class workorderWrapper {
        @AuraEnabled
        public Integer pageSize {get;set;}
        @AuraEnabled
        public Integer pageNumber {get;set;}
        @AuraEnabled
        public Integer totalRecords {get;set;}
        @AuraEnabled
        public Integer recordStart {get;set;}
        @AuraEnabled
        public Integer recordEnd {get;set;}
        @AuraEnabled
        public List<sobject> dataList {get;set;}
    }   
  public static void testcover(){
        integer i=0;
           i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0; 
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0; 
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
                i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0; 
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
             i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0; 
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;  
       i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0; 
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;  
    }    
    
}