force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>Stock-{00000}</displayFormat>
        <label>Stock Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/fields/Available_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Available_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Available Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Intial_Stock__c.field-meta.xml
<CustomField>
    <fullName>Intial_Stock__c</fullName>
    <label>Intial Stock</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Mismatch_Qty__c.field-meta.xml
<CustomField>
    <fullName>Mismatch_Qty__c</fullName>
    <label>Mismatch Qty</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ClearStockController.cls
public class ClearStockController {
     public List<Route__c> routeList;
      public boolean isError{get;set;}
    
      // Constructor
      public ClearStockController(ApexPages.StandardSetController cntlr){
           routeList = cntlr.getSelected(); //get selected records from account list view
         
      } 

    public PageReference clearStock(){
        system.debug('routeList:' + routeList);
        
        Profile pr = [select id,name from Profile where Id=:UserInfo.getProfileId() limit 1];
        
        if(pr.Name != 'ADMIN' && pr.Name != 'System Administrator' ){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'You don\'t have sufficient priviliges. Please Contact Admin.'));
            isError = true;
            return null;
        }
        else{
            if(routeList.size() <= 0){
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'No records selected.'));
                isError = true;
                return null;
            }
            else{
               /* List<Stock__c> stlist = [select Id,Name, Intial_Stock__c, Available_Quantity__c, Mismatch_Qty__c, CreatedDate, Route__r.Name from Stock__c where Route__c IN :routeList and Available_Quantity__c != 0];
                  system.debug('stlist:' + stlist);
                for(Stock__c st:stlist){
                    st.Mismatch_Qty__c = st.Available_Quantity__c;
                    st.Available_Quantity__c = 0;
                }
                update stlist; */
           string query ='select Id,Name from Route__c where Id in :routeList';                
            ClearStock_Btach batch = new ClearStock_Btach(query,routeList);
            Database.executeBatch(batch);  // Execute the batch job
                
                return new ApexPages.Action('{!List}').invoke();
            }
        }
       //return null;
       
    }
    
   /*   public PageReference redirectToLC(){
            String returnUrl = '/lightning/cmp/c__ProcessListView?c__listofAccounts='+routeIds;
            PageReference pgReturnPage = new PageReference(returnUrl);
            pgReturnPage.setRedirect(true);
            return pgReturnPage;
          //  return null;
      }*/

}