force-app/main/default/objects/Invoice_Number_Series__c/Invoice_Number_Series__c.object-meta.xml
<CustomObject>
    <label>Invoice Number Series</label>
    <nameField>
        <label>Series Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Number Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Number_Series__c/fields/End_Number__c.field-meta.xml
<CustomField>
    <fullName>End_Number__c</fullName>
    <label>End Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Number_Series__c/fields/Invoice_number_prefix__c.field-meta.xml
<CustomField>
    <fullName>Invoice_number_prefix__c</fullName>
    <label>Invoice number prefix</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Number_Series__c/fields/Invoice_Post_fix__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Post_fix__c</fullName>
    <label>Invoice Post fix</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Number_Series__c/fields/Last_Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Last_Invoice_Number__c</fullName>
    <label>Last Invoice Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Number_Series__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipName>Invoice_number_series</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Number_Series__c/fields/Start_Number__c.field-meta.xml
<CustomField>
    <fullName>Start_Number__c</fullName>
    <label>Start Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Route__c/fields/End_Number__c.field-meta.xml
<CustomField>
    <fullName>End_Number__c</fullName>
    <label>End Number</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Route__c/fields/Route_Id__c.field-meta.xml
<CustomField>
    <fullName>Route_Id__c</fullName>
    <externalId>true</externalId>
    <label>Route Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Route__c/fields/Start_Number__c.field-meta.xml
<CustomField>
    <fullName>Start_Number__c</fullName>
    <label>Start Number</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice__c/Sales_Invoice__c.object-meta.xml
<CustomObject>
    <label>Sales Invoice</label>
    <nameField>
        <label>Sales Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Invoice__c/fields/Invoice_Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Full_Name__c</fullName>
    <label>Invoice Full Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Sales Invoices</relationshipLabel>
    <relationshipName>Sales_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UpdateInvoiceFullName.cls
public class UpdateInvoiceFullName {
    
    public static void updateName(List<Sales_Invoice__c> salesInvoiceList){
        
        Set<Id> routeIds = new Set<Id>();
        for(Sales_Invoice__c salesInv : salesInvoiceList){
            if(salesInv.Route__c != null){
                routeIds.add(salesInv.Route__c);
            }
        }
        
        Map<Id,Invoice_Number_Series__c> inMap = new Map<Id,Invoice_Number_Series__c>();
        
        List<Route__c> rtlist = [select Id,Name,Route_Id__c,(select id,Route__c,Invoice_number_prefix__c,Last_Invoice_Number__c,Start_Number__c,End_Number__c,Invoice_Post_fix__c from Invoice_Number_Series__r where Active__c = true order by createddate desc limit 1),
                                 (select Id,Name from Sales_Invoices__r Order By CreatedDate Desc Limit 1)
                                 from Route__c where Id in :routeIds];
        
        for(Route__c rt: rtlist){
            if(rt.Invoice_Number_Series__r.size() > 0){
                inMap.put(rt.Id,rt.Invoice_Number_Series__r);
            }
        }
        
        for(Sales_Invoice__c salesInv : salesInvoiceList){
            system.debug('calling SalesInvoiceTriggerHandler====');
            
            if(inMap.size() > 0 && salesInv.Route__c != null){
                Invoice_Number_series__c ins = inMap.get(salesInv.Route__c);
                
                if(ins != null){
                    if(ins.Invoice_number_prefix__c != null && ins.Invoice_Post_fix__c != null){
                        salesInv.Invoice_Full_Name__c = ins.Invoice_number_prefix__c + string.valueOf(salesInv.Name) + ins.Invoice_Post_fix__c; 
                    }
                    else if(ins.Invoice_number_prefix__c != null && ins.Invoice_Post_fix__c == null){
                        salesInv.Invoice_Full_Name__c = ins.Invoice_number_prefix__c + string.valueOf(salesInv.Name); 
                    }
                    else if(ins.Invoice_number_prefix__c == null && ins.Invoice_Post_fix__c != null){
                        salesInv.Invoice_Full_Name__c = string.valueOf(salesInv.Name) + ins.Invoice_Post_fix__c; 
                    }
                    else{
                        salesInv.Invoice_Full_Name__c = string.valueOf(salesInv.Name);
                    }
                }
                
                
            }
            
            
        }
        update salesInvoiceList;
        
    }
}