force-app/main/default/objects/Invoice_Number_Series__c/Invoice_Number_Series__c.object-meta.xml
<CustomObject>
    <label>Invoice Number Series</label>
    <nameField>
        <label>Series Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Number Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Number_Series__c/fields/End_Number__c.field-meta.xml
<CustomField>
    <fullName>End_Number__c</fullName>
    <label>End Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Number_Series__c/fields/Last_Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Last_Invoice_Number__c</fullName>
    <label>Last Invoice Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Number_Series__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipName>Invoice_number_series</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Number_Series__c/fields/Start_Number__c.field-meta.xml
<CustomField>
    <fullName>Start_Number__c</fullName>
    <label>Start Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Route__c/fields/End_Number__c.field-meta.xml
<CustomField>
    <fullName>End_Number__c</fullName>
    <label>End Number</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Route__c/fields/Route_Id__c.field-meta.xml
<CustomField>
    <fullName>Route_Id__c</fullName>
    <externalId>true</externalId>
    <label>Route Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Route__c/fields/Start_Number__c.field-meta.xml
<CustomField>
    <fullName>Start_Number__c</fullName>
    <label>Start Number</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/InvoiceNumberSeriesTriggerHandler.cls
public class InvoiceNumberSeriesTriggerHandler {

    public static void addLastInvoiceNumber(List<Invoice_Number_Series__c> invNumberSeriesRecords){
        //String useRrouteId = [select Id,Route_Id__c from User where Id =: UserInfo.getUserId() Limit 1][0].Route_Id__c;
        //Route__c route = [select Id,Route_Id__c,(select Id,Last_Invoice_Number__c from Invoice_Number_Series__r) from Route__c where Route_Id__c =: useRrouteId Limit 1];
        List<Invoice_Number_Series__c> activeInvoiceNumberSeriesRecords = [select Id,Name,Route__c,Start_Number__c,End_Number__c,Last_Invoice_Number__c 
                                                                           from Invoice_Number_Series__c 
                                                                           where Active__c =: true];
        
        Map<Id,Invoice_Number_Series__c> insMap = new Map<Id,Invoice_Number_Series__c>();
        for(Invoice_Number_Series__c ins: activeInvoiceNumberSeriesRecords ){
            insMap.put(ins.Route__c,ins);
        }
        system.debug('activeInvoiceNumberSeriesRecords : '+activeInvoiceNumberSeriesRecords);
        
        for(Invoice_Number_Series__c invNumberSeries : invNumberSeriesRecords){
            
            if(insMap.containsKey(invNumberSeries.Route__c)){
                invNumberSeries.Active__c.addError('There will be only one active Invoice Number Series for each Route.');
            }
            
            Route__c route = [select Id,Route_Id__c,(select Id,Last_Invoice_Number__c from Invoice_Number_Series__r) from Route__c 
                              where Id =: invNumberSeries.Route__c Limit 1];
            //if(invNumberSeries.Route__c == route.Id){
                if(route.Invoice_Number_Series__r.size()>0){
                    Invoice_Number_Series__c invoiceNumberSeriesRecord = [select Id,Name,Start_Number__c,End_Number__c,Last_Invoice_Number__c 
                                                                          from Invoice_Number_Series__c
                                                                          where Route__c =: route.Id Order By CreatedDate Desc Limit 1];
                    
                    System.debug('invoiceNumberSeriesRecords : '+invoiceNumberSeriesRecord);
                    invNumberSeries.Last_Invoice_Number__c = invoiceNumberSeriesRecord.Last_Invoice_Number__c + 1;
                }else{
                    invNumberSeries.Last_Invoice_Number__c = 0;
                }
            //}
        }
    }
}