force-app/main/default/objects/Invoice_Number_Series__c/Invoice_Number_Series__c.object-meta.xml
<CustomObject>
    <label>Invoice Number Series</label>
    <nameField>
        <label>Series Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Number Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Number_Series__c/fields/Invoice_number_prefix__c.field-meta.xml
<CustomField>
    <fullName>Invoice_number_prefix__c</fullName>
    <label>Invoice number prefix</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Number_Series__c/fields/Invoice_Post_fix__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Post_fix__c</fullName>
    <label>Invoice Post fix</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Number_Series__c/fields/Last_Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Last_Invoice_Number__c</fullName>
    <label>Last Invoice Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Number_Series__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipName>Invoice_number_series</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Number_Series__c/fields/Start_Number__c.field-meta.xml
<CustomField>
    <fullName>Start_Number__c</fullName>
    <label>Start Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/CompanyId__c.field-meta.xml
<CustomField>
    <fullName>CompanyId__c</fullName>
    <label>Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Company</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>REC-{0000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/Approval_status__c.field-meta.xml
<CustomField>
    <fullName>Approval_status__c</fullName>
    <defaultValue>&apos;New&apos;</defaultValue>
    <label>Approval status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted for approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Approval_Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/On_Account_Value__c.field-meta.xml
<CustomField>
    <fullName>On_Account_Value__c</fullName>
    <label>On Account Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipName>Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Sales_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Invoice</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (2 AND 3)</booleanFilter>
        <filterItems>
            <field>Sales_Invoice__c.Pending_Amount__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <filterItems>
            <field>Sales_Invoice__c.Customer__c</field>
            <operation>equals</operation>
            <valueField>$Source.Customer__c</valueField>
        </filterItems>
        <filterItems>
            <field>Sales_Invoice__c.Pending_Amount_SAP__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Sales_Invoice__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Tax_Date__c.field-meta.xml
<CustomField>
    <fullName>Tax_Date__c</fullName>
    <label>Tax Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Against Invoice</fullName>
            </value>
            <value>
                <fullName>On Account</fullName>
            </value>
            <value>
                <fullName>Bouncing Charge</fullName>
            </value>
            <value>
                <fullName>Multiple Invoice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipName>Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Route__c/fields/CompanyId__c.field-meta.xml
<CustomField>
    <fullName>CompanyId__c</fullName>
    <label>Company Id</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Company</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Route__c/fields/Route_Id__c.field-meta.xml
<CustomField>
    <fullName>Route_Id__c</fullName>
    <externalId>true</externalId>
    <label>Route Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Route__c/fields/Start_Number__c.field-meta.xml
<CustomField>
    <fullName>Start_Number__c</fullName>
    <label>Start Number</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Route__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Routes</relationshipLabel>
    <relationshipName>Routes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice__c/Sales_Invoice__c.object-meta.xml
<CustomObject>
    <label>Sales Invoice</label>
    <nameField>
        <label>Sales Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Invoice__c/fields/CompanyId__c.field-meta.xml
<CustomField>
    <fullName>CompanyId__c</fullName>
    <formula>TEXT( Customer__r.CompanyId__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Invoices</relationshipLabel>
    <relationshipName>Sales_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice__c/fields/Doc_Date__c.field-meta.xml
<CustomField>
    <fullName>Doc_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Doc Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Immediate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Invoice__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Sales Invoices</relationshipLabel>
    <relationshipName>Sales_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice__c/fields/Tax_Date__c.field-meta.xml
<CustomField>
    <fullName>Tax_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Tax Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Sales Invoices</relationshipLabel>
    <relationshipName>Sales_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice_Item__c/Sales_Invoice_Item__c.object-meta.xml
<CustomObject>
    <label>Sales Invoice Item</label>
    <nameField>
        <displayFormat>ITEM-{0000}</displayFormat>
        <label>Sales Invoice Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Invoice Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Invoice_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Sales Invoice Items</relationshipLabel>
    <relationshipName>Sales_Invoice_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice_Item__c/fields/Sales_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice__c</fullName>
    <label>Sales Invoice</label>
    <referenceTo>Sales_Invoice__c</referenceTo>
    <relationshipLabel>Invoice Items</relationshipLabel>
    <relationshipName>Invoice_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>Stock-{00000}</displayFormat>
        <label>Stock Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saleable</fullName>
            </value>
            <value>
                <fullName>Non-Saleable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SalesInvoiceTriggerHandlerTest.cls
@IsTest
public class SalesInvoiceTriggerHandlerTest {
    @IsTest
    public static void salesInvoiceTriggerTest1() {
        // Create test data
        Account testAccount = new Account(
            Name = 'Test Account',
            Approval_Status__c = 'Approved',
            CompanyId__c = 'Dev'
        );
        insert testAccount;
        
        testAccount.Approval_Status__c = 'Approved';
        update testAccount;
        
        Route__c testRoute = new Route__c(
            Route_Id__c = 'Route123'
        );
        insert testRoute;
        
        Receipt__c testReceipt = new Receipt__c(
            Type__c = 'On Account',
            On_Account_Value__c = 25563.53,
            Customer__c = testAccount.Id
        );
        insert testReceipt;
        
        // Create a test Sales_Invoice__c record
         Warehouse__c wh = new Warehouse__c();
        wh.name = 'test';
        insert wh;
        
        User user = [select id,name,Route_Id__c from User where id=:UserInfo.getUserId() limit 1];
        Route__c r = new Route__c();
        r.warehouse__c = wh.id;
        r.Name = 'test route';
        r.Route_Id__c = user.Route_Id__c;
        insert r;
        
        List<Sales_invoice__c>salesInvoices = new List<Sales_invoice__c>();
         Sales_invoice__c salesInvoice = new Sales_invoice__c();
         salesInvoice.Customer__c = testAccount.id;
         salesInvoice.Route__c = r.id;
         salesInvoice.Doc_Date__c = Date.NewInstance(2022,03,09);
         salesInvoice.Tax_Date__c = Date.NewInstance(2022,03,09);
         salesInvoice.Payment_Type__c = 'Credit';
        //insert salesInvoice;
        salesInvoices.add(salesInvoice);
        
        test.startTest();
     //   SalesInvoiceTriggerHandler.insertSalesInvoiceName(salesInvoices);
        SalesInvoiceTriggerHandler.insertSalesInvoiceName2(salesInvoices);
        test.stopTest();        
        system.debug('salesInvoice.Name=== '+salesInvoice.Name);
        //system.assertEquals(salesInvoice.Name, 'INV-1/2024');
    }
    
    @IsTest
    public static void salesInvoiceTriggerTest2() {
        // Create test data
        Account testAccount = new Account(
            Name = 'Test Account',
            Approval_Status__c = 'Approved',
            CompanyId__c = 'Dev'
        );
        insert testAccount;
        
        testAccount.Approval_Status__c = 'Approved';
        update testAccount;
        
        Route__c testRoute = new Route__c(
            Route_Id__c = '123'
        );
        insert testRoute;
        
        
        Invoice_Number_Series__c invNumSeries = new Invoice_Number_Series__c(
            Last_Invoice_Number__c = 1,
            Invoice_number_prefix__c = 'INV-',
            Start_Number__c = 1,
            Invoice_Post_fix__c = '/2024',
            Route__c = testRoute.id,
            Active__c = true
        );
        insert invNumSeries;
        
        Receipt__c testReceipt = new Receipt__c(
            Type__c = 'On Account',
            On_Account_Value__c = 25563.53,
            Customer__c = testAccount.Id
        );
        insert testReceipt;
        
        // Create a test Sales_Invoice__c record
         Warehouse__c wh = new Warehouse__c();
        wh.name = 'test';
        insert wh;
        
        List<Sales_invoice__c>salesInvoices = new List<Sales_invoice__c>();
         Sales_invoice__c salesInvoice = new Sales_invoice__c();
        salesInvoice.Name = 'INV-3/2024';
         salesInvoice.Customer__c = testAccount.id;
         salesInvoice.Route__c = testRoute.id;
         salesInvoice.Doc_Date__c = Date.NewInstance(2022,03,09);
         salesInvoice.Tax_Date__c = Date.NewInstance(2022,03,09);
         salesInvoice.Payment_Type__c = 'Credit';
        //insert salesInvoice;
                Sales_invoice__c salesInvoice1 = new Sales_invoice__c();
        salesInvoice1.Name = '20023';
         salesInvoice1.Customer__c = testAccount.id;
         salesInvoice1.Route__c = testRoute.id;
         salesInvoice1.Doc_Date__c = Date.NewInstance(2022,03,09);
         salesInvoice1.Tax_Date__c = Date.NewInstance(2022,03,09);
         salesInvoice1.Payment_Type__c = 'Credit';

     //  insert salesInvoice1;
        salesInvoices.add(salesInvoice);
        
        test.startTest();
        //SalesInvoiceTriggerHandler.insertSalesInvoiceName(salesInvoices);
        //SalesInvoiceTriggerHandler.updateLastInvoiceNumber(salesInvoices);
        SalesInvoiceTriggerHandler.insertSalesInvoiceName2(salesInvoices);
        //SalesInvoiceTriggerHandler.insertSalesInvoiceSeriesUpdate(salesInvoice1);
        test.stopTest();        
        
    }
    
    @IsTest
    public static void salesInvoiceTriggerTest3() {
        // Create test data
        Account testAccount = new Account(
            Name = 'Test Account',
            Approval_Status__c = 'Approved',
            CompanyId__c = 'Dev'
        );
        insert testAccount;
        
        testAccount.Approval_Status__c = 'Approved';
        update testAccount;
        
        Route__c testRoute = new Route__c(
            Route_Id__c = 'Route456'
        );
        insert testRoute;
        
        
        Invoice_Number_Series__c invNumSeries = new Invoice_Number_Series__c(
            Last_Invoice_Number__c = 1,
            Invoice_number_prefix__c = 'INV-',
            Start_Number__c = 1,
            Invoice_Post_fix__c = null,
            Route__c = testRoute.id,
            Active__c = true 
        );
        insert invNumSeries;
        
        Receipt__c testReceipt = new Receipt__c(
            Type__c = 'On Account',
            On_Account_Value__c = 25563.53,
            Customer__c = testAccount.Id
        );
        insert testReceipt;
        
        // Create a test Sales_Invoice__c record
         Warehouse__c wh = new Warehouse__c();
        wh.name = 'test';
        insert wh;
        
        List<Sales_invoice__c>salesInvoices = new List<Sales_invoice__c>();
         Sales_invoice__c salesInvoice = new Sales_invoice__c();
         salesInvoice.Customer__c = testAccount.id;
         salesInvoice.Route__c = testRoute.id;
         salesInvoice.Doc_Date__c = system.today();
         salesInvoice.Tax_Date__c = system.today();
        salesInvoices.add(salesInvoice);
        
        test.startTest();
       // SalesInvoiceTriggerHandler.insertSalesInvoiceName(salesInvoices);
        SalesInvoiceTriggerHandler.insertSalesInvoiceName2(salesInvoices);
        test.stopTest();
        system.assertEquals(salesInvoice.Name, '1');
    }
    
       @IsTest
    public static void salesInvoiceTriggerTest4() {
        // Create test data
        Account testAccount = new Account(
            Name = 'Test Account',
            Approval_Status__c = 'Approved',
            CompanyId__c = 'Dev'
        );
        insert testAccount;
        
        testAccount.Approval_Status__c = 'Approved';
        update testAccount;
        
        Route__c testRoute = new Route__c(
            Route_Id__c = '123'
        );
        insert testRoute;
        
        Receipt__c testReceipt = new Receipt__c(
            Type__c = 'On Account',
            On_Account_Value__c = 25563.53,
            Customer__c = testAccount.Id
        );
        insert testReceipt;
        
        // Create a test Sales_Invoice__c record
         Warehouse__c wh = new Warehouse__c();
        wh.name = 'test';
        insert wh;
        
        List<Sales_invoice__c>salesInvoices = new List<Sales_invoice__c>();
         Sales_invoice__c salesInvoice = new Sales_invoice__c();
        salesInvoice.Name = 'INV-3/2023';
         salesInvoice.Customer__c = testAccount.id;
         salesInvoice.Route__c = testRoute.id;
         salesInvoice.Doc_Date__c = Date.NewInstance(2022,03,09);
         salesInvoice.Tax_Date__c = Date.NewInstance(2022,03,09);
         salesInvoice.Payment_Type__c = 'Credit';
        insert salesInvoice;
                Sales_invoice__c salesInvoice1 = new Sales_invoice__c();
        salesInvoice1.Name = '20023';
         salesInvoice1.Customer__c = testAccount.id;
         salesInvoice1.Route__c = testRoute.id;
         salesInvoice1.Doc_Date__c = Date.NewInstance(2022,03,09);
         salesInvoice1.Tax_Date__c = Date.NewInstance(2022,03,09);
         salesInvoice1.Payment_Type__c = 'Credit';

        salesInvoices.add(salesInvoice);
        update salesInvoice;
        test.startTest();
       // SalesInvoiceTriggerHandler.insertSalesInvoiceName(salesInvoices);
        //SalesInvoiceTriggerHandler.updateLastInvoiceNumber(salesInvoices);
        SalesInvoiceTriggerHandler.insertSalesInvoiceName2(salesInvoices);
       // SalesInvoiceTriggerHandler.insertSalesInvoiceSeriesUpdate(salesInvoice1);
        test.stopTest();        
        
    }
    
    @IsTest
    public static void salesInvoiceTriggerTest5() {
         Account testAccount = new Account(
            Name = 'Test Account',
            Approval_Status__c = 'Approved',
            CompanyId__c = 'Dev'
        );
        insert testAccount;
        
        testAccount.Approval_Status__c = 'Approved';
        update testAccount;
        
        Route__c testRoute = new Route__c(
            Route_Id__c = 'Route456'
        );
        insert testRoute;
               
         Sales_invoice__c salesInvoice = new Sales_invoice__c();
         salesInvoice.Name = 'INV-31/2023';
         salesInvoice.Customer__c = testAccount.id;
         salesInvoice.Route__c = testRoute.id;
         salesInvoice.Doc_Date__c = system.today();
         salesInvoice.Tax_Date__c = system.today();
        salesInvoice.Invoice_Date__c = system.today();
        salesInvoice.Payment_Type__c = 'Credit';
        insert salesInvoice;
          Sales_invoice__c salesInvoice1 = new Sales_invoice__c();
         salesInvoice1.Name = 'INV-30/2023';
         salesInvoice1.Customer__c = testAccount.id;
         salesInvoice1.Route__c = testRoute.id;
         salesInvoice1.Doc_Date__c = system.today();
         salesInvoice1.Tax_Date__c = system.today();
        salesInvoice.Invoice_Date__c = system.today()+1;
        salesInvoice1.Payment_Type__c = 'Immediate';
      //  insert salesInvoice1;
        
        salesInvoice.SAP_Code__c='123';
      // update salesInvoice1;
         Receipt__c testReceipt = new Receipt__c(
            Type__c = 'On Account',
            On_Account_Value__c = 25563.53,
            Customer__c = testAccount.Id
        );
        insert testReceipt;
        
        Product__c productRec = new Product__c();
        productRec.Name = 'Dev Snacks Rosted peanut';
        productRec.Product_Code__c = 'P100';
        productRec.MRP__c = 25;
        productRec.GST__c = '5';
        insert productRec;
        
        Stock__c stock = new Stock__c();
        stock.Intial_Stock__c = 100;
        stock.Available_Quantity__c = 70;
        stock.Sold_Qty__c = 15;
        stock.Blocked_Quantity__c = 15;
        stock.Product__c = productRec.id;
        Insert stock;
        
        Sales_Invoice_Item__c slInvItem = new Sales_Invoice_Item__c();
        slInvItem.Total__c = 100;
        slInvItem.GST_Percentage__c = 1;
        slInvItem.Sales_Invoice__c = salesInvoice.Id;
        slInvItem.Product__c = stock.Product__c;
        slInvItem.Stock__c = stock.Id;
        slInvItem.Quantity__c = 1;
        slInvItem.Unit_Price__c = 100;
        slInvItem.Discount_Percent__c = 1;
        slInvItem.Total_after_discount__c = 100;
      //  insert slInvItem;
        
        StopRecursion.executeSalesInvoiceItemTrigger = true;
        salesInvoice1.Sales_Invoice_Status__c = 'Cancelled';
       // update salesInvoice1;
        
        
    }
   
}