force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>ADD-{0000}</displayFormat>
        <label>Sr. No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/Branch_Id__c.field-meta.xml
<CustomField>
    <fullName>Branch_Id__c</fullName>
    <label>Branch Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Seraphine Dev Impex Pvt</fullName>
            </value>
            <value>
                <fullName>Eva Traders</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/CompanyId__c.field-meta.xml
<CustomField>
    <fullName>CompanyId__c</fullName>
    <label>Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Company</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/GST__c.field-meta.xml
<CustomField>
    <fullName>GST__c</fullName>
    <label>GST</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GST_percentages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Image_Url__c.field-meta.xml
<CustomField>
    <fullName>Product_Image_Url__c</fullName>
    <label>Product Image Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Purchase_Tax__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Tax__c</fullName>
    <label>Purchase Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Route__c/fields/CompanyId__c.field-meta.xml
<CustomField>
    <fullName>CompanyId__c</fullName>
    <label>Company Id</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Company</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Route__c/fields/Route_Id__c.field-meta.xml
<CustomField>
    <fullName>Route_Id__c</fullName>
    <externalId>true</externalId>
    <label>Route Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Route__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Routes</relationshipLabel>
    <relationshipName>Routes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Request__c/Stock_Request__c.object-meta.xml
<CustomObject>
    <label>Stock Request</label>
    <nameField>
        <displayFormat>REQ-{0000}</displayFormat>
        <label>Stock Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_Request__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Stock Requests</relationshipLabel>
    <relationshipName>Stock_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Request__c/fields/CompanyId__c.field-meta.xml
<CustomField>
    <fullName>CompanyId__c</fullName>
    <formula>TEXT( Route__r.CompanyId__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock_Request__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Stock Requests</relationshipLabel>
    <relationshipName>Stock_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Transferred</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stock_Request__c/fields/Stock_Request_Id__c.field-meta.xml
<CustomField>
    <fullName>Stock_Request_Id__c</fullName>
    <displayFormat>REQ-{0000}</displayFormat>
    <externalId>true</externalId>
    <label>Stock Request Id</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Stock_Request__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Stock Requests</relationshipLabel>
    <relationshipName>Stock_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Request_Item__c/Stock_Request_Item__c.object-meta.xml
<CustomObject>
    <label>Stock Request Item</label>
    <nameField>
        <label>Stock Request Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stock Request Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_Request_Item__c/fields/Item_Code__c.field-meta.xml
<CustomField>
    <fullName>Item_Code__c</fullName>
    <formula>Product__r.Product_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Item Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock_Request_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Stock Request Items</relationshipLabel>
    <relationshipName>Stock_Request_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Request_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Transferred</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stock_Request_Item__c/fields/Stock_Request__c.field-meta.xml
<CustomField>
    <fullName>Stock_Request__c</fullName>
    <label>Stock Request</label>
    <referenceTo>Stock_Request__c</referenceTo>
    <relationshipLabel>Stock Request Items</relationshipLabel>
    <relationshipName>Stock_Request_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Stock_Request_Item__c/fields/Stock_Request_Item_Id__c.field-meta.xml
<CustomField>
    <fullName>Stock_Request_Item_Id__c</fullName>
    <externalId>true</externalId>
    <label>Stock Request Item Id</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Stock_Request_Item__c/fields/Transfered_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Transfered_Quantity__c</fullName>
    <label>Transfered Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Vehicle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SAPGetData_Test.cls
@isTest
public class SAPGetData_Test {
    @isTest 
    static void testproPostAPI() {
        
        
        String JsonMsg='{\"data\":[{\"Name\":\"Dev Snacks peanut Masala\",\"CompanyId__c\":\"Dev\",\"Product_Code__c\":\"P010\",\"SKU__c\":\"XYZ12345\",\"Product_Image_Url__c\":\"https:images-na.ssl-images-amazon.comimages1gY92G6x1L._SY879_.jpg\",\"Item_Description__c\":\"Dev Snacks peanut Masala\",\"Brand__c\":\"DJS23\",\"Sales_Tax__c\":2,\"HSN_Code__c\":\"HSN243\",\"Purchase_Tax__c\":5},{\"Name\":\"Dev Snacks Pakkavada\",\"CompanyId__c\":\"Dev\",\"Product_Code__c\":\"P011\",\"SKU__c\":\"XYZ12345\",\"Product_Image_Url__c\":\"https:content40163233_1-dev-snacks-pakkavadaribbon-pakoda.png\",\"Item_Description__c\":\"Dev Snacks Pakkavada\",\"Brand__c\":\"DJS23\",\"Sales_Tax__c\":2,\"HSN_Code__c\":\"HSN243\",\"Purchase_Tax__c\":5}]}';
        RestRequest request = new RestRequest();
        RestResponse res = new RestResponse();
        request.requestURI ='/services/apexrest/send/SAPGetData';
        request.params.put('key', '96ca585abb297b995fab61679e0516fb');
        request.params.put('value', 'productMaster');
        request.requestBody = Blob.valueof(JsonMsg);
        request.httpMethod = 'POST';
        RestContext.request = request;
        RestContext.response= res;
        SAPGetData.doPost();
    }
      @isTest 
    static void testtransPostAPI() {
        
         Product__c productRec = new Product__c();
        productRec.Name = 'Dev Snacks Rosted peanut';
        productRec.Product_Code__c = 'P100';
        productRec.MRP__c = 25;
        productRec.GST__c = '5';
        insert productRec;
        
        Route__c r = new Route__c();
        r.Name = 'test route';
        insert r;
        r=[select id,name,route_id__c from route__c where id=:r.Id];
        
         Branch__c br = new Branch__c();
        br.Name = 'tesbranch';
        br.Address__c = 'Bengaluru';
        br.Branch_Id__c = 453647;
        insert br;
        Stock_Request__c sr = new Stock_Request__c();
        
        sr.Branch__c = br.Id;
        //sr.Vehicle__c = vh.id;
        sr.Route__c = r.id;
        sr.Request_Date__c = Date.NewInstance(2022,03,09);
        insert sr;
        
        Stock_Request_Item__c srt = new Stock_Request_Item__c();
        srt.Name = 'Masala';
        srt.Received_Qunatity__c = 100;
        srt.Product__c = productRec.Id;
        srt.Stock_Request__c = sr.id;
        insert srt;
        
        sr=[select id,name,Stock_Request_Id__c from Stock_Request__c where id=:sr.Id];
        srt=[select id,name,stock_request_item_id__c from Stock_Request_Item__c where id=:srt.Id];
        
        system.debug('sr:' + sr.Stock_Request_Id__c);
        system.debug('srt:' + srt.Stock_Request_Item_Id__c);
        String JsonMsg='{\"data\":[{\"CompanyId__c\":\"Dev\",\"Stock_Request_Id__c\":\"'+sr.Stock_Request_Id__c+'\",\"Transfer_Date__c\":\"2023-06-02\",\"Route_Id__c\":\"'+r.route_id__c+'\",\"Branch_Id__c\":\"'+br.Branch_Id__c+'\",\"Stock_Request_Items__r\":[{\"Stock_Request_Item_Id__c\":\"'+srt.Stock_Request_Item_Id__c+'\",\"Item_Code__c\":\"TEST2\",\"Transfered_Quantity__c\":12,\"Status__c\":\"Transferred\",\"Batch_Number__c\":\"12\",\"MRP__c\":200,\"Expiry_Date__c\":\"2023-02-14\",\"Manufacturing_Date__c\":\"2023-02-14\"},{\"Item_Code__c\":\"P100\",\"Transfered_Quantity__c\":12,\"Status__c\":\"Transferred\",\"Batch_Number__c\":\"12\",\"MRP__c\":200,\"Expiry_Date__c\":\"2023-02-14\",\"Manufacturing_Date__c\":\"2023-02-14\"}]}]}';
        RestRequest request = new RestRequest();
        RestResponse res = new RestResponse();
        request.requestURI ='/services/apexrest/send/SAPGetData';
        request.params.put('key', '96ca585abb297b995fab61679e0516fb');
        request.params.put('value', 'StockTransfer');
        request.requestBody = Blob.valueof(JsonMsg);
        request.httpMethod = 'POST';
        RestContext.request = request;
        RestContext.response= res;
        SAPGetData.doPost();
    }
}