force-app/main/default/objects/Discount__c/Discount__c.object-meta.xml
<CustomObject>
    <label>Margin</label>
    <nameField>
        <displayFormat>Dis-{0000}</displayFormat>
        <label>Margin Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Margins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Discount__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount %</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Discount</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Seraphine Dev Impex Pvt</fullName>
            </value>
            <value>
                <fullName>Eva Traders</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <formula>if( AND(Product_Group__c !=null , text(Product_Group__r.Applicable_For__c) ==&apos;All&apos;,Product_Group__r.Active__c ), 
			 Product_Group__r.Discount__c*100 ,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Fixed_Price_Item__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Price_Item__c</fullName>
    <defaultValue>&apos;N&apos;</defaultValue>
    <label>Fixed Price Item</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
                <default>true</default>
                <label>N</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Return__c/Return__c.object-meta.xml
<CustomObject>
    <label>Return</label>
    <nameField>
        <label>Return Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Returns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Return__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Returns</relationshipLabel>
    <relationshipName>Returns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Return__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Against Invoice</fullName>
            </value>
            <value>
                <fullName>Against Customer</fullName>
            </value>
            <value>
                <fullName>On Account</fullName>
                <isActive>false</isActive>
                <label>On Account</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Return_Item__c/Return_Item__c.object-meta.xml
<CustomObject>
    <label>Return Item</label>
    <nameField>
        <label>Return Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Return Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Return_Item__c/fields/Batch_No__c.field-meta.xml
<CustomField>
    <fullName>Batch_No__c</fullName>
    <label>Batch Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Return_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Return Items</relationshipLabel>
    <relationshipName>Return_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Return_Item__c/fields/Stock__c.field-meta.xml
<CustomField>
    <fullName>Stock__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Returned Damaged Stock</label>
    <referenceTo>Stock__c</referenceTo>
    <relationshipLabel>Return Items</relationshipLabel>
    <relationshipName>Return_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Return_Item__c/fields/Total_after_discount__c.field-meta.xml
<CustomField>
    <fullName>Total_after_discount__c</fullName>
    <formula>IF(Unit_Price__c != UnitPriceWithDiscount__c  , 
				((Total_Unit_Price__c - (Total_Unit_Price__c * Cash_Discount__c))  +
	((Total_Unit_Price__c - (Total_Unit_Price__c * Cash_Discount__c)) * Sales_Tax__c  )
	), Total_Unit_Price__c  +
		(Total_Unit_Price__c  * Sales_Tax__c  ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total after discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Route__c/fields/Branch_Name__c.field-meta.xml
<CustomField>
    <fullName>Branch_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch Name</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Routes</relationshipLabel>
    <relationshipName>Routes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice__c/Sales_Invoice__c.object-meta.xml
<CustomObject>
    <label>Sales Invoice</label>
    <nameField>
        <label>Sales Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Invoice__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Sales Invoices</relationshipLabel>
    <relationshipName>Sales_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice_Item__c/Sales_Invoice_Item__c.object-meta.xml
<CustomObject>
    <label>Sales Invoice Item</label>
    <nameField>
        <displayFormat>ITEM-{0000}</displayFormat>
        <label>Sales Invoice Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Invoice Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Invoice_Item__c/fields/Cash_Discount__c.field-meta.xml
<CustomField>
    <fullName>Cash_Discount__c</fullName>
    <label>Cash Discount (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice_Item__c/fields/Fixed_Price_Item__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Price_Item__c</fullName>
    <formula>IF( ISPICKVAL(Product__r.Fixed_Price_Item__c, &apos;Y&apos;) , true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fixed Price Item</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice_Item__c/fields/Item_Name__c.field-meta.xml
<CustomField>
    <fullName>Item_Name__c</fullName>
    <formula>Stock__r.Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Item Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Sales Invoice Items</relationshipLabel>
    <relationshipName>Sales_Invoice_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice_Item__c/fields/Stock__c.field-meta.xml
<CustomField>
    <fullName>Stock__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stock</label>
    <referenceTo>Stock__c</referenceTo>
    <relationshipLabel>Sales Invoice Items</relationshipLabel>
    <relationshipName>Sales_Invoice_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>Stock-{00000}</displayFormat>
        <label>Stock Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/fields/Available_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Available_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Available Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Blocked_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Blocked_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Blocked Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Branch_Name__c.field-meta.xml
<CustomField>
    <fullName>Branch_Name__c</fullName>
    <formula>Branch__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Branch Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Manufacturing_Date__c.field-meta.xml
<CustomField>
    <fullName>Manufacturing_Date__c</fullName>
    <label>Manufacturing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Product_Batch_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Batch_Name__c</fullName>
    <formula>Product__r.Name + &apos; (&apos; +  Batch_Number__c +&apos;)&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Batch Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Product_Batch_Price__c.field-meta.xml
<CustomField>
    <fullName>Product_Batch_Price__c</fullName>
    <formula>Product__r.Name + &apos; (&apos; + Batch_Number__c +&apos;)&apos;+&apos;- ₹ &apos; + TEXT(Price__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Batch Price</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Product_GST__c.field-meta.xml
<CustomField>
    <fullName>Product_GST__c</fullName>
    <formula>TEXT( Product__r.GST__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product GST</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Product_Old_GST__c.field-meta.xml
<CustomField>
    <fullName>Product_Old_GST__c</fullName>
    <formula>TEXT( Product__r.Old_GST__c  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Old GST</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Sold_Qty__c.field-meta.xml
<CustomField>
    <fullName>Sold_Qty__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sold Qty</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Stock_Type__c.field-meta.xml
<CustomField>
    <fullName>Stock_Type__c</fullName>
    <label>Stock Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Return</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
            </value>
            <value>
                <fullName>Manufacturing Defect</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saleable</fullName>
            </value>
            <value>
                <fullName>Non-Saleable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ReturnUIController.cls
public without sharing class ReturnUIController {
    
    @AuraEnabled
    public Account customer {get;set;}
    @AuraEnabled
    public List<Stock__c> stocks {get;set;}
     @AuraEnabled
    public map<string, List<Stock__c>> productStockMap{get;set;}
    
    @AuraEnabled
    public static ReturnUIController getCustomerStock(String custId){   
        List<Stock__c> stockList = new List<Stock__c>();
        map<string, List<Stock__c>> productStockMap = new   map<string, List<Stock__c>>();
        
        ReturnUIController rc = new ReturnUIController();
        Account acc =[select Id,Name,Cash_Discount__c,Routes__c from Account where Id=:custId];
        rc.customer = acc;
        if(acc.Routes__c ==null){
            throw new AuraHandledException('Please add route in account');
        }else{
            list<string> batchrouteList = new list<string>();
            batchrouteList =  label.batch.split(',');
            Set<String> batches = new Set<String>();
            
            for (Batch__c b : [ SELECT Name  FROM Batch__c  WHERE Active__c = true ]) {  batches.add(b.Name); }
            system.debug(batchrouteList);
            stockList =[SELECT Id,name,Product__c,Product_Name__c,Batch_Number__c,Product_Batch_Price__c,Product_Batch_Name__c,Branch_Name__c,Available_Quantity__c,Sold_Qty__c,
                        Blocked_Quantity__c,Manufacturing_Date__c,Product_Old_GST__c ,Price__c,Product_GST__c,Product__r.Brand__c,Fixed_Price_Item__c,Margin__c from Stock__c where Route__c=:acc.Routes__c and ownerId !='0055g00000DnHO5AAN' and Sold_Qty__c >0  and Stock_Type__c = 'New' and  Batch_Number__c IN : batches order by lastmodifieddate];
        }
        rc.stocks = stockList;
       if (!stockList.isEmpty()) {
           for (Stock__c s : stockList) {
               if (productStockMap.containsKey(s.Product_Batch_Price__c)) {
                   productStockMap.get(s.Product_Batch_Price__c).add(s);
               } else {
                   productStockMap.put(s.Product_Batch_Price__c, new List<Stock__c>{ s });
               }
           }
       }
          rc.productStockMap = productStockMap;
        return rc;
    }
    @AuraEnabled
    public static List<Sales_invoice_Item__c> getInvoiceItems(String invId){
        system.debug(invId);
        system.debug([select Id,Name,Unit_Price__c,Stock__r.Manufacturing_Date__c,Quantity__c,Product__c,Stock__c,Total_after_discount__c,Item_Name__c,Batch_No__c from Sales_Invoice_Item__c where Sales_Invoice__c =:invId]);
        return [select Id,Name,Unit_Price__c,Stock__r.Manufacturing_Date__c,Quantity__c,Product__c,Stock__c,Total_after_discount__c,Item_Name__c,Batch_No__c,GST_Percentage__c,GST_Value__c,Sales_Tax__c,Cash_Discount__c,Customer_Discount__c,Sales_Invoice__r.Customer__c,Sales_Invoice__r.Customer__r.Name,UnitPriceWithDiscount__c,Rate__c,Fixed_Price_Item__c from Sales_Invoice_Item__c where Sales_Invoice__c =:invId];
    }
    
      @AuraEnabled
    public static List<Discount__c> getDiscounts(string custId){
        List<Discount__c> disList = new  List<Discount__c>();        
        disList = [SELECT Id,Name,GST_Percentage__c,Discount_Percent__c,Eva_Discount_Percent__c  from  Discount__c   where Customer__c=:custId ];        
        system.debug('disList--'+disList.size());
        return disList;
    }
    @AuraEnabled
    public static String saveNewReturn(string returnId,string routeId, List<Return_Item__c> items ){
        
        Return__c returnrec =[select Id,Name,Sales_Invoice__c,Type__c from Return__c where Id=:returnId];
        List<Return_Item__c> itemsToInsert = new List<Return_Item__c>();
        for(Return_Item__c ri: items){
            if(ri.Quantity__c != 0){
                Return_Item__c ritem = new Return_Item__c();
                ritem = ri;
                if(returnrec.Type__c == 'Against Invoice') ritem.Sales_Invoice__c = returnrec.Sales_Invoice__c;
                ritem.Return__c = returnrec.Id;
                ritem.Damaged_Stock__c =  ri.Stock__c;
                ritem.Stock__c = null;
                itemsToInsert.add(ritem);
            }  
        }
         
        try {
            insert itemsToInsert;
           // insert stocklist;
        }
        catch (System.Exception ae) { 
            ExceptionHandler.addLog(ae,String.valueOf(itemsToInsert)  ); 
        }  
        
         return returnrec.Id;

    }
        public static void testcover(){
        integer i=0; 
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0; 
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0; 
        
    }
}