force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/Cash_In_Hand__c.field-meta.xml
<CustomField>
    <fullName>Cash_In_Hand__c</fullName>
    <label>Cash In Hand</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Cash_Transfer__c/Cash_Transfer__c.object-meta.xml
<CustomObject>
    <label>Cash Transfer</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Cash Transfer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cash Transfers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cash_Transfer__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Cash Transfers</relationshipLabel>
    <relationshipName>Cash_Transfers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cash_Transfer__c/fields/From__c.field-meta.xml
<CustomField>
    <fullName>From__c</fullName>
    <label>From</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Branch</fullName>
            </value>
            <value>
                <fullName>Route</fullName>
            </value>
            <value>
                <fullName>Head Office</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cash_Transfer__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Cash Transfers</relationshipLabel>
    <relationshipName>Cash_Transfers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cash_Transfer__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credited</fullName>
            </value>
            <value>
                <fullName>Debited</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cash_Transfer__c/fields/To__c.field-meta.xml
<CustomField>
    <fullName>To__c</fullName>
    <label>To</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Branch</fullName>
            </value>
            <value>
                <fullName>Route</fullName>
            </value>
            <value>
                <fullName>Head Office</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cash_Transfer__c/fields/Trip__c.field-meta.xml
<CustomField>
    <fullName>Trip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trip</label>
    <referenceTo>Trip__c</referenceTo>
    <relationshipLabel>Cash Transfers</relationshipLabel>
    <relationshipName>Cash_Transfers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Route__c/fields/Branch_Name__c.field-meta.xml
<CustomField>
    <fullName>Branch_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch Name</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Routes</relationshipLabel>
    <relationshipName>Routes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/Trip__c.object-meta.xml
<CustomObject>
    <label>Trip</label>
    <nameField>
        <displayFormat>TRIP-{0000}</displayFormat>
        <label>Trip Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipName>Trips</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Ended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ClearBalController.cls
public class ClearBalController {
    
    @AuraEnabled
    public static Decimal checkBalance(Id recId){
        String sobjectType = recId.getSObjectType().getDescribe().getName();
        
        if(sobjectType == 'Route__c'){
            Route__c rt = [select id,Name,Branch_Name__c,Cash_In_Hand__c,Last_Cleared_Date__c from Route__c where id=:recId];
            return rt.Cash_In_Hand__c;
        }
        
        if(sobjectType == 'Trip__c'){
            Trip__c trp = [select id,Name,Route__c,Route__r.Branch_Name__c,Cash_In_Hand__c,Last_Cleared_Date__c from Trip__c where id=:recId];
            return trp.Cash_In_Hand__c;
        }
        return null;
    }
    @AuraEnabled
    public static void clearBalance(Id recId){
        String sobjectType = recId.getSObjectType().getDescribe().getName();
        
        if(sobjectType == 'Route__c'){
            Route__c rt = [select id,Name,Branch_Name__c,Branch_Name__r.Cash_In_Hand__c,Cash_In_Hand__c,Last_Cleared_Date__c from Route__c where id=:recId];
            
            Cash_Transfer__c ct = new Cash_Transfer__c();
            ct.From__c = 'Route';
            ct.To__c = 'Branch';
            ct.Route__c = recId;
            ct.Branch__c = rt.Branch_Name__c;
            ct.Amount__c = rt.Cash_In_Hand__c;
            
            
            try {
                insert ct;
            }
            catch (System.Exception ae) { 
                ExceptionHandler.addLog(ae,String.valueOf(ct)  );  
            }     
            
            rt.Cash_In_Hand__c = 0;
            rt.Last_Cleared_Date__c = system.today();
            
            try {
                update rt;
            }
            catch (System.Exception ae) { 
                ExceptionHandler.addLog(ae,String.valueOf(rt)  );  
            }     
            
            Branch__c br = new Branch__c();
            br.Id = rt.Branch_Name__c;
            if(rt.Branch_Name__r.Cash_In_Hand__c == null || rt.Branch_Name__r.Cash_In_Hand__c == 0){
                br.Cash_In_Hand__c = ct.Amount__c;
            }
            else{
                br.Cash_In_Hand__c = rt.Branch_Name__r.Cash_In_Hand__c + ct.Amount__c;
            }
            
            try {
                update br;
            }
            catch (System.Exception ae) { 
                ExceptionHandler.addLog(ae,String.valueOf(br)  );  
            }     
            
            Trip__c trp = [SELECT id,Route__c,Cash_In_Hand__c,Last_Cleared_Date__c from  Trip__c  WHERE   (Status__c = 'Started' AND End_Date__c = null )  AND Route__c =:recId limit 1]; 
            trp.Cash_In_Hand__c = 0;
            trp.Last_Cleared_Date__c = system.today();
            
            try {
                update trp;
            }
            catch (System.Exception ae) { 
                ExceptionHandler.addLog(ae,String.valueOf(trp)  );   
            }     
            
        }
        
        if(sobjectType == 'Trip__c'){
            Trip__c trp = [select id,Name,Route__c,Route__r.Branch_Name__c,Route__r.Branch_Name__r.Cash_In_Hand__c,Cash_In_Hand__c,Last_Cleared_Date__c from Trip__c where id=:recId];
            
            Cash_Transfer__c ct = new Cash_Transfer__c();
            ct.From__c = 'Route';
            ct.To__c = 'Branch';
            ct.Route__c = trp.Route__c;
            ct.Branch__c = trp.Route__r.Branch_Name__c;
            ct.Amount__c = trp.Cash_In_Hand__c;
            
            
            try {
                insert ct;
            }
            catch (System.Exception ae) { 
                ExceptionHandler.addLog(ae,String.valueOf(ct)  );  
            }     
            
            trp.Cash_In_Hand__c = 0;
            trp.Last_Cleared_Date__c = system.today();
            
            try {
                update trp;
            }
            catch (System.Exception ae) { 
                ExceptionHandler.addLog(ae,String.valueOf(trp)  );  
            }     
            
            Branch__c br = new Branch__c();
            br.Id = trp.Route__r.Branch_Name__c;
            if(trp.Route__r.Branch_Name__r.Cash_In_Hand__c == null || trp.Route__r.Branch_Name__r.Cash_In_Hand__c == 0){
                br.Cash_In_Hand__c = ct.Amount__c;
            }
            else{
                br.Cash_In_Hand__c = trp.Route__r.Branch_Name__r.Cash_In_Hand__c + ct.Amount__c;
            }
            
            try {
                update br;
            }
            catch (System.Exception ae) { 
                ExceptionHandler.addLog(ae,String.valueOf(br)  );   
            }     
            
            Route__c rt = new Route__c();
            rt.Id = trp.Route__c;
            rt.Cash_In_Hand__c = 0;
            rt.Last_Cleared_Date__c = system.today();
            
            try {
                update rt;
            }
            catch (System.Exception ae) { 
                ExceptionHandler.addLog(ae,String.valueOf(rt)  );  
            }  
            
        }
        
    }
}