force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cashbook__c/Cashbook__c.object-meta.xml
<CustomObject>
    <label>Cashbook</label>
    <nameField>
        <displayFormat>CB-{0000}</displayFormat>
        <label>Cashbook Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cashbooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cashbook__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Cashbooks</relationshipLabel>
    <relationshipName>Cashbooks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cashbook__c/fields/Closing_Balance__c.field-meta.xml
<CustomField>
    <fullName>Closing_Balance__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Closing Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Cashbook__c/fields/Opening_Balance__c.field-meta.xml
<CustomField>
    <fullName>Opening_Balance__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Opening Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Cashbook__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Cashbooks</relationshipLabel>
    <relationshipName>Cashbooks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <displayFormat>EP-{00000}</displayFormat>
        <label>Expense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <formula>IF(ISPICKVAL(Select_Expense_Entry__c, &apos;General&apos;)  || Text(Select_Expense_Entry__c)==Null, TA__c  +  DA__c +  Food_Expense__c +  Fuel_Expense__c  +  Vehicle_Repair_Expense__c  +  Accommodation_Expense__c +  Other_Expenses__c, Amount__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>REC-{0000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/Approval_status__c.field-meta.xml
<CustomField>
    <fullName>Approval_status__c</fullName>
    <defaultValue>&apos;New&apos;</defaultValue>
    <label>Approval status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted for approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipName>Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Cheque_Trasaction_Number__c.field-meta.xml
<CustomField>
    <fullName>Cheque_Trasaction_Number__c</fullName>
    <label>Cheque/Trasaction Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Approval_Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Mode_of_payment__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_payment__c</fullName>
    <label>Mode of payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>UPI</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Bank Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Receipt_Status__c.field-meta.xml
<CustomField>
    <fullName>Receipt_Status__c</fullName>
    <defaultValue>&apos;Generated&apos;</defaultValue>
    <label>Receipt Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Generated</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipName>Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Sales_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Invoice</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (2 AND 3)</booleanFilter>
        <filterItems>
            <field>Sales_Invoice__c.Pending_Amount__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <filterItems>
            <field>Sales_Invoice__c.Customer__c</field>
            <operation>equals</operation>
            <valueField>$Source.Customer__c</valueField>
        </filterItems>
        <filterItems>
            <field>Sales_Invoice__c.Pending_Amount_SAP__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Sales_Invoice__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Invoice__c/Sales_Invoice__c.object-meta.xml
<CustomObject>
    <label>Sales Invoice</label>
    <nameField>
        <label>Sales Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Invoice__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Sales Invoices</relationshipLabel>
    <relationshipName>Sales_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Invoices</relationshipLabel>
    <relationshipName>Sales_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice__c/fields/Grand_Total_Discounted__c.field-meta.xml
<CustomField>
    <fullName>Grand_Total_Discounted__c</fullName>
    <formula>IF( New_Flow__c == true,
			Grand_Total__c,
			IF(TEXT(Payment_Type__c)==&apos;Credit&apos;,
						Grand_Total__c ,  
						IF(Grand_Total_after_discount__c != 0.0 , 
									Grand_Total_after_discount__c - (Grand_Total_after_discount__c *  Customer__r.Cash_Discount__c), 
									Grand_Total__c - (Grand_Total__c *  Customer__r.Cash_Discount__c) 
								)
					)
			)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Grand Total (Discounted)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <displayFormat>{0000}</displayFormat>
    <label>Invoice Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice__c/fields/Invoice_Total__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Total__c</fullName>
    <formula>ROUND(Grand_Total_Discounted__c,0 )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Sales Invoices</relationshipLabel>
    <relationshipName>Sales_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <formula>TEXT(Customer__r.State__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>State</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CollectionSheetController.cls
public class CollectionSheetController {
   
    public Decimal ClosingBalance{get;set;}
    public Decimal TotalSalesAmount{get;set;}
    public Decimal totalCashCollection{get;set;}
    public Decimal totalChequeCollection{get;set;}
    public Decimal totalExpense{get;set;}
    public list<wrapper>salesInvoices{get;set;}
    
      public CollectionSheetController(){
        Id recordId = ApexPages.currentPage().getParameters().get('Id'); 
        String fromDate = ApexPages.currentPage().getParameters().get('from'); 
        String toDate = ApexPages.currentPage().getParameters().get('to'); 
        
        Date fromdate1 = date.valueof(fromDate);
        Date todate1 = date.valueof(toDate);
        
        String sobjectType = recordId.getSObjectType().getDescribe().getName(); 
        system.debug('sobjectType:' + sobjectType);
        
        system.debug('id:' + recordId);
        system.debug('fromDate:' + fromdate1);
        system.debug('toDate:' + todate1);
        
        Date fromdate2 = date.valueof(fromDate).addDays(-1);
        Date todate2 = date.valueof(toDate).addDays(-1);
        
        ClosingBalance=0;
        totalCashCollection = 0;
        totalChequeCollection = 0;
        TotalSalesAmount = 0;
        totalExpense = 0;
        salesInvoices = new list<wrapper>();

        if(sobjectType == 'Route__c'){
             List<Cashbook__c> cbList = [select Id,Name,Date__c,Branch__c,Opening_Balance__c,Closing_Balance__c,CreatedDate from Cashbook__c where Route__c = :recordId and (Date__c=:fromDate1  or Date__c=:toDate1) ];
            if(cbList.size() > 0){
                for(Cashbook__c cb: cbList){
                    if(cb.Date__c == toDate1){
                        ClosingBalance = cb.Closing_Balance__c;
                    }
                }
            }
            List<Sales_Invoice__c> salesInvoiceList = [select id,Name,CreatedDate,Customer__r.Name,Route__c, Customer__r.State__c,Invoice_Number__c,Grand_Total_Discounted__c,Invoice_Total__c,Invoice_Date__c,Customer__r.Phone,
                                                (Select Id,Cheque_Trasaction_Number__c,Mode_of_payment__c,Amount__c From Collections__r where Receipt_Status__c != 'Cancelled' AND ((New_Approval_Flow__c =true AND Approval_status__c='Approved') OR (Approval_status__c=null AND New_Approval_Flow__c=false))) from Sales_Invoice__c 
                                                where Route__c =: recordId AND (Invoice_Date__c >=:fromDate1  and Invoice_Date__c <=:toDate1) AND Invoice_Total__c !=0 order by Invoice_Date__c];
            system.debug('salesInvoiceList=== '+salesInvoiceList);
            for(Sales_Invoice__c salesInvoice : salesInvoiceList){
               /* wrapper wrp = new wrapper();
                wrp.PartyName = salesInvoice.Customer__r.Name;
                wrp.Place = salesInvoice.Customer__r.State__c;
                wrp.InvoiceNo = salesInvoice.Name;
                wrp.SaleAmount = salesInvoice.Grand_Total_Discounted__c;
                TotalSalesAmount =TotalSalesAmount + salesInvoice.Grand_Total_Discounted__c;
                wrp.invDate = salesInvoice.Invoice_Date__c;*/
                
                if(salesInvoice.Collections__r.size()>0){
                    
                    for(Receipt__c rec:salesInvoice.Collections__r){
                        wrapper wrp = new wrapper();
                        wrp.PartyName = salesInvoice.Customer__r.Name;
                        wrp.Place = salesInvoice.Customer__r.State__c;
                        wrp.InvoiceNo = salesInvoice.Name;
                        wrp.SaleAmount = salesInvoice.Invoice_Total__c;
                        TotalSalesAmount =TotalSalesAmount + salesInvoice.Invoice_Total__c;
                        wrp.invDate = salesInvoice.Invoice_Date__c;
                        
                        if(rec.Mode_of_payment__c == 'Cheque'){
                            wrp.CheckNo = rec.Cheque_Trasaction_Number__c;
                            wrp.ChequeAmount = rec.Amount__c;
                            totalChequeCollection = totalChequeCollection + rec.Amount__c;
                        }
                        else{
                            wrp.CashAmount = rec.Amount__c;
                            totalCashCollection = totalCashCollection + rec.Amount__c;
                        }
                        wrp.Phone = salesInvoice.Customer__r.Phone;
                        
                        salesInvoices.add(wrp);
                    }
                    
                   
                    
                   /* if(salesInvoice.Collections__r[0].Mode_of_payment__c == 'Cheque'){
                        wrp.ChequeAmount = salesInvoice.Grand_Total_Discounted__c;
                        totalChequeCollection = totalChequeCollection + salesInvoice.Grand_Total_Discounted__c;
                    }else{
                       // wrp.ChequeAmount = 0.00;
                    }*/
                    
                  /*  if(salesInvoice.Collections__r[0].Mode_of_payment__c == 'Cash'){
                        wrp.CashAmount = salesInvoice.Grand_Total_Discounted__c;
                        totalCashCollection = totalCashCollection + salesInvoice.Grand_Total_Discounted__c;
                    }else{
                      //  wrp.CashAmount = 0.00;
                    }*/
                }else{
                    
                    wrapper wrp = new wrapper();
                    wrp.PartyName = salesInvoice.Customer__r.Name;
                    wrp.Place = salesInvoice.Customer__r.State__c;
                    wrp.InvoiceNo = salesInvoice.Name;
                    wrp.SaleAmount = salesInvoice.Invoice_Total__c;
                    TotalSalesAmount =TotalSalesAmount + salesInvoice.Invoice_Total__c;
                    wrp.invDate = salesInvoice.Invoice_Date__c;
                    wrp.Phone = salesInvoice.Customer__r.Phone;
                    
                    salesInvoices.add(wrp);
                  //  wrp.CheckNo = null;
                  //  wrp.ChequeAmount = 0.00;
                   // wrp.CashAmount = 0.00;
                   
                }
                
                
                
            }
            
            List<Expense__c> expenseList = [Select Id,Total_Amount__c from Expense__c
                                            where Route__c =: recordId AND (CreatedDate >=:fromDate1  and CreatedDate <=:toDate1) order by CreatedDate];
            
            system.debug('expenseList=== '+expenseList);
            if(expenseList.size()>0){
                for(Expense__c exp : expenseList){
                    totalExpense = totalExpense + exp.Total_Amount__c;
                }
            }
            
        }
        
    }
    
    public class wrapper{
        public String PartyName{get;set;}
        public String Place{get;set;}
        public String InvoiceNo{get;set;}
        public Decimal SaleAmount{get;set;}
        public Decimal CheckNo{get;set;}
        public Date invDate{get;set;}
        public Decimal ChequeAmount{get;set;}
        public Decimal CashAmount{set;get;}
        public string Phone{get;set;}
    }
}