force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>Stock-{00000}</displayFormat>
        <label>Stock Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Stock_Date__c.field-meta.xml
<CustomField>
    <fullName>Stock_Date__c</fullName>
    <label>Stock Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ProductBranchLatestPriceControllerTest.cls
@IsTest
public class ProductBranchLatestPriceControllerTest {
    @testSetup
    static void setupData(){
        product2 Prod= new Product2(
        Name = 'Test Product',
        IsActive = true
        );
        insert prod;
        
        Branch__c branch1= new Branch__c(Name= 'Branch A');
        Branch__c branch2 = new Branch__c(Name= 'Branch B');
        insert new List<Branch__c>{ branch1, branch2};
            
            Stock__c stockA1 = new Stock__c(
            Product__c = prod.Id,
            Branch__c = branch1.Id,
            Price__c = 100,
            Stock_Date__c=Date.today().addDays(-5)
            );
        Stock__c stockA2 = new Stock__c(
        Product__c = prod.Id,
        //Branch_c = branch1.Id,
        Price__c = 150,
        Stock_Date__c = Date.today());
        
       Stock__c stockB1 = new Stock__c(
       Product__c = prod.Id,
       Branch__c = branch2.Id,
       Price__c = 200,
       Stock_Date__c = Date.today().addDays(-10)
       );
        
        Stock__c stockB2 = new Stock__c(
       Product__c = prod.Id,
       Branch__c = branch2.Id,
       Price__c= 250,
       Stock_date__c= Date.today().addDays(-1));
        insert new List<stock__c>{ stockA1, stockA2, stockB1, stockB2};
            }
            
        
        @IsTest
        static void testGetLatestBranchPrice(){
            Product2 prod = [SELECT Id FROM Product2 LIMIT 1];
            Test.startTest();
            List<ProductBranchLatestPriceController.BranchPriceWrapper> result= productBranchLatestPriceController.getLatestBranchPrice(prod.Id);
            Test.stopTest();
            
            system.assertEquals(2, result.size(), 'Should return latest price per branch');
            
            Map<String, Decimal> branchPriceMap = new Map<String, Decimal>();
            for ( ProductBranchLatestPriceController.BranchPriceWrapper bp : result){
                branchPriceMap.put(bp.branchName, bp.price);
                
            }
            system.assertEquals(150, branchPriceMap.get('Branch A'),
                               'Branch A should return latest price');
            
            system.assertEquals(250, branchPriceMap.get('Branch B'),
                               'Branch B should retun latest price');
        }
    
     
        
        
    }