force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/Cash_In_Hand__c.field-meta.xml
<CustomField>
    <fullName>Cash_In_Hand__c</fullName>
    <label>Cash In Hand</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Branch__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Branches</relationshipLabel>
    <relationshipName>Branches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cash_Transfer__c/Cash_Transfer__c.object-meta.xml
<CustomObject>
    <label>Cash Transfer</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Cash Transfer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cash Transfers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cash_Transfer__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Cash Transfers</relationshipLabel>
    <relationshipName>Cash_Transfers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cash_Transfer__c/fields/From__c.field-meta.xml
<CustomField>
    <fullName>From__c</fullName>
    <label>From</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Branch</fullName>
            </value>
            <value>
                <fullName>Route</fullName>
            </value>
            <value>
                <fullName>Head Office</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cash_Transfer__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Cash Transfers</relationshipLabel>
    <relationshipName>Cash_Transfers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cash_Transfer__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credited</fullName>
            </value>
            <value>
                <fullName>Debited</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cash_Transfer__c/fields/To__c.field-meta.xml
<CustomField>
    <fullName>To__c</fullName>
    <label>To</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Branch</fullName>
            </value>
            <value>
                <fullName>Route</fullName>
            </value>
            <value>
                <fullName>Head Office</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cash_Transfer__c/fields/Trip__c.field-meta.xml
<CustomField>
    <fullName>Trip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trip</label>
    <referenceTo>Trip__c</referenceTo>
    <relationshipLabel>Cash Transfers</relationshipLabel>
    <relationshipName>Cash_Transfers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Route__c/fields/Branch_Name__c.field-meta.xml
<CustomField>
    <fullName>Branch_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch Name</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Routes</relationshipLabel>
    <relationshipName>Routes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Routes</relationshipLabel>
    <relationshipName>Routes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/Trip__c.object-meta.xml
<CustomObject>
    <label>Trip</label>
    <nameField>
        <displayFormat>TRIP-{0000}</displayFormat>
        <label>Trip Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipName>Trips</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Ended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/ClearBalControllerTest.cls
@isTest
public class ClearBalControllerTest {
    @isTest
    public static void testClearBalController(){
        Warehouse__c wh = new Warehouse__c();
        wh.name = 'test';
        insert wh;
        Branch__c br = new Branch__c();
        br.Name = 'BR1';
        br.Cash_In_Hand__c = 100000;
        insert br;
        List<Route__c> rut = new List<Route__c>();
        Route__c r = new Route__c();
        r.warehouse__c = wh.id;
        r.Name = 'test route';
        r.Branch_Name__c = br.Id;
        rut.add(r);
        insert rut;
        List<Trip__c> tri = new List<Trip__c>();
        Trip__c tr = new Trip__c();
        tr.Route__c = r.id;
        tr.Status__c = 'Started';
        tr.End_Date__c = null;
        tri.add(tr);
        insert tr;
        
        String sobjectType = 'Trip__c';
        Trip__c tr1 = new Trip__c();
        tr1.Route__c = r.id;
      
        insert tr1;
        
        Trip__c trp = [select id,Name,Route__c,Route__r.Branch_Name__c,Cash_In_Hand__c,Last_Cleared_Date__c from Trip__c where id=:tr1.id];
        system.debug(trp+'dhebchdbchdbcgvcgdfvc');
        
        
            Cash_Transfer__c ct1 = new Cash_Transfer__c();
            ct1.From__c = 'Route';
            ct1.To__c = 'Branch';
            ct1.Route__c = trp.Route__c;
            ct1.Branch__c = trp.Route__r.Branch_Name__c;
            ct1.Amount__c = 566;
            
            insert ct1;
            
            trp.Cash_In_Hand__c = 0;
            trp.Last_Cleared_Date__c = system.today();
            update trp;
            
            Route__c rt4 = new Route__c();
            rt4.Id = trp.Route__c;
            rt4.Cash_In_Hand__c = 0;
            rt4.Last_Cleared_Date__c = system.today();
            update rt4;
            
        
        
        Cash_Transfer__c ct = new Cash_Transfer__c();
            ct.From__c = 'Route';
            ct.To__c = 'Branch';
            ct.Route__c = r.id;
            
            ct.Amount__c = 100;
            
            insert ct;
        ClearBalController.checkBalance(r.id);
        ClearBalController.checkBalance(tr.id);
        
        ClearBalController.clearBalance(r.id);
        ClearBalController.clearBalance(tr.id);
    }

}