force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cash_Transfer__c/Cash_Transfer__c.object-meta.xml
<CustomObject>
    <label>Cash Transfer</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Cash Transfer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cash Transfers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cash_Transfer__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Cash Transfers</relationshipLabel>
    <relationshipName>Cash_Transfers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cash_Transfer__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Cash Transfers</relationshipLabel>
    <relationshipName>Cash_Transfers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cashbook__c/Cashbook__c.object-meta.xml
<CustomObject>
    <label>Cashbook</label>
    <nameField>
        <displayFormat>CB-{0000}</displayFormat>
        <label>Cashbook Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cashbooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cashbook__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Cashbooks</relationshipLabel>
    <relationshipName>Cashbooks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cashbook__c/fields/Closing_Balance__c.field-meta.xml
<CustomField>
    <fullName>Closing_Balance__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Closing Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Cashbook__c/fields/Opening_Balance__c.field-meta.xml
<CustomField>
    <fullName>Opening_Balance__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Opening Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Cashbook__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Cashbooks</relationshipLabel>
    <relationshipName>Cashbooks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DailyLog__c/DailyLog__c.object-meta.xml
<CustomObject>
    <label>Daily Log</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Log Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/DailyLog__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Driver</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Daily Logs (Driver)</relationshipLabel>
    <relationshipName>Daily_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DailyLog__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Daily Logs</relationshipLabel>
    <relationshipName>Daily_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DailyLog__c/fields/Sales_Man__c.field-meta.xml
<CustomField>
    <fullName>Sales_Man__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Man</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Daily Logs (Sales Man)</relationshipLabel>
    <relationshipName>Daily_Logs1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <displayFormat>EP-{00000}</displayFormat>
        <label>Expense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <formula>IF(ISPICKVAL(Select_Expense_Entry__c, &apos;General&apos;)  || Text(Select_Expense_Entry__c)==Null, TA__c  +  DA__c +  Food_Expense__c +  Fuel_Expense__c  +  Vehicle_Repair_Expense__c  +  Accommodation_Expense__c +  Other_Expenses__c, Amount__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>REC-{0000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/Approval_status__c.field-meta.xml
<CustomField>
    <fullName>Approval_status__c</fullName>
    <defaultValue>&apos;New&apos;</defaultValue>
    <label>Approval status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted for approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipName>Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Mode_of_payment__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_payment__c</fullName>
    <label>Mode of payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>UPI</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Bank Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Receipt_Status__c.field-meta.xml
<CustomField>
    <fullName>Receipt_Status__c</fullName>
    <defaultValue>&apos;Generated&apos;</defaultValue>
    <label>Receipt Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Generated</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipName>Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Sales_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Invoice</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (2 AND 3)</booleanFilter>
        <filterItems>
            <field>Sales_Invoice__c.Pending_Amount__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <filterItems>
            <field>Sales_Invoice__c.Customer__c</field>
            <operation>equals</operation>
            <valueField>$Source.Customer__c</valueField>
        </filterItems>
        <filterItems>
            <field>Sales_Invoice__c.Pending_Amount_SAP__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Sales_Invoice__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Invoice__c/Sales_Invoice__c.object-meta.xml
<CustomObject>
    <label>Sales Invoice</label>
    <nameField>
        <label>Sales Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Invoice__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Sales Invoices</relationshipLabel>
    <relationshipName>Sales_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice__c/fields/Invoice_Total__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Total__c</fullName>
    <formula>ROUND(Grand_Total_Discounted__c,0 )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Sales Invoices</relationshipLabel>
    <relationshipName>Sales_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ExpenseSheetController.cls
public class ExpenseSheetController {
    
    
    public list<wrapper> wraplist{get;set;}
    
    
    public ExpenseSheetController(){
        Id recordId = ApexPages.currentPage().getParameters().get('Id'); 
        String fromDate = ApexPages.currentPage().getParameters().get('from'); 
        String toDate = ApexPages.currentPage().getParameters().get('to'); 
        
        Date fromdate1 = date.valueof(fromDate);
        Date todate1 = date.valueof(toDate);
        
        String sobjectType = recordId.getSObjectType().getDescribe().getName(); 
        system.debug('sobjectType:' + sobjectType);
        
        system.debug('id:' + recordId);
        system.debug('fromDate:' + fromdate1);
        system.debug('toDate:' + todate1);
        
        Date fromdate2 = date.valueof(fromDate).addDays(-1);
        Date todate2 = date.valueof(toDate).addDays(-1);
        
        Date incDate = fromdate1;
        wraplist = new list<wrapper>();
        
        List<Cashbook__c> cblist = [select Id,Name,Branch__c,Opening_Balance__c,Closing_Balance__c,CreatedDate,Date__c from Cashbook__c where Route__c = :recordId and (Date__c >=:incDate and Date__c <=:toDate1  ) ];
        Map<Date,Cashbook__c> cbMap = new Map<Date,Cashbook__c>();
        
        for(Cashbook__c cb: cblist){
            cbMap.put(cb.Date__c,cb);
        }
         List<Cash_Transfer__c> cflist = [select Id,Name,Branch__c,Branch__r.Name,Amount__c,CreatedDate,Date__c from Cash_Transfer__c where Route__c = :recordId and (Date__c >=:incDate and Date__c <=:toDate1  ) ];
        Map<Date,Cash_Transfer__c> cfMap = new Map<Date,Cash_Transfer__c>();
        
        for(Cash_Transfer__c cf: cflist){
            cfMap.put(cf.Date__c,cf);
        }
        system.debug('cfMap'+cfMap);
        List<AggregateResult> resinvlist = [select Route__c,DAY_ONLY(createdDate)dt,sum(Invoice_Total__c)amt from Sales_Invoice__c where Route__c = :recordId and  (DAY_ONLY(createdDate)>=:incDate and DAY_ONLY(createdDate)<=:toDate1 ) group by Route__c,DAY_ONLY(createdDate) ];  
        Map<Date,Decimal> aggMapInv = new Map<Date,Decimal>();
        for(AggregateResult res: resinvlist){
            aggMapInv.put(Date.valueof(res.get('dt')), (Decimal)res.get('amt'));
        }
        
        List<AggregateResult> resReclist = [select Route__c,DAY_ONLY(createdDate)dt,sum(Amount__c)amt from Receipt__c where Route__c = :recordId and  Mode_of_Payment__c = 'Cash' and  Receipt_Status__c != 'Cancelled' and (DAY_ONLY(createdDate)>=:incDate and DAY_ONLY(createdDate)<=:toDate1 ) group by Route__c,DAY_ONLY(createdDate) ];  
        Map<Date,Decimal> aggMapRec = new Map<Date,Decimal>();
        for(AggregateResult res: resReclist){
            aggMapRec.put(Date.valueof(res.get('dt')), (Decimal)res.get('amt'));
        }
        
        List<AggregateResult> resExp = [select Route__c,DAY_ONLY(createdDate)dt,sum(Total_Amount__c)amt from Expense__c where Route__c = :recordId and  (DAY_ONLY(createdDate)>=:incDate and DAY_ONLY(createdDate)<=:toDate1 ) and Approval_Status__c = 'Approved'  group by Route__c,DAY_ONLY(createdDate)];   
        Map<Date,Decimal> aggMapExp = new Map<Date,Decimal>();
        for(AggregateResult res: resExp){
            aggMapExp.put(Date.valueof(res.get('dt')), (Decimal)res.get('amt'));
        }
        
       //  List<Expense__c> expList = [select Route__c,DAY_ONLY(createdDate)dt,Total_Amount__c from Expense__c where Route__c = :recordId and  (DAY_ONLY(createdDate)>=:incDate and DAY_ONLY(createdDate)<=:toDate1 ) and Approval_Status__c = 'Approved' ];   
       // Map<Date,List<Expense__c>> expMap = new Map<Date,List<Expense__c>>();
        
        
        List<Dailylog__c> dllist = [select Id,Route__c,Driver__c,Sales_Man__r.Name,CreatedDate from Dailylog__c where Route__c = :recordId and (DAY_ONLY(createdDate)>=:incDate and DAY_ONLY(createdDate)<=:toDate1 ) ];
        Map<Date,Dailylog__c> dlMap = new Map<Date,Dailylog__c>();
        
        for(Dailylog__c dl: dllist){
            dlMap.put(Date.valueof(dl.CreatedDate),dl);
        }
        
        
        while(incDate != todate1.addDays(1)){
            wrapper w = new wrapper();
            w.OpeningBalance = 0;
            w.ClosingBalance = 0;
            w.saleAmount = 0;
            w.Amount = 0;
            w.totalAmount = 0;
            w.totalExp = 0;
            
            if(cbMap.size() > 0 && cbMap.containsKey(incDate)){
                w.OpeningBalance = cbMap.get(incDate).Opening_Balance__c;
                w.ClosingBalance = cbMap.get(incDate).Closing_Balance__c;
            }
            
            
            // List<AggregateResult> resRec = [select Route__c,sum(Amount__c)amt from Receipt__c where Route__c = :recordId and  Mode_of_Payment__c = 'Cash' and  DAY_ONLY(createdDate)=:incDate group by Route__c limit 1];   
            
            if(aggMapInv.size() > 0 && aggMapInv.containsKey(incDate)){
                w.saleAmount = aggMapInv.get(incDate);
            }
            
            if(aggMapRec.size() > 0 && aggMapRec.containsKey(incDate)){
                w.Amount = aggMapRec.get(incDate);
            }
            
            w.totalAmount = w.OpeningBalance + w.Amount;
            
            // List<AggregateResult> resExp = [select Route__c,sum(Total_Amount__c)amt from Expense__c where Route__c = :recordId and  DAY_ONLY(createdDate)=:incDate and Approval_Status__c = 'Approved'  group by Route__c limit 1];   
            /* if(resExp.size() > 0){
w.totalExp = (Decimal)resExp[0].get('amt');
//w.Particulars = String.valueof(resExp.get('Expense_Comments__c'));
w.Particulars = 'ex';
}*/
            if(aggMapExp.size() > 0 && aggMapExp.containsKey(incDate)){
                w.totalExp = aggMapExp.get(incDate);
                w.Particulars = 'Total Expenses on ' + incDate.format();
            }
            
            //List<Dailylog__c> dl = [select Id,Route__c,Driver__c,Sales_Man__r.Name from Dailylog__c where Route__c = :recordId and  DAY_ONLY(createdDate)=:incDate limit 1];
            if(dlMap.size() > 0 && dlMap.containsKey(incDate)){
                w.SalesMan = dlMap.get(incDate).Sales_Man__r.Name;
            }
            w.transDate = incDate;
            wraplist.add(w);
           // to branch
            if(cfMap.size() > 0 && cfMap.containsKey(incDate)){
                if(cfMap.get(incDate).Branch__c != null){
                 wrapper w1 = new wrapper();
            w1.OpeningBalance = 0;
            w1.ClosingBalance = 0;
            w1.saleAmount = 0;
            w1.Amount = cfMap.get(incDate).Amount__c;
            w1.totalAmount = 0;
            w1.totalExp = 0;
            w1.Tobranch =cfMap.get(incDate).Branch__r.Name;
            w1.transDate = incDate;
            wraplist.add(w1);
            }
            }   
            
            
           //end 
            
            
            
            incDate = incDate.addDays(1);
            
        }
        
        wraplist.sort();
        //this.wraplist = wraplist;
        system.debug('wraplist:' + wraplist);
        
        
    }
    public class wrapper implements Comparable{
        
        public Date transDate{get;set;}
        public Decimal saleAmount{get;set;}
        public Decimal OpeningBalance{get;set;}
        public String Particulars{get;set;}
        public String SalesMan{get;set;}
        public Decimal Amount{get;set;}
        public Decimal totalAmount{get;set;}
        public Decimal totalExp{get;set;}
        public Decimal ClosingBalance{get;set;}
          public String Tobranch{get;set;}
        
        
        public  Integer compareTo(Object anotherObject){
            wrapper wso2=(wrapper) anotherObject;
            if(transDate>wso2.transDate){
                return 1;
            }else if(transDate<wso2.transDate){
                return -1;
            }
            return 0;
        }
    }
}