force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cashbook__c/Cashbook__c.object-meta.xml
<CustomObject>
    <label>Cashbook</label>
    <nameField>
        <displayFormat>CB-{0000}</displayFormat>
        <label>Cashbook Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cashbooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cashbook__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Cashbooks</relationshipLabel>
    <relationshipName>Cashbooks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cashbook__c/fields/Closing_Balance__c.field-meta.xml
<CustomField>
    <fullName>Closing_Balance__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Closing Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Cashbook__c/fields/Opening_Balance__c.field-meta.xml
<CustomField>
    <fullName>Opening_Balance__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Opening Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Cashbook__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Cashbooks</relationshipLabel>
    <relationshipName>Cashbooks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Route__c/fields/Route_Id__c.field-meta.xml
<CustomField>
    <fullName>Route_Id__c</fullName>
    <externalId>true</externalId>
    <label>Route Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/UpdateRouteOpeningBalance.cls
global class UpdateRouteOpeningBalance  implements Database.Batchable<sObject>,Database.Stateful,Schedulable{

     public Database.QueryLocator start(Database.BatchableContext BC){
        String query='select Id,Name,Route_ID__c from Route__c';
      return Database.getQueryLocator(query);
   }

    public void execute(Database.BatchableContext BC, List<Route__c> scope){
        Set<Id> rtIds = new Set<Id>();
        
        for(Route__c rt : scope){
            rtIds.add(rt.Id);
        }
        Map<Id,Cashbook__c> cbMap = new Map<Id,Cashbook__c>();
         List<Cashbook__c> cbList = [select Id,Name,Route__c,Branch__c,Opening_Balance__c,Closing_Balance__c,CreatedDate from Cashbook__c where CreatedDate = yesterday and Route__c IN:rtIds];
        List<Cashbook__c> cbListToUpdate = new List<Cashbook__c>();
        if(cbList.size() != 0){
            for(Cashbook__c cb: cbList){
                cbMap.put(cb.Route__c,cb);
            }
        }
        else{
             for(Route__c rt: scope){
                Cashbook__c cb1 = new Cashbook__c();
                cb1.Route__c = rt.Id;
                cb1.Opening_Balance__c = 0;
                 cbListToUpdate.add(cb1);
            }
        }      
        
        
        if(cbMap.size() != 0){
            for(Route__c rt: scope){
                if(cbMap.containsKey(rt.Id)){
                    Cashbook__c cb1 = new Cashbook__c();
                    cb1.Route__c = rt.Id;
                    cb1.Opening_Balance__c = cbMap.get(rt.Id).Closing_Balance__c;
                    cbListToUpdate.add(cb1);
                }
                else{
                    Cashbook__c cb1 = new Cashbook__c();
                    cb1.Route__c = rt.Id;
                    cb1.Opening_Balance__c = 0;
                    cbListToUpdate.add(cb1);
                }
              
            }
             
             
         }
     system.debug('cbListToUpdate:' + cbListToUpdate);
       insert cbListToUpdate;
    }
    
    public void finish(Database.BatchableContext BC){
   }
    
     global void execute(SchedulableContext SC){
        database.executeBatch(new UpdateRouteOpeningBalance(),100);
      
    } 

}