force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item_Replacement__c/Item_Replacement__c.object-meta.xml
<CustomObject>
    <label>Item Replacement</label>
    <nameField>
        <displayFormat>IR-{0000}</displayFormat>
        <label>Item Replacement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Item Replacements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item_Replacement__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Item Replacements</relationshipLabel>
    <relationshipName>Item_Replacements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Item_Replacement__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Item Replacements</relationshipLabel>
    <relationshipName>Item_Replacements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Item_Replacement__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Item Replacements</relationshipLabel>
    <relationshipName>Item_Replacements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Item_Replacement__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Return</fullName>
            </value>
            <value>
                <fullName>Replacement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/CompanyId__c.field-meta.xml
<CustomField>
    <fullName>CompanyId__c</fullName>
    <label>Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Company</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/GST__c.field-meta.xml
<CustomField>
    <fullName>GST__c</fullName>
    <label>GST</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GST_percentages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Replaced_Item__c/Replaced_Item__c.object-meta.xml
<CustomObject>
    <label>Replaced Item</label>
    <nameField>
        <label>Replaced Item Name (Damged Item)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Replaced Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Replaced_Item__c/fields/Batch_No__c.field-meta.xml
<CustomField>
    <fullName>Batch_No__c</fullName>
    <formula>Damaged_Stock__r.Batch_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Batch No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Replaced_Item__c/fields/Damaged_Stock__c.field-meta.xml
<CustomField>
    <fullName>Damaged_Stock__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Damaged Stock</label>
    <referenceTo>Stock__c</referenceTo>
    <relationshipLabel>Replaced Items</relationshipLabel>
    <relationshipName>Replaced_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Replaced_Item__c/fields/Item_Replacement__c.field-meta.xml
<CustomField>
    <fullName>Item_Replacement__c</fullName>
    <label>Item Replacement</label>
    <referenceTo>Item_Replacement__c</referenceTo>
    <relationshipLabel>Replaced Items</relationshipLabel>
    <relationshipName>Replaced_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Replaced_Item__c/fields/New_Created_Stock__c.field-meta.xml
<CustomField>
    <fullName>New_Created_Stock__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Created Stock</label>
    <referenceTo>Stock__c</referenceTo>
    <relationshipLabel>Replaced Items (New Created Stock)</relationshipLabel>
    <relationshipName>Replaced_Items2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Replaced_Item__c/fields/New_Stock__c.field-meta.xml
<CustomField>
    <fullName>New_Stock__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Replaced Stock</label>
    <referenceTo>Stock__c</referenceTo>
    <relationshipLabel>Replaced Items (New Stock)</relationshipLabel>
    <relationshipName>Replaced_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Replaced_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Replaced Items</relationshipLabel>
    <relationshipName>Replaced_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Replaced_Item__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <formula>Item_Replacement__r.Route__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Route</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Replaced_Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Return</fullName>
            </value>
            <value>
                <fullName>Replacement</fullName>
            </value>
            <value>
                <fullName>Non-Saleable</fullName>
                <isActive>false</isActive>
                <label>Non-Saleable</label>
            </value>
            <value>
                <fullName>Saleable</fullName>
                <isActive>false</isActive>
                <label>Saleable</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Route__c/fields/CompanyId__c.field-meta.xml
<CustomField>
    <fullName>CompanyId__c</fullName>
    <label>Company Id</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Company</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Route__c/fields/Route_Id__c.field-meta.xml
<CustomField>
    <fullName>Route_Id__c</fullName>
    <externalId>true</externalId>
    <label>Route Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Route__c/fields/Week__c.field-meta.xml
<CustomField>
    <fullName>Week__c</fullName>
    <label>Week</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FIR</fullName>
                <label>First Week</label>
            </value>
            <value>
                <fullName>SEC</fullName>
                <label>Second Week</label>
            </value>
            <value>
                <fullName>THI</fullName>
                <label>Third Week</label>
            </value>
            <value>
                <fullName>FOR</fullName>
                <label>Fourth Week</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>Stock-{00000}</displayFormat>
        <label>Stock Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/fields/Available_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Available_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Available Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Blocked_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Blocked_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Blocked Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Damaged_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Damaged_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Damaged Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Intial_Stock__c.field-meta.xml
<CustomField>
    <fullName>Intial_Stock__c</fullName>
    <label>Intial Stock</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Sold_Qty__c.field-meta.xml
<CustomField>
    <fullName>Sold_Qty__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sold Qty</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saleable</fullName>
            </value>
            <value>
                <fullName>Non-Saleable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stock_History__c/Stock_History__c.object-meta.xml
<CustomObject>
    <label>Stock History</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Stock History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock History</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_History__c/fields/Available_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Available_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Closing Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock_History__c/fields/Blocked_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Blocked_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Blocked Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock_History__c/fields/Ext_ID__c.field-meta.xml
<CustomField>
    <fullName>Ext_ID__c</fullName>
    <label>Ext. ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock_History__c/fields/Opening_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Opening_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Opening Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock_History__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Stock History</relationshipLabel>
    <relationshipName>Stock_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_History__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Stock History</relationshipLabel>
    <relationshipName>Stock_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ItemReplacementHandlerTest.cls
@isTest
public class ItemReplacementHandlerTest {
    @testSetup
    static void setupTestData() {
        
         Account acc=new Account();
        acc.Name='testaccount1';
        acc.Phone = '9985542322';
        acc.Email__c = 'test@gmail.com';
        acc.CardType__c = 'C';
        acc.CompanyId__c = 'Dev';
        acc.OwnerId = UserInfo.getUserId();
        insert acc;
        
        Route__c routeRec = new Route__c();
        routeRec.Name = 'Kannur Route';
        routeRec.Route_Id__c = 'RI-01000';
        routeRec.Week_Sales__c = 'SUN';
        //routeRec.Week__c = 'First Week';
        insert routeRec;
        
        Product__c productRec = new Product__c();
        productRec.Name = 'Dev Snacks Rosted peanut';
        productRec.Product_Code__c = 'P009';
        productRec.MRP__c = 25;
        productRec.GST__c = '5';
        insert productRec;
        
        Stock_History__c his = new Stock_History__c();
        his.Route__c = routeRec.Id;
        his.Product__c = productRec.Id;
        his.Opening_Quantity__c = 100;
        his.Available_Quantity__c = his.Opening_Quantity__c;
        his.Ext_ID__c = String.valueOf(his.Product__c) + String.valueOf(his.Route__c)  + system.today();
        his.Date__c = system.today() ;
        insert his;      
        
        
        Stock__c stock = new Stock__c();
        stock.Intial_Stock__c = 100;
        stock.Available_Quantity__c = 70;
        stock.Sold_Qty__c = 15;
        stock.Blocked_Quantity__c = 15;
        stock.Product__c = productRec.id;
        Insert stock;
        Stock__c stock1 = new Stock__c();
        stock1.Intial_Stock__c = 100;
        stock1.Available_Quantity__c = 70;
        stock1.Sold_Qty__c = 15;
        stock1.Blocked_Quantity__c = 15;
        stock1.Product__c = productRec.id;
        Insert stock1;
        Item_Replacement__c item = new Item_Replacement__c();
        item.Customer__c=acc.Id;
        item.Type__c='Replacement';
        item.Route__c=routeRec.Id;
        insert item;
        Replaced_Item__c r = new Replaced_Item__c();
        r.Item_Replacement__c=item.Id;
        r.Product__c=productRec.Id;
        r.Quantity__c=2;
        r.New_Stock__c=stock.Id;
        r.Damaged_Stock__c = stock1.Id;
        insert r;
    }

    @isTest
    static void testUpdateStock() {
        // Retrieve test data
        List<Replaced_Item__c> replacedItems = [select Id,Name,Product__c,Quantity__c,New_Created_Stock__c,Damaged_Stock__c,New_Stock__c,
                                              Item_Replacement__r.Route__c,Item_Replacement__r.Route__r.OwnerId,Item_Replacement__r.Branch__c,
                                              Batch_No__c,Item_Replacement__r.Type__c,Type__c from Replaced_Item__c];
        System.assert(!replacedItems.isEmpty(), 'Test Replaced Items should exist');

        // Mock the StopRecursion flag
        StopRecursion.executeReturnItemTrigger = true;

        // Call the method to test
        Test.startTest();
        ItemReplacementHandler.updateStock(replacedItems);
        ItemReplacementHandler.updateAvailableStock(replacedItems);
          ItemReplacementHandler.testcover();
        Test.stopTest();

        // Verify updates to stock records
        //Stock__c updatedStock = [SELECT Id, Damaged_Quantity__c FROM Stock__c WHERE Id = :replacedItems[0].Damaged_Stock__c LIMIT 1];
        //System.assertEquals(10, updatedStock.Damaged_Quantity__c, 'Damaged Quantity should be updated correctly');
    }
}