force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/Cash_In_Hand__c.field-meta.xml
<CustomField>
    <fullName>Cash_In_Hand__c</fullName>
    <label>Cash In Hand</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Cash_Transfer__c/Cash_Transfer__c.object-meta.xml
<CustomObject>
    <label>Cash Transfer</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Cash Transfer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cash Transfers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cash_Transfer__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Cash Transfers</relationshipLabel>
    <relationshipName>Cash_Transfers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cash_Transfer__c/fields/From__c.field-meta.xml
<CustomField>
    <fullName>From__c</fullName>
    <label>From</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Branch</fullName>
            </value>
            <value>
                <fullName>Route</fullName>
            </value>
            <value>
                <fullName>Head Office</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cash_Transfer__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Cash Transfers</relationshipLabel>
    <relationshipName>Cash_Transfers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cash_Transfer__c/fields/To__c.field-meta.xml
<CustomField>
    <fullName>To__c</fullName>
    <label>To</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Branch</fullName>
            </value>
            <value>
                <fullName>Route</fullName>
            </value>
            <value>
                <fullName>Head Office</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cashbook__c/Cashbook__c.object-meta.xml
<CustomObject>
    <label>Cashbook</label>
    <nameField>
        <displayFormat>CB-{0000}</displayFormat>
        <label>Cashbook Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cashbooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cashbook__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Cashbooks</relationshipLabel>
    <relationshipName>Cashbooks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cashbook__c/fields/Closing_Balance__c.field-meta.xml
<CustomField>
    <fullName>Closing_Balance__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Closing Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Cashbook__c/fields/Opening_Balance__c.field-meta.xml
<CustomField>
    <fullName>Opening_Balance__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Opening Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Cashbook__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Cashbooks</relationshipLabel>
    <relationshipName>Cashbooks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <displayFormat>EP-{00000}</displayFormat>
        <label>Expense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <formula>IF(ISPICKVAL(Select_Expense_Entry__c, &apos;General&apos;)  || Text(Select_Expense_Entry__c)==Null, TA__c  +  DA__c +  Food_Expense__c +  Fuel_Expense__c  +  Vehicle_Repair_Expense__c  +  Accommodation_Expense__c +  Other_Expenses__c, Amount__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>REC-{0000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/Approval_status__c.field-meta.xml
<CustomField>
    <fullName>Approval_status__c</fullName>
    <defaultValue>&apos;New&apos;</defaultValue>
    <label>Approval status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted for approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipName>Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Approval_Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Mode_of_payment__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_payment__c</fullName>
    <label>Mode of payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>UPI</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Bank Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipName>Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Route__c/fields/Route_Id__c.field-meta.xml
<CustomField>
    <fullName>Route_Id__c</fullName>
    <externalId>true</externalId>
    <label>Route Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/UpdateRouteClosingBalance.cls
global class UpdateRouteClosingBalance  implements Database.Batchable<sObject>,Database.Stateful,Schedulable{
    
    public Database.QueryLocator start(Database.BatchableContext BC){
        String query='select Id,Name,Route_ID__c,Cash_In_Hand__c from Route__c';
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<Route__c> scope){
        Set<Id> rtIds = new Set<Id>();
        Map<Id,Decimal> rtMap = new Map<Id,Decimal>();
        
        for(Route__c rt : scope){
            rtIds.add(rt.Id);
            if(rt.Cash_In_Hand__c == null){
                rt.Cash_In_Hand__c = 0;
            }
            rtMap.put(rt.Id,rt.Cash_In_Hand__c);
        }
      Map<Id,Cashbook__c> cbMap = new Map<Id,Cashbook__c>();
        
          List<Cashbook__c> cbList = [select Id,Name,Route__c,Branch__c,Opening_Balance__c,Closing_Balance__c,CreatedDate from Cashbook__c where CreatedDate = today and Route__c IN:rtIds];
       
         if(cbList.size() != 0){
            for(Cashbook__c cb: cbList){
                cbMap.put(cb.Route__c,cb);
            }
        }
        
      /*  List<Cashbook__c> cbListToUpdate = new List<Cashbook__c>();
        
        //Decimal totalDr=0,totalCr=0,ClosingBalance=0;
        Map<Id,Decimal> totalDrMap = new Map<Id,Decimal>();
        Map<Id,Decimal> totalCrMap = new Map<Id,Decimal>();
        
        List<Cash_Transfer__c> translist = [select id,Name,From__c, TO__c, Route__c, Amount__c, CreatedDate from Cash_Transfer__c where Route__c IN:rtIds and CreatedDate = today];
        if(translist.size() > 0){
            for(Cash_Transfer__c ct: translist){
                if(ct.Amount__c !=null){
                    if(ct.From__c == 'Branch' && ct.To__c == 'Route'){
                        //totalCr = totalCr + ct.Amount__c;
                        if(totalCrMap.containsKey(ct.Route__c)){
                            totalCrMap.put(ct.Route__c,totalCrMap.get(ct.Route__c) + ct.Amount__c);
                        }
                        else{
                           totalCrMap.put(ct.Route__c,ct.Amount__c); 
                        }
                        
                    }
                    else if(ct.From__c == 'Route' && ct.To__c == 'Branch'){
                        if(totalDrMap.containsKey(ct.Route__c)){
                            totalDrMap.put(ct.Route__c,totalDrMap.get(ct.Route__c) + ct.Amount__c);
                        }
                        else{
                           totalDrMap.put(ct.Route__c,ct.Amount__c); 
                        }
                      //  totalDr = totalDr + ct.Amount__c;
                    }
                }
            }
        }
        
        List<Receipt__c> recList = [select Id,Name,Branch__c,Branch__r.Name,Route__c,Route__r.Name,Amount__c,Customer__c,Customer__r.Name,Remarks__c,CreatedDate from Receipt__c where Mode_of_Payment__c = 'Cash' and Route__c IN:rtIds and CreatedDate = today];
        if(recList.size() > 0){
            for(Receipt__c rec: recList){
                if(rec.Amount__c != null && rec.Route__c != null && rec.Customer__c != null){
                    if(totalCrMap.containsKey(rec.Route__c)){
                            totalCrMap.put(rec.Route__c,totalCrMap.get(rec.Route__c) + rec.Amount__c);
                        }
                        else{
                           totalCrMap.put(rec.Route__c,rec.Amount__c); 
                        }
                    //totalCr = totalCr + rec.Amount__c;
                }
            }
        }
        
        List<Expense__c> explist = [select Id,Name,Branch__c,Route__c,Branch__r.Name,Route__r.Name,Total_Amount__c,Expense_Comments__c,CreatedDate from Expense__c where Route__c IN:rtIds and Approval_Status__c = 'Approved' and CreatedDate = today];
        if(explist.size() > 0){
            for(Expense__c exp: explist){
                if(exp.Total_Amount__c != null){
                    if(totalDrMap.containsKey(exp.Route__c)){
                            totalDrMap.put(exp.Route__c,totalDrMap.get(exp.Route__c) + exp.Total_Amount__c);
                        }
                        else{
                           totalDrMap.put(exp.Route__c,exp.Total_Amount__c); 
                        }
                      //totalDr = totalDr + exp.Total_Amount__c;
                }
            }
        }
        
         //ClosingBalance = totalCr - totalDr;
        system.debug('cbMap:' + cbMap.values());
         if(cbMap.size() != 0){
            for(Route__c rt: scope){
                if(cbMap.containsKey(rt.Id)){
                    Cashbook__c cb1 = cbMap.get(rt.Id);
                    cb1.Route__c = rt.Id;
                    if(totalCrMap.containsKey(rt.Id) && totalDrMap.containsKey(rt.Id)){
                    cb1.Closing_Balance__c = totalCrMap.get(rt.Id) - totalDrMap.get(rt.Id);
                    }
                    if(totalCrMap.containsKey(rt.Id) && !totalDrMap.containsKey(rt.Id)){
                    cb1.Closing_Balance__c = totalCrMap.get(rt.Id);
                    }
                    if(!totalCrMap.containsKey(rt.Id) && totalDrMap.containsKey(rt.Id)){
                    cb1.Closing_Balance__c = 0 - totalDrMap.get(rt.Id);
                    }
                      //cbList.add(cb1);
                }
                
            }
             
             
         }*/
        
         if(cbMap.size() != 0){
            for(Route__c rt: scope){
                if(cbMap.containsKey(rt.Id)){
                    Cashbook__c cb1 = cbMap.get(rt.Id);
                    cb1.Route__c = rt.Id;
                   cb1.Closing_Balance__c = rtMap.get(rt.Id);
                      //cbList.add(cb1);
                }
                
            }
         }
        system.debug('cbMap:' + cbMap);
        update cbMap.values();
    }
    
    public void finish(Database.BatchableContext BC){
    }
    
     global void execute(SchedulableContext SC){
        database.executeBatch(new UpdateRouteClosingBalance(),100);
      
    } 
}