force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Branches</relationshipLabel>
    <relationshipName>Branches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/GST__c.field-meta.xml
<CustomField>
    <fullName>GST__c</fullName>
    <label>GST</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GST_percentages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Route__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Routes</relationshipLabel>
    <relationshipName>Routes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Routes</relationshipLabel>
    <relationshipName>Routes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>Stock-{00000}</displayFormat>
        <label>Stock Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Manufacturing_Date__c.field-meta.xml
<CustomField>
    <fullName>Manufacturing_Date__c</fullName>
    <label>Manufacturing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Stock_Transfer__c.field-meta.xml
<CustomField>
    <fullName>Stock_Transfer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stock Transfer</label>
    <referenceTo>Stock_Transfer__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Request__c/Stock_Request__c.object-meta.xml
<CustomObject>
    <label>Stock Request</label>
    <nameField>
        <displayFormat>REQ-{0000}</displayFormat>
        <label>Stock Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_Request__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Stock Requests</relationshipLabel>
    <relationshipName>Stock_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Request__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Stock Requests</relationshipLabel>
    <relationshipName>Stock_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Transferred</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stock_Request__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Stock Requests</relationshipLabel>
    <relationshipName>Stock_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Request_Item__c/Stock_Request_Item__c.object-meta.xml
<CustomObject>
    <label>Stock Request Item</label>
    <nameField>
        <label>Stock Request Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stock Request Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_Request_Item__c/fields/Item_Code__c.field-meta.xml
<CustomField>
    <fullName>Item_Code__c</fullName>
    <formula>Product__r.Product_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Item Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock_Request_Item__c/fields/Margin__c.field-meta.xml
<CustomField>
    <fullName>Margin__c</fullName>
    <label>Margin</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Stock_Request_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Stock Request Items</relationshipLabel>
    <relationshipName>Stock_Request_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Request_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Requested Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock_Request_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Transferred</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stock_Request_Item__c/fields/Stock_Request__c.field-meta.xml
<CustomField>
    <fullName>Stock_Request__c</fullName>
    <label>Stock Request</label>
    <referenceTo>Stock_Request__c</referenceTo>
    <relationshipLabel>Stock Request Items</relationshipLabel>
    <relationshipName>Stock_Request_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Stock_Request_Item__c/fields/Stock_Request_Item_Id__c.field-meta.xml
<CustomField>
    <fullName>Stock_Request_Item_Id__c</fullName>
    <externalId>true</externalId>
    <label>Stock Request Item Id</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Stock_Request_Item__c/fields/Transfered_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Transfered_Quantity__c</fullName>
    <label>Transfered Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock_Transfer__c/Stock_Transfer__c.object-meta.xml
<CustomObject>
    <label>Stock Transfer</label>
    <nameField>
        <displayFormat>STR-{0000}</displayFormat>
        <label>Stock Transfer ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Transfers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_Transfer__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Stock Transfers</relationshipLabel>
    <relationshipName>Stock_Transfers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Transfer__c/fields/From__c.field-meta.xml
<CustomField>
    <fullName>From__c</fullName>
    <label>From</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Warehouse</fullName>
            </value>
            <value>
                <fullName>Branch</fullName>
            </value>
            <value>
                <fullName>Route</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stock_Transfer__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Stock Transfers</relationshipLabel>
    <relationshipName>Stock_Transfers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Transfer__c/fields/Stock_Request__c.field-meta.xml
<CustomField>
    <fullName>Stock_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stock Request</label>
    <referenceTo>Stock_Request__c</referenceTo>
    <relationshipLabel>Stock Transfers</relationshipLabel>
    <relationshipName>Stock_Transfers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Transfer__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Stock Transfers</relationshipLabel>
    <relationshipName>Stock_Transfers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Transfer__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Stock Transfers</relationshipLabel>
    <relationshipName>Stock_Transfers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Vehicle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ConfirmStockController.cls
public class ConfirmStockController {
    
     @AuraEnabled
    public static String getUIThemeDescription() {
        String theme = UserInfo.getUiThemeDisplayed();
        return theme;
    }
    
    @AuraEnabled
    public static List<Stock_Request_Item__c> getStock(String recId){
        
        return [select Id,Name,Product__c,Item_Code__c,Quantity__c,Transfered_Quantity__c,Manufacturing_Date__c,Batch_Number__c,Expiry_Date__c,MRP__c,
                Received_Qunatity__c,Status__c,Stock_Request_Item_Id__c,Stock_Request__c,Product__r.GST__c,Stock_Request__r.Status__c,Margin__c from Stock_Request_Item__c where Stock_Request__c =:recId and (Transfered_Quantity__c != null and Transfered_Quantity__c != 0) ];
    }
     @AuraEnabled
    public static String checkStatus(String recId){
        
        return [select Id,Name,Status__c from Stock_Request__c where Id =:recId  ].Status__c;
    }
    @AuraEnabled
    public static String rejectNewRequest(List<Stock_Request_Item__c> reqList, String recId){
        system.debug('reqList=== '+reqList);
        system.debug('recId=== '+recId);
        List<Stock_Request_Item__c> stockReqItems = new List<Stock_Request_Item__c>();
        Stock_Request__c stockReq = [Select Id,Name,Status__c,Branch__c,Route__c,Route__r.Warehouse__c,Route__r.Vehicle__c from Stock_Request__c where id=:recId];
        stockReq.Status__c = 'Cancelled';
        
         try {
          update stockReq;
        }
        catch (System.Exception ae) { 
           ExceptionHandler.addLog(ae,String.valueOf(stockReq) ); 
        }     
        
        for(Stock_Request_Item__c stockReqItem: reqList){
            stockReqItem.Status__c = 'Cancelled';
            stockReqItems.add(stockReqItem);
        }
        if(stockReqItems.size()>0){
            
            try {
                update stockReqItems;
            }
            catch (System.Exception ae) { 
                ExceptionHandler.addLog(ae,String.valueOf(stockReqItems) ); 
            }
        }
        system.debug('stockReqItems=== '+stockReqItems);
        return stockReq.Id;
    }
    @AuraEnabled
    public static String saveNewRequest(List<Stock_Request_Item__c> reqList, String recId ){
        
        Stock_Request__c sr = [Select Id,Name,Status__c,Branch__c,Route__c,Route__r.Warehouse__c,Route__r.Vehicle__c,Transfer_Date__c from Stock_Request__c where id=:recId];
        
        Stock_Transfer__c st = new Stock_Transfer__c();
        st.Transfer_Date__c = sr.Transfer_Date__c != null ? sr.Transfer_Date__c : system.today();
        st.Stock_Request__c = sr.Id;
        st.From__c = 'Branch';
        st.To__c = 'Route';
        st.Route__c = sr.Route__c;
        st.Branch__c = sr.Branch__c;
        st.Warehouse__c = sr.Route__r.Warehouse__c;
        st.Vehicle__c = sr.Route__r.Vehicle__c;
        try {
            insert st;
        }
        catch (System.Exception ae) { 
            ExceptionHandler.addLog(ae,String.valueOf(st) ); 
        }
        
        
        List<Stock__c> stList = [select Id,Name,Stock_Date__c,Product__c,Route__c,Batch_Number__c,Intial_Stock__c,Available_Quantity__c,Sold_Qty__c,Manufacturing_Date__c,Price__c,Stock_Ext_ID__c from Stock__c where Stock_Ext_ID__c != null ];
        Map<String,Stock__c> stockMap = new Map<String,Stock__c>();
        for(Stock__c stk:stList){
            stockMap.put(stk.Stock_Ext_ID__c, stk);
        }
        
        String extId='';
        
        List<Stock__c> stocklist = new List<Stock__c>();
        for(Stock_Request_Item__c sri: reqList){
          system.debug('sri=== '+sri.MRP__c);
            
            Stock__c stock = new Stock__c();
            
            if(sri.Batch_Number__c != null && sri.Product__c != null && sri.Manufacturing_Date__c != null && sri.MRP__c != null){
                extId = sr.Route__c + String.valueOf(sri.Product__c) + sri.Batch_Number__c + sri.Manufacturing_Date__c + sri.MRP__c.setScale(2) + system.today();
            }
            
            if(stockMap.containsKey(extId)){
                stock = stockMap.get(extId);
                stock.Intial_Stock__c = stockMap.get(extId).Intial_Stock__c + sri.Received_Qunatity__c;
                stock.Available_Quantity__c = stockMap.get(extId).Available_Quantity__c + sri.Received_Qunatity__c;
            }
            else{
                stock.Stock_Date__c = system.today();
                stock.Product__c = sri.Product__c;
                stock.Related_To__c = 'Route';
                stock.Route__c = sr.Route__c;
                stock.Batch_Number__c = sri.Batch_Number__c;
                stock.Branch__c = sr.Branch__c;
                stock.Warehouse__c = sr.Route__r.Warehouse__c;
                stock.Vehicle__c = sr.Route__r.Vehicle__c;
                stock.GST_Percentage__c = sri.Product__r.GST__c != null ? Decimal.valueOf(sri.Product__r.GST__c) : 0;
                stock.Intial_Stock__c = sri.Received_Qunatity__c;
                stock.Available_Quantity__c = sri.Received_Qunatity__c;
                stock.Sold_Qty__c = stock.Intial_Stock__c - stock.Available_Quantity__c;
                stock.Stock_Transfer__c = st.Id;
                stock.Manufacturing_Date__c = sri.Manufacturing_Date__c;
                stock.Expiry_Date__c = sri.Expiry_Date__c;  
                stock.Price__c = sri.MRP__c;
                stock.Margin__c = sri.Margin__c;
                stock.Stock_Ext_ID__c = extId;
            }
            
            sri.Status__c = 'Received';
            
            stocklist.add(stock);
            
        }
       
        
        try{
            
            upsert stocklist Stock_Ext_ID__c ;
            
            sr.Status__c = 'Received';
            sr.Received_Date_Time__c = system.now();
            update sr;
            
            update reqList;
            
        }
        catch(Exception ae){
            ExceptionHandler.addLog(ae,String.valueOf(stocklist) + '---' + String.valueOf(sr) + '---' + String.valueOf(reqList)  ); 
        }
        
        return recId;
    }
}