force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/Godown_Manager__c.field-meta.xml
<CustomField>
    <fullName>Godown_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Godown Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Branches1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Branch__c/fields/Manager_Name__c.field-meta.xml
<CustomField>
    <fullName>Manager_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Branches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Branch__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Branches</relationshipLabel>
    <relationshipName>Branches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_item__c/Invoice_item__c.object-meta.xml
<CustomObject>
    <label>Invoice item2</label>
    <nameField>
        <displayFormat>IIT-{000000}</displayFormat>
        <label>Invoice item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice items2</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product Name</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Invoice items</relationshipLabel>
    <relationshipName>Invoice_items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Fixed_Price_Item__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Price_Item__c</fullName>
    <defaultValue>&apos;N&apos;</defaultValue>
    <label>Fixed Price Item</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
                <default>true</default>
                <label>N</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_catogery__c.field-meta.xml
<CustomField>
    <fullName>Product_catogery__c</fullName>
    <label>Product catogery</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Image__c.field-meta.xml
<CustomField>
    <fullName>Product_Image__c</fullName>
    <formula>IF(Product_Image_Url__c != null , IMAGE(  Product_Image_Url__c , &apos;image&apos;), IMAGE(  &apos;https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxw2zmO4oHZBX0PUSZd_nD6IAl203sdkzxCw&amp;usqp=CAU&apos; , &apos;image&apos;) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Image</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Image_Url__c.field-meta.xml
<CustomField>
    <fullName>Product_Image_Url__c</fullName>
    <label>Product Image Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Route__c/fields/Branch_Name__c.field-meta.xml
<CustomField>
    <fullName>Branch_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch Name</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Routes</relationshipLabel>
    <relationshipName>Routes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route__c/fields/Route_Id__c.field-meta.xml
<CustomField>
    <fullName>Route_Id__c</fullName>
    <externalId>true</externalId>
    <label>Route Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Route__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Routes</relationshipLabel>
    <relationshipName>Routes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Routes</relationshipLabel>
    <relationshipName>Routes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Request__c/Stock_Request__c.object-meta.xml
<CustomObject>
    <label>Stock Request</label>
    <nameField>
        <displayFormat>REQ-{0000}</displayFormat>
        <label>Stock Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_Request__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Stock Requests</relationshipLabel>
    <relationshipName>Stock_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Request__c/fields/Godown_Manager__c.field-meta.xml
<CustomField>
    <fullName>Godown_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Godown Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Stock_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Request__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Stock Requests</relationshipLabel>
    <relationshipName>Stock_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Transferred</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stock_Request__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Stock Requests</relationshipLabel>
    <relationshipName>Stock_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Request_Item__c/Stock_Request_Item__c.object-meta.xml
<CustomObject>
    <label>Stock Request Item</label>
    <nameField>
        <label>Stock Request Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stock Request Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_Request_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Stock Request Items</relationshipLabel>
    <relationshipName>Stock_Request_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Request_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Requested Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock_Request_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Transferred</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stock_Request_Item__c/fields/Stock_Request__c.field-meta.xml
<CustomField>
    <fullName>Stock_Request__c</fullName>
    <label>Stock Request</label>
    <referenceTo>Stock_Request__c</referenceTo>
    <relationshipLabel>Stock Request Items</relationshipLabel>
    <relationshipName>Stock_Request_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Vehicle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit - {00000000}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Route_Id__c.field-meta.xml
<CustomField>
    <fullName>Route_Id__c</fullName>
    <formula>Owner:User.Route_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Route Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>PostPone</fullName>
                <isActive>false</isActive>
                <label>PostPone</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NewStockReqController.cls
public class NewStockReqController {

    
      @auraEnabled
    Public static List<Product__c> getStock(){
        return [SELECT Id,name from Product__c];
    }
     @AuraEnabled
    public static String getUIThemeDescription() {
        String theme = UserInfo.getUiThemeDisplayed();
        return theme;
    }
    
    @auraEnabled
    public static Product__c getSelectedProduct(string recordId){
        List<Product__c> selectedProduct = [select Id,Name, Product_Code__c, Item_Description__c, Unit__c,Product_catogery__c,Product_Image__c,Product_Image_Url__c,Fixed_Price_Item__c
                                            from Product__c where Id =: recordId Limit 1];
        return selectedProduct[0];
    }
    
      @auraEnabled
    Public static List<Product__c> getProducts(String pageSize, String pageNumber, string searchText, string sortDirection,string sortBy, string searchType){
        List<Product__c> plist = new List<Product__c>();
        String searchKey = '%'+searchText+ '%';
 
        String query = 'select Id,Name, Product_Code__c, Item_Description__c, Unit__c,Product_catogery__c,Product_Image__c,Product_Image_Url__c,Fixed_Price_Item__c from Product__c';
        if (String.isNotBlank(searchText)) {
            if(searchType == 'Name'){
                query += ' where (Name like: searchKey)';
            } else if(searchType == 'Code'){
                query += ' where (Product_Code__c LIKE: searchKey)';
            } 
        }
 
        query += ' limit 1000';
        system.debug('query:' + query);
        plist =  Database.query(query);
        system.debug('plist:' + plist);
        
        return plist;
    }
    
      @AuraEnabled
    public static String saveNewRequest(List<Stock_Request_Item__c> reqList ){
        system.debug(reqList);
        User user = [select id,name,Route_Id__c from User where id=:UserInfo.getUserId() limit 1];
        List<Route__c> rt = new List<Route__c>();

        Stock_Request__c sr = new Stock_Request__c();
        sr.Request_Date__c = system.today();
        sr.Status__c = 'Requested';
        if(user.Route_Id__c != null){
            rt = [select id,Route_Id__c,Warehouse__c,Branch_Name__c,Branch_Name__r.Manager_Name__c,Vehicle__c from Route__c where Route_Id__c =:user.Route_Id__c limit 1];
            if(rt.size() > 0){
                sr.Route__c = rt[0].Id;
                sr.Vehicle__c = rt[0].Vehicle__c;
                sr.Branch__c = rt[0].Branch_Name__c;
                sr.Godown_Manager__c = rt[0].Branch_Name__r.Manager_Name__c;
            }
        }
        
        //insert sr;
         try {
           insert sr;
        }
        catch (System.Exception ae) { 
            ExceptionHandler.addLog(ae,String.valueOf(sr) ); 
        }     
        
        for(Stock_Request_Item__c sri: reqList){
            sri.Stock_request__c = sr.Id;
        }
        
          try {
           insert reqList;
        }
        catch (System.Exception ae) { 
            ExceptionHandler.addLog(ae,String.valueOf(reqList) ); 
        }     
      
        return sr.Id;
    }
  /*  @AuraEnabled
    public static List<Invoice_item__c> upsertReqItem(string  orderItemList,string ordId ){
      
      /*  List<Order_Item__c> ordItList = new List<Order_Item__c>();
        for(Order_Item__c ord : orderItemList){
          Order_Item__c orl = ord;
            ordItList.add(orl);
        }
          upsert orderItemList;*/
      /*   system.debug(orderItemList);
        system.debug('ordId-'+ordId);
        string newstring = orderItemList.replace('[','');
        string newstring2 = newstring.replace(']','');
        string newstring3 = '['+newstring2+']';
        string newstring4 = newstring3.replace('Id', 'Product__c');
         List<Invoice_item__c> ordList = (List<Invoice_item__c>)JSON.deserialize( newstring4, List<Invoice_item__c>.class);
        system.debug('final list-'+ordList);
        list<Invoice_item__c>upsertlst=new list<Invoice_item__c>();
        for(Invoice_item__c t:ordList){
            Invoice_item__c i =new Invoice_item__c();
            i.Total_Amount__c=t.Total_Amount__c;
            i.TAX_Per_GST__c=t.TAX_Per_GST__c;
            i.Product__c=t.Product__c;
            i.Quantity__c=t.Quantity__c;
            i.Invoice__c=ordId;
            upsertlst.add(i);
        }
        Upsert upsertlst;
      
       /* system.debug(orderItemList + ' '+storeId);
        List<Order_Item__c> orList = new List<Order_Item__c>();
        Order__c ord = new Order__c();
        ord.Store__c = storeId;
        ord.Order_Date__c = system.today();
        //ord.Grand_Total__c = grandtotal;
        insert ord;
        
        for(Order_Item__c ol : orderItemList){
            ol.Order__c = ord.id;
            orList.add(ol);
            
        }
        insert orList;*/
     /*    List<Invoice_item__c> orderList =  [SELECT Id, Name,Invoice__r.EID__c,Visit__r.EID__c,Store__r.EID__c, Unit_Price__c,Visit__c,Store__c, Price_MRP__c, Invoice__c, Product__c, Quantity__c, TAX_Per_GST__c, Tax_Value__c, Total_Amount__c, Total_Price__c FROM Invoice_item__c WHERE CreatedDate=TODAY  AND Invoice__r.OwnerId=:userinfo.getUserId()];

        return orderList;
    }*/
    
}