force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/Branch_Id__c.field-meta.xml
<CustomField>
    <fullName>Branch_Id__c</fullName>
    <label>Branch Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cashbook__c/Cashbook__c.object-meta.xml
<CustomObject>
    <label>Cashbook</label>
    <nameField>
        <displayFormat>CB-{0000}</displayFormat>
        <label>Cashbook Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cashbooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cashbook__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Cashbooks</relationshipLabel>
    <relationshipName>Cashbooks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cashbook__c/fields/Closing_Balance__c.field-meta.xml
<CustomField>
    <fullName>Closing_Balance__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Closing Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Cashbook__c/fields/Opening_Balance__c.field-meta.xml
<CustomField>
    <fullName>Opening_Balance__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Opening Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Cashbook__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Cashbooks</relationshipLabel>
    <relationshipName>Cashbooks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/UpdateBranchOpeningBalance.cls
global class UpdateBranchOpeningBalance  implements Database.Batchable<sObject>,Database.Stateful,Schedulable{

     public Database.QueryLocator start(Database.BatchableContext BC){
        String query='select Id,Name,Branch_ID__c from Branch__c';
      return Database.getQueryLocator(query);
   }

    public void execute(Database.BatchableContext BC, List<Branch__c> scope){
        Set<Id> rtIds = new Set<Id>();
        
        for(Branch__c rt : scope){
            rtIds.add(rt.Id);
        }
        Map<Id,Cashbook__c> cbMap = new Map<Id,Cashbook__c>();
         List<Cashbook__c> cbList = [select Id,Name,Route__c,Branch__c,Opening_Balance__c,Closing_Balance__c,CreatedDate from Cashbook__c where CreatedDate = yesterday and Branch__c IN:rtIds];
        List<Cashbook__c> cbListToUpdate = new List<Cashbook__c>();
        if(cbList.size() != 0){
            for(Cashbook__c cb: cbList){
                cbMap.put(cb.Branch__c,cb);
            }
        }
        else{
             for(Branch__c rt: scope){
                Cashbook__c cb1 = new Cashbook__c();
                cb1.Branch__c = rt.Id;
                cb1.Opening_Balance__c = 0;
                 cbListToUpdate.add(cb1);
            }
        }      
        
        
        if(cbMap.size() != 0){
            for(Branch__c rt: scope){
                if(cbMap.containsKey(rt.Id)){
                    Cashbook__c cb1 = new Cashbook__c();
                    cb1.Branch__c = rt.Id;
                    cb1.Opening_Balance__c = cbMap.get(rt.Id).Closing_Balance__c;
                    cbListToUpdate.add(cb1);
                }
                else{
                    Cashbook__c cb1 = new Cashbook__c();
                    cb1.Branch__c = rt.Id;
                    cb1.Opening_Balance__c = 0;
                    cbListToUpdate.add(cb1);
                }
              
            }
             
             
         }
     system.debug('cbListToUpdate:' + cbListToUpdate);
       insert cbListToUpdate;
    }
    
    public void finish(Database.BatchableContext BC){
   }
    
     global void execute(SchedulableContext SC){
        database.executeBatch(new UpdateBranchOpeningBalance(),100);
      
    } 

}