force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/Branch_Id__c.field-meta.xml
<CustomField>
    <fullName>Branch_Id__c</fullName>
    <label>Branch Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Branch__c/fields/Cash_In_Hand__c.field-meta.xml
<CustomField>
    <fullName>Cash_In_Hand__c</fullName>
    <label>Cash In Hand</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <displayFormat>EP-{00000}</displayFormat>
        <label>Expense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Expense_Account__c.field-meta.xml
<CustomField>
    <fullName>Expense_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expense Account</label>
    <referenceTo>Expense_Account__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Account__c/Expense_Account__c.object-meta.xml
<CustomObject>
    <label>Expense Account</label>
    <nameField>
        <label>Expense Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Account__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Expense Account</relationshipLabel>
    <relationshipName>Expense_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Route__c/fields/Branch_Name__c.field-meta.xml
<CustomField>
    <fullName>Branch_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch Name</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Routes</relationshipLabel>
    <relationshipName>Routes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route__c/fields/Route_Id__c.field-meta.xml
<CustomField>
    <fullName>Route_Id__c</fullName>
    <externalId>true</externalId>
    <label>Route Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit - {00000000}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Route_Id__c.field-meta.xml
<CustomField>
    <fullName>Route_Id__c</fullName>
    <formula>Owner:User.Route_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Route Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>PostPone</fullName>
                <isActive>false</isActive>
                <label>PostPone</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/customNewExpenseController.cls
public class customNewExpenseController {

     public class dataBox{
        @AuraEnabled
        public Date Todaydate {get; set;}
        @AuraEnabled
        public Date yersterdaydate {get; set;}         
        @AuraEnabled
        public Date twodaydate {get; set;} 
        @AuraEnabled
        public string listId {get; set;} 
        @AuraEnabled
        public integer inprogressCount {get; set;}  
        @AuraEnabled
        public integer plannedCount {get; set;}   
     }
     @AuraEnabled
     public static dataBox getDates(){
             dataBox db = new dataBox();
             db.Todaydate = system.today();
             date mydate = system.today();
             db.twodaydate = mydate.addDays(-2);
             db.yersterdaydate = mydate.addDays(-1);
              List<ListView> listviews = [SELECT Id, Name FROM ListView WHERE SobjectType = 'Expense__c' and Name='All'];
			db.listId = listviews[0].Id;
             List<visit__c> inprogressList= [SELECT id,Name,Status__c FROM visit__c WHERE Status__c = 'In Progress' AND Planned_Start_Time__c = TODAY AND ownerId =:userinfo.getUserId()];
             db.inprogressCount = inprogressList.size();
              List<visit__c> plannedList= [SELECT id,Name,Status__c FROM visit__c WHERE Status__c = 'Planned' AND Planned_Start_Time__c = TODAY AND ownerId =:userinfo.getUserId()];
             db.plannedCount = plannedList.size();
             return db;
     }    
     @AuraEnabled
     public static Expense__c insertExpense(Expense__c expense){ 
        if(expense !=null ){
            
            try {
                upsert expense;
                return expense;
            }
            catch (System.Exception ae) { 
                ExceptionHandler.addLog(ae,String.valueOf(expense)  ); 
                return null;
            }     
            
        }else{
            return null;
        }
        
    }
    @AuraEnabled
    public static void submitapproval(string expId){ 
        List<Approval.ProcessSubmitRequest> requests = new List<Approval.ProcessSubmitRequest>();
        Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
        req.setObjectId(expId);
        requests.add(req);
    	
        try {
            Approval.ProcessResult[] processResults = Approval.process(requests);
        }
        catch (System.Exception ae) { 
           ExceptionHandler.addLog(ae,String.valueOf(expId)  );   
        }     
        
    
    }
     @AuraEnabled
    public static list<Expense_Account__c> getExpenseAccount(){ 
          list<Expense_Account__c> expAccount;
                User currentUser = [SELECT Id, Company_Name__c,Route_Id__c,Branch_Id__c FROM User WHERE Id = :UserInfo.getUserId()];
       List<Route__c> route = [select Id,Route_Id__c,Branch_Name__c from Route__c where Route_Id__c =: currentUser.Route_Id__c Limit 1];
        List<Branch__c> branch = [select Id,Cash_In_Hand__c from Branch__c where Branch_Id__c = :currentUser.Branch_Id__c];
        
        if(route.size() > 0){
             expAccount =[select Id,Name from Expense_Account__c where Branch__c=:route[0].Branch_Name__c  order by Name asc ];
        }
        else if(branch.size()>0){
             expAccount =[select Id,Name from Expense_Account__c where Branch__c=:branch[0].Id  order by Name asc ];
        }
 
        return expAccount;
    } 
}