force-app/main/default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>Stock-{00000}</displayFormat>
        <label>Stock Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/fields/Available_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Available_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Available Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Blocked_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Blocked_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Blocked Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Free_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Free_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Free Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Intial_Stock__c.field-meta.xml
<CustomField>
    <fullName>Intial_Stock__c</fullName>
    <label>Intial Stock</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Sold_Qty__c.field-meta.xml
<CustomField>
    <fullName>Sold_Qty__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sold Qty</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/stockHandler.cls
public class stockHandler {
    
    public static void addBlockedQuantityToStock(map<Id,decimal> blockStockMap){
        
        map<Id,Stock__c> StockMap = new map<Id,Stock__c>([select Id,Blocked_Quantity__c,Intial_Stock__c,Sold_Qty__c,Free_Quantity__c,Replaced_Quantity__c,Available_Quantity__c from Stock__c where Id in :blockStockMap.keySet() limit 4999]);
        for(Stock__c s : StockMap.values()){
            s.Replaced_Quantity__c =  s.Replaced_Quantity__c ==null?0:s.Replaced_Quantity__c;
            s.Blocked_Quantity__c += blockStockMap.get(s.Id);
            s.Available_Quantity__c=s.Intial_Stock__c-s.Sold_Qty__c-s.Blocked_Quantity__c-s.Free_Quantity__c-s.Replaced_Quantity__c ;
        }
        try {
            update StockMap.values();
        }
        catch(Exception ex){
            ExceptionHandler.addLog(ex,String.valueOf(StockMap.values())); 
            system.debug(ex.getMessage());
        }
    }
    public static void removeBlockedQuantityToStock(map<Id,decimal> blockStockMap,string type){
        map<Id,Stock__c> StockMap = new map<Id,Stock__c>([select Id,Blocked_Quantity__c,Intial_Stock__c,Sold_Qty__c,Free_Quantity__c,Replaced_Quantity__c,Available_Quantity__c from Stock__c where Id in :blockStockMap.keySet() limit 4999]);
        for(Stock__c s : StockMap.values()){
        
            s.Blocked_Quantity__c -= blockStockMap.get(s.Id); /*deduct blocked qty*/
            
            if(type == 'Replacement'){
                    s.Replaced_Quantity__c =  s.Replaced_Quantity__c ==null?0:s.Replaced_Quantity__c;
                s.Replaced_Quantity__c +=blockStockMap.get(s.Id);
            }
            if(type == 'Unsealed'){
                  s.Free_Quantity__c =  s.Free_Quantity__c ==null?0:s.Free_Quantity__c;
                s.Free_Quantity__c +=blockStockMap.get(s.Id);
            }
            
            s.Available_Quantity__c=s.Intial_Stock__c-s.Sold_Qty__c-s.Blocked_Quantity__c-s.Free_Quantity__c-s.Replaced_Quantity__c;  
            
        }
        try {
            update StockMap.values();
        }
        catch(Exception ex){
            ExceptionHandler.addLog(ex,String.valueOf(StockMap.values())); 
            system.debug(ex.getMessage());
        }
    }
}