force-app/main/default/objects/DailyLog__c/DailyLog__c.object-meta.xml
<CustomObject>
    <label>Daily Log</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Log Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/DailyLog__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Daily Logs</relationshipLabel>
    <relationshipName>Daily_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DailyLog__c/fields/Trip__c.field-meta.xml
<CustomField>
    <fullName>Trip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trip</label>
    <referenceTo>Trip__c</referenceTo>
    <relationshipLabel>Logs</relationshipLabel>
    <relationshipName>Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <displayFormat>EP-{00000}</displayFormat>
        <label>Expense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Select_Expense_Entry__c.field-meta.xml
<CustomField>
    <fullName>Select_Expense_Entry__c</fullName>
    <label>Expense Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>General Entry</fullName>
            </value>
            <value>
                <fullName>Purchase Entry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Trip__c.field-meta.xml
<CustomField>
    <fullName>Trip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trip</label>
    <referenceTo>Trip__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Route__c/fields/Route_Id__c.field-meta.xml
<CustomField>
    <fullName>Route_Id__c</fullName>
    <externalId>true</externalId>
    <label>Route Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Trip__c/Trip__c.object-meta.xml
<CustomObject>
    <label>Trip</label>
    <nameField>
        <displayFormat>TRIP-{0000}</displayFormat>
        <label>Trip Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipName>Trips</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Ended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ExpenseTriggerTest.cls
@IsTest
private class ExpenseTriggerTest {
    static testMethod void testExpenseTrigger() {
        // Create a test user
        User testUser = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'system administrator'].Id,
            LastName = 'last',
            Email = 'puser000@amamama.com',
            Username = 'puser000@amamama.com' + System.currentTimeMillis(),
            CompanyName = 'TEST',
            Title = 'title',
            Alias = 'alias',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',         
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            Route_Id__c = 'TEST');
        insert testUser;
        
        // Create a test route
        Route__c r = new Route__c();
        r.Route_Id__c = 'TEST';
        r.Cash_In_Hand__c = 100;
        r.OwnerId = testUser.Id;
        insert r;
        system.debug('Route is - '+r);
        
        system.runAs(testUser){
            
            // Create a test trip
            Trip__c tr = new Trip__c();
            tr.Route__c = r.id;
            tr.Cash_In_Hand__c = 100;
            tr.Last_Cleared_Date__c = System.today();
            tr.Status__c = 'Started';
            insert tr;
            system.debug('Trip is - '+tr);
            
            // Create a test daily log
            DailyLog__c dl = new DailyLog__c();
            dl.Clock_In__c = System.Today();
            dl.Clock_In__c = System.today() + 1;
            dl.Trip__c = tr.Id;
            insert dl;
            system.debug('Daily log - '+dl);
            
            // Create a test expense
            Expense__c exp = new Expense__c();
            exp.Select_Expense_Entry__c = '	General Entry';
            exp.Expense_Comments__c = 'Some Comment';
            try{
                insert exp;
            }
            catch(DMLException e)
            {
                system.debug('Error is - '+e.getMessage());
            }
            Expense__c exp1 = new Expense__c();
            exp1.Select_Expense_Entry__c = '	General Entry';
            exp1.Expense_Comments__c = 'Some Comment';
            // exp1.OwnerId = UserInfo.getUserId();
            try{
                insert exp1;
            }
            catch(DMLException e)
            {
                system.debug('Error is - '+e.getMessage());
            }
            
            
            
            // Test before insert trigger
            Test.startTest();
            
            exp.Approval_Status__c = 'Approved';
            update exp;
            
            exp1.Approval_Status__c = 'Rejected';
            update exp1;
            Test.stopTest();
        }
    }
    
    
}