force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Company_Id__c.field-meta.xml
<CustomField>
    <fullName>Company_Id__c</fullName>
    <label>Company_Id</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Company</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/CompanyId__c.field-meta.xml
<CustomField>
    <fullName>CompanyId__c</fullName>
    <label>Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Company</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Route__c/fields/CompanyId__c.field-meta.xml
<CustomField>
    <fullName>CompanyId__c</fullName>
    <label>Company Id</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Company</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>Stock-{00000}</displayFormat>
        <label>Stock Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/fields/Available_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Available_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Available Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Stock_Type__c.field-meta.xml
<CustomField>
    <fullName>Stock_Type__c</fullName>
    <label>Stock Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Return</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
            </value>
            <value>
                <fullName>Manufacturing Defect</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stock_History__c/Stock_History__c.object-meta.xml
<CustomObject>
    <label>Stock History</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Stock History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock History</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_History__c/fields/Available_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Available_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Closing Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock_History__c/fields/Ext_ID__c.field-meta.xml
<CustomField>
    <fullName>Ext_ID__c</fullName>
    <label>Ext. ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock_History__c/fields/Opening_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Opening_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Opening Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock_History__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Stock History</relationshipLabel>
    <relationshipName>Stock_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_History__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Stock History</relationshipLabel>
    <relationshipName>Stock_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/StockBatch.cls
global class StockBatch implements Database.Batchable<sObject>,Database.Stateful,Schedulable{
    
    public Database.QueryLocator start(Database.BatchableContext BC){
        String query='select Id,Name,Product_Code__c,Company_Id__c from Product__c';
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<Product__c> scope){
        Set<String> pIds = new Set<String>();
        
        List<Route__c> rtList = new List<Route__c>();
        //Dev Users to Dev Products, Eva Users to EVA Products
       // if(Test.isRunningTest()){
            rtList = [select Id,Name,CompanyId__c,OwnerId from Route__c where Id='a0LN0000008h2ADMAY'];
        //}
        //else{
        //    rtList = [select Id,Name,CompanyId__c,OwnerId from Route__c];
       // }
         
        
        for(Product__c pro : scope){
            for(Route__c rt:rtList){
                if(pro.Company_Id__c == rt.CompanyId__c){
                    string ext = String.valueOf(pro.Id) + String.valueOf(rt.Id) + system.today();
                    pIds.add(ext);
                }
                
            }
        }
       
        List<AggregateResult> aggList = [select Product__c prod,Route__c rt, SUM(Available_Quantity__c) availQty from Stock__c where Stock_Type__c = 'New' and Product__c IN:scope group by Product__c,Route__c];
        
        Map<String,Decimal> availMap = new Map<String,Decimal>();
        
        for(AggregateResult agg:aggList){
            
            string ext = String.valueOf(agg.get('prod')) + String.valueOf(agg.get('rt'));
            availMap.put(ext,(Decimal)agg.get('availQty'));
           
        }
      
        Map<String,Stock_History__c> histMap = new Map<String,Stock_History__c>();
        
        List<Stock_History__c> hisList = [select Id,Name,Route__c,Product__c,Available_Quantity__c,CreatedDate,Ext_ID__c from Stock_History__c where CreatedDate = yesterday and Ext_ID__c IN:pIds];
        List<Stock_History__c> hisListToUpdate = new List<Stock_History__c>();
        
        if(hisList.size() != 0){
            for(Stock_History__c sh: hisList){
                histMap.put(sh.Ext_ID__c,sh);
            }
        }
        else{
            for(Product__c pro : scope){
                for(Route__c rt:rtList){
                    if(pro.Company_Id__c == rt.CompanyId__c){
                        Stock_History__c his = new Stock_History__c();
                        his.Route__c = rt.Id;
                        his.Product__c = pro.Id;
                        if(availMap.containsKey(String.valueOf(his.Product__c) + String.valueOf(his.Route__c)))
                        {
                            his.Opening_Quantity__c = availMap.get(String.valueOf(his.Product__c) + String.valueOf(his.Route__c));
                        }
                        else{
                            his.Opening_Quantity__c = 0;
                        }
                        his.Available_Quantity__c = his.Opening_Quantity__c;
                        his.Ext_ID__c = String.valueOf(his.Product__c) + String.valueOf(his.Route__c)  + system.today();
                        his.Date__c = system.today();
                        his.OwnerId = rt.OwnerId;
                        hisListToUpdate.add(his);
                        
                    }
                }
            }      
            
        }
        if(histMap.size() != 0){
            for(Product__c pro : scope){
                for(Route__c rt:rtList){
                    if(pro.Company_Id__c == rt.CompanyId__c){
                        string ext = String.valueOf(pro.Id) + String.valueOf(rt.Id)  + system.today();
                        if(histMap.containsKey(ext)){
                            Stock_History__c his = new Stock_History__c();
                            his.Route__c = rt.Id;
                            his.Product__c = pro.Id;
                            his.Opening_Quantity__c = histMap.get(ext).Available_Quantity__c;
                            his.Available_Quantity__c = his.Opening_Quantity__c;
                            his.Ext_ID__c = String.valueOf(his.Product__c) + String.valueOf(his.Route__c) + system.today();
                            his.Date__c = system.today();
                            his.OwnerId = rt.OwnerId;
                            hisListToUpdate.add(his);
                        }
                        else{
                            Stock_History__c his = new Stock_History__c();
                            his.Route__c = rt.Id;
                            his.Product__c = pro.Id;
                            if(availMap.containsKey(String.valueOf(his.Product__c) + String.valueOf(his.Route__c)))
                            {
                                his.Opening_Quantity__c = availMap.get(String.valueOf(his.Product__c) + String.valueOf(his.Route__c));
                            }
                            else{
                                his.Opening_Quantity__c = 0;
                            }
                            his.Available_Quantity__c = his.Opening_Quantity__c;
                            his.Ext_ID__c = String.valueOf(his.Product__c) + String.valueOf(his.Route__c) + system.today();
                            his.Date__c = system.today();
                            his.OwnerId = rt.OwnerId;
                            hisListToUpdate.add(his);
                        }
                    }
                }
            }
            
            
        }
        system.debug('hisListToUpdate:' + hisListToUpdate);
        //insert hisListToUpdate;
        database.insert(hisListToUpdate,false);
        
        /*  Integer batchSize = 2000;
        Integer nrOfRecordsProcessed = 0;
        
        Integer rowsReturned = batchSize;
        Map<String,Decimal> availMap = new Map<String,Decimal>();
        while (rowsReturned == batchSize) {
            rowsReturned = 0;
            for(AggregateResult agg : [select Product__c prod,Route__c rt, SUM(Available_Quantity__c) availQty from Stock__c where Stock_Type__c = 'New'  group by Product__c,Route__c LIMIT :batchSize OFFSET :nrOfRecordsProcessed]) {
                string ext = String.valueOf(agg.get('prod')) + String.valueOf(agg.get('rt'));
                availMap.put(ext,(Decimal)agg.get('availQty'));
                rowsReturned++;
            }
            nrOfRecordsProcessed = nrOfRecordsProcessed + rowsReturned;
        }*/
         
       /* Integer recordCount = [select count() from Stock__c  where Stock_Type__c = 'New'];
        Integer sizeBlock = recordCount/2000 + (math.mod(recordCount,2000)!=0?1:0) ;
        Set<Id> setAppIds = new Set<Id>(); 
        Map<String,Decimal> availMap = new Map<String,Decimal>();
        //Iterate aggregate result with blocks of 2000 to avoid exception
        for(Integer i=0;i<sizeBlock;i++){            
            for(AggregateResult agg : [select Product__c prod,Route__c rt, SUM(Available_Quantity__c) availQty from Stock__c
                                      where Stock_Type__c = 'New' and id not in :setAppIds 
                                      group by Product__c,Route__c limit 2000]) {
                                          
            	string ext = String.valueOf(agg.get('prod')) + String.valueOf(agg.get('rt'));
            	availMap.put(ext,(Decimal)agg.get('availQty'));
            	setAppIds.add(Id.valueOf(String.valueOf(agg.get('id'))));
            }
        }*/
        
        

    }
    
    public void finish(Database.BatchableContext BC){
    }
    
    global void execute(SchedulableContext SC){
        database.executeBatch(new StockBatch(),1);
        
    } 
    
    
}