force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_History__c/Stock_History__c.object-meta.xml
<CustomObject>
    <label>Stock History</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Stock History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock History</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_History__c/fields/Available_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Available_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Closing Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock_History__c/fields/Free_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Free_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Free Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock_History__c/fields/Initial_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Initial_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Received Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock_History__c/fields/Opening_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Opening_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Opening Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock_History__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Stock History</relationshipLabel>
    <relationshipName>Stock_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_History__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Stock History</relationshipLabel>
    <relationshipName>Stock_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_History__c/fields/Sold_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Sold_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sold Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock_History__c/fields/Unsealed_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Unsealed_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Unsealed Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/vanStockControllerTest.cls
@IsTest
public class vanStockControllerTest {

    @IsTest
    static void testVanStockController_WithParams() {

       
        // 1. Create required master data
     

        // Route
        Route__c route = new Route__c(
            Name = 'Test Route'
        );
        insert route;

        // Custom Product (NOT Product2)
        Product__c product = new Product__c(
            Name = 'Test Product'
        );
        insert product;

        
        // 2. Create Stock History record
        
        Stock_History__c stock = new Stock_History__c(
            Route__c = route.Id,
            Product__c = product.Id,
            Opening_Quantity__c = 10,
            Initial_Quantity__c = 20,
            Sold_Quantity__c = 5,
            Available_Quantity__c = 25,
            Damaged_Quantity__c = 1,
            Free_Quantity__c = 2,
            Unsealed_Quantity__c = 1,
            Date__c = Date.today()
        );
        insert stock;

        
        // 3. Set VF page & parameters
        // (avoid static resource issue)
    
        Test.setCurrentPage(new PageReference('/apex/dummy'));
        ApexPages.currentPage().getParameters().put('Id', route.Id);
        ApexPages.currentPage().getParameters().put('from', String.valueOf(Date.today().addDays(-1)));
        ApexPages.currentPage().getParameters().put('to', String.valueOf(Date.today().addDays(1)));

       
        // 4. Execute controller
        
        Test.startTest();
        vanStockController controller = new vanStockController();
        Test.stopTest();

      
        // 5. Assertions
      
        System.assertNotEquals(
            null,
            controller.stockList,
            'Stock list should not be null'
        );

        System.assertEquals(
            1,
            controller.stockList.size(),
            'One Stock History record expected'
        );

        System.assertEquals(
            'Test Product',
            controller.stockList[0].Product__r.Name,
            'Product name should match'
        );
    }

    @IsTest
    static void testVanStockController_WithoutParams() {

        // No parameters passed
        Test.setCurrentPage(new PageReference('/apex/dummy'));

        Test.startTest();
        vanStockController controller = new vanStockController();
        Test.stopTest();

        // stockList should remain null
        System.assertEquals(null, controller.stockList);
    }
}