force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/GST__c.field-meta.xml
<CustomField>
    <fullName>GST__c</fullName>
    <label>GST</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GST_percentages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>Stock-{00000}</displayFormat>
        <label>Stock Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/fields/Available_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Available_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Available Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Blocked_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Blocked_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Blocked Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Intial_Stock__c.field-meta.xml
<CustomField>
    <fullName>Intial_Stock__c</fullName>
    <label>Intial Stock</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Sold_Qty__c.field-meta.xml
<CustomField>
    <fullName>Sold_Qty__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sold Qty</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ClearStockControllerTest.cls
@isTest
public class ClearStockControllerTest {

     public static testmethod void testVFPage(){
         
         List<Route__c> rut = new List<Route__c>();
         Route__c r = new Route__c();
         r.Name = 'test route';
         rut.add(r);
         insert rut;
         
         Product__c productRec = new Product__c();
         productRec.Name = 'Dev Snacks Rosted peanut';
         productRec.Product_Code__c = 'P100';
         productRec.MRP__c = 25;
         productRec.GST__c = '5';
         insert productRec;
         
         Stock__c stock = new Stock__c();
         stock.Intial_Stock__c = 100;
         stock.Available_Quantity__c = 70;
         stock.Sold_Qty__c = 15;
         stock.Blocked_Quantity__c = 15;
         stock.Product__c = productRec.id;
         stock.Route__c = r.Id;
         Insert stock;
         
         Test.startTest();
         
         Test.setCurrentPage(Page.ClearStock);
         
         ApexPages.StandardSetController sc = new ApexPages.StandardSetController(rut);
         sc.setSelected(rut);
         ClearStockController testAccPlan = new ClearStockController(sc);
         testAccPlan.clearStock();
         
         Test.stopTest(); 
         
     }
    
    public static testmethod void testVFPage2(){
         
         List<Route__c> rut = new List<Route__c>();
         Route__c r = new Route__c();
         r.Name = 'test route';
         rut.add(r);
         insert rut;
         
         Product__c productRec = new Product__c();
         productRec.Name = 'Dev Snacks Rosted peanut';
         productRec.Product_Code__c = 'P100';
         productRec.MRP__c = 25;
         productRec.GST__c = '5';
         insert productRec;
         
         Stock__c stock = new Stock__c();
         stock.Intial_Stock__c = 100;
         stock.Available_Quantity__c = 70;
         stock.Sold_Qty__c = 15;
         stock.Blocked_Quantity__c = 15;
         stock.Product__c = productRec.id;
         stock.Route__c = r.Id;
         Insert stock;
         
         Test.startTest();
         
         Test.setCurrentPage(Page.ClearStock);
         
         ApexPages.StandardSetController sc = new ApexPages.StandardSetController(new List<Route__c>());
         sc.setSelected(new List<Route__c>());
         ClearStockController testAccPlan = new ClearStockController(sc);
         testAccPlan.clearStock();
         
         Test.stopTest(); 
         
     }
}