force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>Stock-{00000}</displayFormat>
        <label>Stock Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/fields/Available_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Available_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Available Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Damaged_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Damaged_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Damaged Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Free_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Free_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Free Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_History__c/Stock_History__c.object-meta.xml
<CustomObject>
    <label>Stock History</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Stock History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock History</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_History__c/fields/Available_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Available_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Closing Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock_History__c/fields/Ext_ID__c.field-meta.xml
<CustomField>
    <fullName>Ext_ID__c</fullName>
    <label>Ext. ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock_History__c/fields/Free_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Free_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Free Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock_History__c/fields/Initial_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Initial_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Received Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock_History__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Stock History</relationshipLabel>
    <relationshipName>Stock_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_History__c/fields/Replaced_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Replaced_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Replaced Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock_History__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Stock History</relationshipLabel>
    <relationshipName>Stock_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_History__c/fields/Sold_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Sold_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sold Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock_History__c/fields/Unsealed_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Unsealed_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Unsealed Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unsealed__c/Unsealed__c.object-meta.xml
<CustomObject>
    <label>Unsealed</label>
    <nameField>
        <displayFormat>U-{0000}</displayFormat>
        <label>Unsealed Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unsealeds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unsealed__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipName>Goods_Issues</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unsealed_Item__c/Unsealed_Item__c.object-meta.xml
<CustomObject>
    <label>Unsealed Item</label>
    <nameField>
        <displayFormat>UI-{0000}</displayFormat>
        <label>Unsealed Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unsealed Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unsealed_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipName>Goods_Issue_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unsealed_Item__c/fields/Stock__c.field-meta.xml
<CustomField>
    <fullName>Stock__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stock</label>
    <referenceTo>Stock__c</referenceTo>
    <relationshipName>Goods_Issue_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unsealed_Item__c/fields/Unsealed__c.field-meta.xml
<CustomField>
    <fullName>Unsealed__c</fullName>
    <label>Unsealed</label>
    <referenceTo>Unsealed__c</referenceTo>
    <relationshipLabel>Unsealed Items</relationshipLabel>
    <relationshipName>Unsealed_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/UnsealedItemTrigger_Handler.cls
public with sharing class UnsealedItemTrigger_Handler {

    public static void updateStockHistory(list<Unsealed_Item__c> unsealedItems){
          map<string,decimal> stockQtyMap = new map<string,decimal>();
        for(Unsealed_Item__c u : unsealedItems){
             decimal quantity =0;
            if(u.Stock__c != null && u.Quantity__c !=null){
                if(stockQtyMap.containsKey(u.Stock__c)){
                    quantity = stockQtyMap.get(u.Stock__c);
                }
                quantity += u.Quantity__c;
                  stockQtyMap.put(u.Stock__c,quantity);
            } 
        }   
       if(!stockQtyMap.isEmpty()){
            List<Stock__c> stocksList = [select Id,Route__c,Available_Quantity__c,Free_Quantity__c from Stock__c where Id in :stockQtyMap.keySet() ];
            
            for(Stock__c s : stocksList ){
                s.Available_Quantity__c =  s.Available_Quantity__c != null ?  (s.Available_Quantity__c - stockQtyMap.get(s.Id) ) : - stockQtyMap.get(s.Id);
                s.Free_Quantity__c =  s.Free_Quantity__c != null ?  (s.Free_Quantity__c + stockQtyMap.get(s.Id) ) : stockQtyMap.get(s.Id);
            }
            try{
                update stocksList;
            }
            catch (System.Exception ae) { 
                ExceptionHandler.addLog(ae,String.valueOf(stocksList)  ); 
            } 
        }       
        
        
        
        
        
        
        
         
         List<AggregateResult> avaggList = [select Product__c prod,Unsealed__r.Route__c rt, SUM(Quantity__c) freeQty from Unsealed_Item__c where createddate=today  group by Product__c,Unsealed__r.Route__c];
        Map<String,Decimal> availMap = new Map<String,Decimal>();
            Set<String> extids = new Set<String>();
        for(AggregateResult agg:avaggList){
            
            string ext = String.valueOf(agg.get('prod')) + String.valueOf(agg.get('rt')) + system.today();
            extids.add(ext);
            availMap.put(ext,(Decimal)agg.get('freeQty'));
        }
        
         List<Stock_History__c> hisList = [select Id,Name,Route__c,Product__c,Available_Quantity__c,Initial_Quantity__c,
                                          Damaged_Quantity__c,Free_Quantity__c,Sold_Quantity__c,
                                          Replaced_Quantity__c,Unsealed_Quantity__c,CreatedDate,Ext_ID__c from Stock_History__c where  Ext_ID__c IN:extIds];
    	 List<Stock_History__c> hisListToUpdate = new List<Stock_History__c>();
        if(hisList.size() > 0){
            for(Stock_History__c his : hisList){
                his.Unsealed_Quantity__c = availMap.containsKey(his.Ext_ID__c) ? availMap.get(his.Ext_ID__c) : his.Unsealed_Quantity__c;
               
                hisListToUpdate.add(his);
            }
        }
        
        try {
            upsert hisListToUpdate;
        }
        catch (System.Exception ae) { 
            ExceptionHandler.addLog(ae,String.valueOf(hisListToUpdate) );
        }  
    }
}