force-app/main/default/objects/Return__c/Return__c.object-meta.xml
<CustomObject>
    <label>Return</label>
    <nameField>
        <label>Return Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Returns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Return__c/fields/Branch_Id__c.field-meta.xml
<CustomField>
    <fullName>Branch_Id__c</fullName>
    <formula>Branch__r.Branch_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Branch Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Return__c/fields/Driver_Code__c.field-meta.xml
<CustomField>
    <fullName>Driver_Code__c</fullName>
    <formula>Daily_log__r.Employee__r.Employee_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Driver Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Return__c/fields/IRN_Number__c.field-meta.xml
<CustomField>
    <fullName>IRN_Number__c</fullName>
    <label>IRN Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Return__c/fields/Sales_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Invoice</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Sales_Invoice__c.Sales_Invoice_Status__c</field>
            <operation>notEqual</operation>
            <value>Cancelled</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Sales_Invoice__c</referenceTo>
    <relationshipLabel>Returns</relationshipLabel>
    <relationshipName>Returns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Return__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <formula>TEXT( Customer__r.State__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>State</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Return_Item__c/Return_Item__c.object-meta.xml
<CustomObject>
    <label>Return Item</label>
    <nameField>
        <label>Return Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Return Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Return_Item__c/fields/Batch_No__c.field-meta.xml
<CustomField>
    <fullName>Batch_No__c</fullName>
    <label>Batch Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Return_Item__c/fields/Return__c.field-meta.xml
<CustomField>
    <fullName>Return__c</fullName>
    <label>Return</label>
    <referenceTo>Return__c</referenceTo>
    <relationshipLabel>Return Items</relationshipLabel>
    <relationshipName>Invoice_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Return_Item__c/fields/Sales_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Invoice</label>
    <referenceTo>Sales_Invoice__c</referenceTo>
    <relationshipLabel>Return Items</relationshipLabel>
    <relationshipName>Return_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Return_Item__c/fields/Warehouse_Code__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Code__c</fullName>
    <formula>Return__r.Route__r.Route_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Warehouse Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice__c/Sales_Invoice__c.object-meta.xml
<CustomObject>
    <label>Sales Invoice</label>
    <nameField>
        <label>Sales Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Invoice__c/fields/CompanyId__c.field-meta.xml
<CustomField>
    <fullName>CompanyId__c</fullName>
    <formula>TEXT( Customer__r.CompanyId__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice__c/fields/Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>Customer_Id__c</fullName>
    <formula>Customer__r.CustomerId__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice__c/fields/Doc_Date__c.field-meta.xml
<CustomField>
    <fullName>Doc_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Doc Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice__c/fields/Driver_Code__c.field-meta.xml
<CustomField>
    <fullName>Driver_Code__c</fullName>
    <formula>Daily_log__r.Driver__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Driver Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice__c/fields/GST_applicable_formula__c.field-meta.xml
<CustomField>
    <fullName>GST_applicable_formula__c</fullName>
    <formula>Customer__r.GST_applicable__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GST applicable_formula</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <displayFormat>{0000}</displayFormat>
    <label>Invoice Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice__c/fields/Send_to_GSTZen__c.field-meta.xml
<CustomField>
    <fullName>Send_to_GSTZen__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send to GSTZen</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <formula>TEXT(Customer__r.State__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>State</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice__c/fields/Tax_Date__c.field-meta.xml
<CustomField>
    <fullName>Tax_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Tax Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice_Item__c/Sales_Invoice_Item__c.object-meta.xml
<CustomObject>
    <label>Sales Invoice Item</label>
    <nameField>
        <displayFormat>ITEM-{0000}</displayFormat>
        <label>Sales Invoice Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Invoice Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Invoice_Item__c/fields/Batch_No__c.field-meta.xml
<CustomField>
    <fullName>Batch_No__c</fullName>
    <formula>Stock__r.Batch_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Batch No.</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice_Item__c/fields/Customer_Discount__c.field-meta.xml
<CustomField>
    <fullName>Customer_Discount__c</fullName>
    <label>Customer Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice_Item__c/fields/Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>Customer_Id__c</fullName>
    <formula>Sales_Invoice__r.Customer__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice_Item__c/fields/GST_applicable_formula__c.field-meta.xml
<CustomField>
    <fullName>GST_applicable_formula__c</fullName>
    <formula>Sales_Invoice__r.Customer__r.GST_applicable__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GST applicable_formula</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice_Item__c/fields/Inv_Line_Items_Id__c.field-meta.xml
<CustomField>
    <fullName>Inv_Line_Items_Id__c</fullName>
    <displayFormat>ITEM-{0000}</displayFormat>
    <label>Invoice Line Items Id</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice_Item__c/fields/Item_Code__c.field-meta.xml
<CustomField>
    <fullName>Item_Code__c</fullName>
    <formula>Stock__r.Product__r.Product_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Item Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice_Item__c/fields/Item_Name__c.field-meta.xml
<CustomField>
    <fullName>Item_Name__c</fullName>
    <formula>Stock__r.Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Item Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice_Item__c/fields/Sales_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice__c</fullName>
    <label>Sales Invoice</label>
    <referenceTo>Sales_Invoice__c</referenceTo>
    <relationshipLabel>Invoice Items</relationshipLabel>
    <relationshipName>Invoice_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice_Item__c/fields/Warehouse_Code__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Code__c</fullName>
    <formula>Sales_Invoice__r.Route_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Warehouse Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Einvoice_Send_TriggerHandler.cls
public class Einvoice_Send_TriggerHandler {
    @Future(callout=true)
    public static void sendToPortal(list<Id> recIds,string type){
        for(Id recId: recIds){
            try{
                SalesEinvoice.sendData(recId,type);   
            }
          catch(Exception   ex){
                system.debug('Error'+ ex.getMessage());
                ExceptionHandler.addLog(ex,String.valueOf(recId));
            }
        }
    }
        @Future(callout=true)
    public static void sendToPortalCredit(list<Id> recIds,string type){
        for(Id recId: recIds){
            try{
                SalesEinvoiceCreditDebit.sendData(recId,type);   
            }
            catch(Exception   ex){
                system.debug('Error'+ ex.getMessage());
                ExceptionHandler.addLog(ex,String.valueOf(recId));
            }
        }
    }
    @AuraEnabled
    public static integer SendToPortal_call(Id recordId,string type){
        integer count =0,approvedcount=0,gstApplicable=0;
        string query,query1,Approved='Approved';
        list<Id> IdList =new list<Id>();
        if(recordId != null){
            IdList.add(recordId);  
            String objName = recordId.getSObjectType().getDescribe().getName();  
            if(objName == 'Sales_Invoice__c' && type == 'Generate'){
                query = 'select count() from Sales_Invoice__c where Id=:recordId and GST_applicable_formula__c=true and Send_to_GSTZen__c=false ';        
            }
                if(objName == 'Sales_Invoice__c' && type == 'Cancel'){
                query = 'select count() from Sales_Invoice__c where Id=:recordId and GST_applicable_formula__c=true and Send_to_GSTZen__c=true ';        
            }
            system.debug(query1);
            if(query != '' && query != null){
                    gstApplicable =  database.countQuery(query);
                system.debug(query);
                system.debug('gst'+gstApplicable);
                if(gstApplicable == 0){
                    count = 3;
                }
            }
            if(gstApplicable == 1){
                sendToPortal(IdList,type);
                // count= checkDataUpdated(objName,recordId);
                count = 1;
            }
        }
        return count; 
    } 
    
     
        /*@Autor -Nanma send IRN to Sap*/
    @invocableMethod
    public static void callSendToSAP(list<Id> SalesInvIds){
      list<Sales_Invoice__c> salesInvoice =[SELECT Id, Name, CompanyId__c, Route_Id__c, Driver_Code__c, Branch_Id__c, Doc_Date__c, Tax_Date__c, Invoice_Number__c, Customer_Id__c,State__c,IRN_Number__c,(SELECT Id, Name, Inv_Line_Items_Id__c, Item_Code__c, Item_Name__c, Quantity__c, Unit_Price__c, Warehouse_Code__c, Batch_No__c,Customer_Discount__c FROM Invoice_Items__r) FROM Sales_Invoice__c where Id in :SalesInvIds and Sent_to_SAP__c=false];
       // if(salesInvoice.size() > 0)    sendData(salesInvoice);
         if(salesInvoice.size() > 0)  
           SAPSendData.sendData(salesInvoice);
    
    }
    
        @AuraEnabled
    public static integer SendToPortal_creditCall(Id recordId,string type){
        integer count =0,gstApplicable=0;
        string query,query1,Approved='Approved';
        list<Id> IdList =new list<Id>();
        if(recordId != null){
            IdList.add(recordId);  
            String objName = recordId.getSObjectType().getDescribe().getName();  

             if(objName == 'Return__c' && type == 'Generate'){
                 query= 'select count() from Return__c where Id=:recordId and Approval_Status__c=:Approved and Sales_Invoice__r.GST_applicable_formula__c=true  ';          
            }
                if(objName == 'Return__c' && type == 'Cancel'){
                query = 'select count() from Return__c where Id=:recordId and Send_to_GSTZen__c=true ';        
            }
            if(query != '' && query != null){
                    gstApplicable = database.countQuery(query);
                system.debug(query);
             
                if(gstApplicable == 0 && type == 'Generate'){
                    count = 2;
                }
                  if(gstApplicable == 0 && type == 'Cancel'){
                    count = 3;
                }
            }
            if(gstApplicable == 1){
                sendToPortalCredit(IdList,type);
                count = 1;
            }
        }
        return count; 
    } 
          
}