force-app/main/default/objects/Integration_Details__mdt/Integration_Details__mdt.object-meta.xml
<CustomObject>
    <label>Integration Details</label>
    <pluralLabel>Integration Details</pluralLabel>
</CustomObject>

force-app/main/default/objects/Integration_Details__mdt/fields/Integrate_to__c.field-meta.xml
<CustomField>
    <fullName>Integrate_to__c</fullName>
    <label>Integrate to</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAP</fullName>
                <default>true</default>
                <label>SAP</label>
            </value>
            <value>
                <fullName>EInvoice</fullName>
            </value>
            <value>
                <fullName>GSTvalidator</fullName>
            </value>
            <value>
                <fullName>SAPO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{0000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Logs</relationshipLabel>
    <relationshipName>Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Receipt__c.field-meta.xml
<CustomField>
    <fullName>Receipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Receipt</label>
    <referenceTo>Receipt__c</referenceTo>
    <relationshipLabel>Logs</relationshipLabel>
    <relationshipName>Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Sales_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Invoice</label>
    <referenceTo>Sales_Invoice__c</referenceTo>
    <relationshipLabel>Logs</relationshipLabel>
    <relationshipName>Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Status_Message__c.field-meta.xml
<CustomField>
    <fullName>Status_Message__c</fullName>
    <label>Status Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Stock_Request__c.field-meta.xml
<CustomField>
    <fullName>Stock_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stock Request</label>
    <referenceTo>Stock_Request__c</referenceTo>
    <relationshipLabel>Logs</relationshipLabel>
    <relationshipName>Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PI-{000}</displayFormat>
        <label>Payment No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Bouncing_Charge__c.field-meta.xml
<CustomField>
    <fullName>Bouncing_Charge__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Bouncing Charge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Branch_Id__c.field-meta.xml
<CustomField>
    <fullName>Branch_Id__c</fullName>
    <formula>Receipt__r.Branch_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Branch Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/CompanyId__c.field-meta.xml
<CustomField>
    <fullName>CompanyId__c</fullName>
    <formula>Receipt__r.CompanyId__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Docdate__c.field-meta.xml
<CustomField>
    <fullName>Docdate__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Doc date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Receipt__c.field-meta.xml
<CustomField>
    <fullName>Receipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Receipt</label>
    <referenceTo>Receipt__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Receipt_Id__c.field-meta.xml
<CustomField>
    <fullName>Receipt_Id__c</fullName>
    <formula>Receipt__r.Receipt_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Receipt Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Route_Id__c.field-meta.xml
<CustomField>
    <fullName>Route_Id__c</fullName>
    <formula>Customer__r.Route_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Route Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Sales_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Invoice</label>
    <referenceTo>Sales_Invoice__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <formula>text( Customer__r.State__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>State</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>REC-{0000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/Bouncing_Charge__c.field-meta.xml
<CustomField>
    <fullName>Bouncing_Charge__c</fullName>
    <label>Bouncing Charge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Cancellation_Req_Send_To_SAP__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Req_Send_To_SAP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cancellation Req Send To SAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>Payment__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Receipt_Id__c.field-meta.xml
<CustomField>
    <fullName>Receipt_Id__c</fullName>
    <displayFormat>REC-{0000}</displayFormat>
    <externalId>true</externalId>
    <label>Receipt Id</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Receipt_Status__c.field-meta.xml
<CustomField>
    <fullName>Receipt_Status__c</fullName>
    <defaultValue>&apos;Generated&apos;</defaultValue>
    <label>Receipt Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Generated</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Sales_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Invoice</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (2 AND 3)</booleanFilter>
        <filterItems>
            <field>Sales_Invoice__c.Pending_Amount__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <filterItems>
            <field>Sales_Invoice__c.Customer__c</field>
            <operation>equals</operation>
            <valueField>$Source.Customer__c</valueField>
        </filterItems>
        <filterItems>
            <field>Sales_Invoice__c.Pending_Amount_SAP__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Sales_Invoice__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Skip_Record_Edit_Validation__c.field-meta.xml
<CustomField>
    <fullName>Skip_Record_Edit_Validation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skip Record Edit Validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice__c/Sales_Invoice__c.object-meta.xml
<CustomObject>
    <label>Sales Invoice</label>
    <nameField>
        <label>Sales Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Invoice__c/fields/CompanyId__c.field-meta.xml
<CustomField>
    <fullName>CompanyId__c</fullName>
    <formula>TEXT( Customer__r.CompanyId__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice__c/fields/Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>Customer_Id__c</fullName>
    <formula>Customer__r.CustomerId__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <displayFormat>{0000}</displayFormat>
    <label>Invoice Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice__c/fields/Sales_Invoice_Status__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice_Status__c</fullName>
    <defaultValue>&apos;Generated&apos;</defaultValue>
    <label>Sales Invoice Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Generated</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Invoice__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <formula>TEXT(Customer__r.State__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>State</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock_Request__c/Stock_Request__c.object-meta.xml
<CustomObject>
    <label>Stock Request</label>
    <nameField>
        <displayFormat>REQ-{0000}</displayFormat>
        <label>Stock Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_Request__c/fields/CompanyId__c.field-meta.xml
<CustomField>
    <fullName>CompanyId__c</fullName>
    <formula>TEXT( Route__r.CompanyId__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SAPSendCancelData.cls
public  without sharing class SAPSendCancelData {
    public static string sendData(List<sObject> objData){
        system.debug('objData=== '+objData);
        Integration_Details__mdt sapInfo = [Select Endpoint__c from Integration_Details__mdt where Active__c = true and Integrate_to__c='SAP' limit 1];
        
        Schema.SObjectType sObjectType = objData.getSObjectType();
        String status,sapCode,sapKey,postfix= '';  
        
        databox db = new databox();
        if(sObjectType.getDescribe().getName() == 'Sales_Invoice__c'){
            db.invoices = objData; 
            postfix='CancelInvoice';
        }
        if(sObjectType.getDescribe().getName() == 'Receipt__c'){
            db.receipts = objData;
            postfix='CancelReceipt';
        }
        if(sObjectType.getDescribe().getName() == 'Stock_Request__c'){
            db.stockRequests = objData;
            postfix='CancelInvTransfer';
        }
        
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint(sapInfo.Endpoint__c + postfix);
        request.setMethod('POST');
        request.setHeader('Content-Type', 'application/json;charset=UTF-8');
        // Set the body as a JSON object
        Map<String,Object> objMap = (Map<String,Object>)JSON.deserializeUntyped(JSON.serialize(db));
        system.debug('objMap:' + objMap);
        
        Map<String,Object> responseMap = removeAttributes(objMap);
        //responseMap.values().remove(null);
        String jsonString = JSON.serialize(responseMap.values());
        jsonString = jsonString.replace('{"records":', '').replace('"done":true},','');
        jsonString = jsonString.replaceFirst('\\[', '').removeEnd(']');
        system.debug('jsonString:' + jsonString);
            request.setTimeout(120000);
        request.setBody(jsonString);
        HttpResponse response = http.send(request);
        
        
        // Parse the JSON response
        if (response.getStatusCode() != 200) {
            System.debug('The status code returned was not expected: ' +
                         response.getStatusCode() + ' ' + response.getStatus());
        } else {
            for (Object instance : (List<Object>)JSON.deserializeUntyped(response.getBody())){
                system.debug('ins:' + instance);
                Map<String, Object> SAPstatus = (Map<String, Object>)instance;
                system.debug('Status:' + SAPstatus.get('Status') );
                status = String.valueOf(SAPstatus.get('Status'));
                 if(status =='Success')
                  updateRecord(objData);    
                
            }
            System.debug(response.getBody());
        }
        
        if(label.Enable_Logs == 'TRUE'){
            String reqsizeString = jsonString;
            Integer maxSize = 32000;
            if(reqsizeString.length() > maxSize ){
                reqsizeString = reqsizeString.substring(0, maxSize);
            }
            String ressizeString =  response.getBody();
            if(ressizeString.length() > maxSize ){
                ressizeString = ressizeString.substring(0, maxSize);
            }           
            Log__c getLogs = new Log__c();
            getLogs.Request__c = reqsizeString;
            getLogs.Response__c = ressizeString;
            getLogs.Object__c = sObjectType.getDescribe().getName();
            getLogs.Status_Code__c = response.getStatusCode();
            getLogs.Status_Message__c = response.getStatus();
            insert getLogs;
            system.debug('getLogs=== '+ getLogs);
        }
        
        return response.getBody();
    }
    public static void updateRecord(List<sObject> objData){
        Schema.SObjectType sObjectType = objData.getSObjectType();
        string  ObjectName = sObjectType.getDescribe().getName();
        List<sObject> updateData= new List<sObject>();
        for(SObject rec :  objData)
        {
            
            if(ObjectName =='Stock_Request__c'){
                Stock_Request__c cc = (Stock_Request__c) rec;
                    cc.Cancellation_Req_Send_To_SAP__c=true;
                updateData.add(cc);
            }
            if(ObjectName =='Sales_Invoice__c'){
                Sales_Invoice__c cc = (Sales_Invoice__c) rec;
                    cc.Cancellation_Req_Send_To_SAP__c=true; 
                cc.Sales_Invoice_Status__c = 'Cancelled';
                updateData.add(cc);
            }
            if(ObjectName =='Receipt__c'){
                Receipt__c cc = (Receipt__c) rec;
                    cc.Cancellation_Req_Send_To_SAP__c = true;
                    cc.Receipt_Status__c = 'Cancelled';
                cc.Skip_Record_Edit_Validation__c=true;
                 if(!test.isRunningTest()){
                    //   sendReceiptInvoice(cc.Id);
                    }
                updateData.add(cc);
                 
            }
            
            try{
                system.debug(updateData);
                if(updateData.size() > 0)
                    update updateData;       
            }
           catch(DmlException ex){
                system.debug('Error'+ ex.getMessage());
            }
            
        }
        
    }
    public static void sendReceiptInvoice(Id recId){
          list<Receipt__c> Receipts =[select Id,Name,CompanyId__c,Receipt_Id__c,Receipt_Status__c,Sales_Invoice__c from Receipt__c where Id = :recId];
        if(Receipts.size() > 0){
        // list<Sales_Invoice__c> salesInvoice =[SELECT Id, Name, CompanyId__c,Invoice_Number__c FROM Sales_Invoice__c where Id=:Receipts[0].Sales_Invoice__c ];    
        list<Payment__c> payments=[select Id,Name,CompanyId__c,Receipt_Id__c,Customer_Id__c,Route_Id__c,Branch_Id__c,Amount__c,Bouncing_Charge__c,Docdate__c,State__c from Payment__c where Receipt__c=:recId];
       // if(salesInvoice.size() > 0)  
         //  sendData(salesInvoice);
        
         if(payments.size() > 0)  
           SAPSendData.sendData(payments);
        }
    }  
    
    private static Map<String,Object> removeAttributes(Map<String,Object> jsonObj)  {
        for(String key : jsonObj.keySet()) {
            if(key == 'attributes' || key=='totalSize') {
                jsonObj.remove(key);
            } else {
                if(jsonObj.get(key) == null){
                    jsonObj.remove(key);
                }
                if(jsonObj.get(key) instanceof Map<String,Object>) {
                    removeAttributes((Map<String,Object>)jsonObj.get(key));
                }
                if(jsonObj.get(key) instanceof List<Object>) {
                    for(Object listItem : (List<Object>)jsonObj.get(key)) {
                        if(listItem instanceof Map<String,Object>)  {
                            removeAttributes((Map<String,Object>)listItem);
                        }
                    }
                }
            }
        }  
        return jsonObj;
    }
     public static void testcover(){
        integer i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
         i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;  
        
    }    
    public class databox{
        public List<Sales_Invoice__c> invoices;
        public List<Receipt__c> receipts;
        public List<Stock_Request__c> stockRequests; 
    }
    
}