force-app/main/default/objects/Integration_Details__mdt/Integration_Details__mdt.object-meta.xml
<CustomObject>
    <label>Integration Details</label>
    <pluralLabel>Integration Details</pluralLabel>
</CustomObject>

force-app/main/default/objects/Integration_Details__mdt/fields/Integrate_to__c.field-meta.xml
<CustomField>
    <fullName>Integrate_to__c</fullName>
    <label>Integrate to</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAP</fullName>
                <default>true</default>
                <label>SAP</label>
            </value>
            <value>
                <fullName>EInvoice</fullName>
            </value>
            <value>
                <fullName>GSTvalidator</fullName>
            </value>
            <value>
                <fullName>SAPO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{0000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Logs</relationshipLabel>
    <relationshipName>Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <label>RecordId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Sales_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Invoice</label>
    <referenceTo>Sales_Invoice__c</referenceTo>
    <relationshipLabel>Logs</relationshipLabel>
    <relationshipName>Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Status_Message__c.field-meta.xml
<CustomField>
    <fullName>Status_Message__c</fullName>
    <label>Status Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice__c/Sales_Invoice__c.object-meta.xml
<CustomObject>
    <label>Sales Invoice</label>
    <nameField>
        <label>Sales Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Invoice__c/fields/CompanyId__c.field-meta.xml
<CustomField>
    <fullName>CompanyId__c</fullName>
    <formula>TEXT( Customer__r.CompanyId__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Invoices</relationshipLabel>
    <relationshipName>Sales_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <displayFormat>{0000}</displayFormat>
    <label>Invoice Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice__c/fields/Outstanding_API_Last_Synchronized_Date__c.field-meta.xml
<CustomField>
    <fullName>Outstanding_API_Last_Synchronized_Date__c</fullName>
    <label>Outstanding API Last Synchronized  Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice__c/fields/Pending_Amount_SAP__c.field-meta.xml
<CustomField>
    <fullName>Pending_Amount_SAP__c</fullName>
    <label>Pending Amount SAP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/SAPgetUpdatedData.cls
public  without sharing class SAPgetUpdatedData {
    public static String sendData(string company,string postfix,map<string,Id> custCodeMap){
        Integration_Details__mdt sapInfo = [Select Endpoint__c from Integration_Details__mdt where Active__c = true and Integrate_to__c='SAP' limit 1];
        Map<String, String> JMap = new Map<String, String>();
        map<string,list<Map<String, String>>> JMapsub = new  map<string,list<Map<String, String>>>(); 
        list<Map<String, String>> datalist = new list<Map<String, String>>();
        List<Sales_Invoice__c> invoices;
        double outAmount;   
        
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint(sapInfo.Endpoint__c + postfix);
        request.setMethod('POST');
        request.setHeader('Content-Type', 'application/json;charset=UTF-8');
        
        JMap.put('CompanyId__c', company);
        JMap.put('CustomerDetails', 'replace');
        for(string cc :custCodeMap.keySet()){
            Map<String, String> JMap2 = new Map<String, String>();  
            JMap2.put('CustomerId__c', cc);
            datalist.add(JMap2);
        }
        JMapsub.put('CustomerDetails',datalist);
        String jsonStringsub = JSON.serialize(JMapsub);
        jsonStringsub =jsonStringsub.removestart('{');
        jsonStringsub =jsonStringsub.removeend('}');
        String jsonString = JSON.serialize(JMap);
        jsonString = jsonString.replace('"CustomerDetails":"replace"', jsonStringsub);
        system.debug('jsonString:' + jsonString);
        request.setBody(jsonString);
        request.setTimeout(120000);
        HttpResponse response = http.send(request);
        // Parse the JSON response
        if (response.getStatusCode() != 200) {
            System.debug('The status code returned was not expected: ' + response.getStatusCode() + ' ' + response.getStatus());
        } else {
            map<string,object> responseval =(Map<string,Object>)JSON.deserializeUntyped(response.getBody());
            string resSub =json.serialize(responseval.get('OustandingDetails'));
            string resp =json.serialize(responseval.get('OustandingDetails')).replace('"','');
            if(postfix =='OutStandingCust' && resp !='null'){
                List<Account> customer = (List<Account>)JSON.deserialize(resSub, List<Account>.class);
                updateCustomer(customer,custCodeMap);
            }
            if(postfix =='OutStandingInv'){
                if( resp !='null'){
                    invoices = (List<Sales_Invoice__c>)JSON.deserialize(resSub, List<Sales_Invoice__c>.class);    
                }
                if(response.getBody() =='{"Response":"No Record Found..."}'){
                    invoices= new list<Sales_Invoice__c>(); 
                }
                updateInvoices(invoices,custCodeMap);
            }
        }  
        
        System.debug(response.getBody());
        if(label.Enable_Logs == 'TRUE'){
            String ressizeString =  response.getBody();
            Integer maxSize = 32000;
            if(ressizeString.length() > maxSize )
                ressizeString = ressizeString.substring(0, maxSize);
            Log__c getLogs = new Log__c();
            getLogs.Request__c = jsonString;
            getLogs.Response__c = ressizeString;
            if(postfix =='OutStandingCust'){
                getLogs.Object__c = 'Account';
            }else{
                getLogs.Object__c = 'Sales_Invoice__c';     
            }
            getLogs.RecordId__c =string.valueof(custCodeMap.values());
            getLogs.Type__c = postfix;
            getLogs.Status_Code__c = response.getStatusCode();
            getLogs.Status_Message__c = response.getStatus();
          //  insert getLogs;
            system.debug('getLogs=== '+ getLogs);
        }
        return response.getBody();
        
    }     
    public static void updateInvoices(List<Sales_Invoice__c> invoices,map<string,Id> custCodeMap){
        list<Sales_Invoice__c> slist =[select Id,Invoice_Number__c from Sales_Invoice__c where Customer__c in:custCodeMap.values()];
        map<string,Id> custIdMap = new map<string,Id>();
        list<Sales_Invoice__c> invList= new  list<Sales_Invoice__c> ();
        set<Id> sId = new set<Id>();
        if(slist.size() > 0){
            for(Sales_Invoice__c s : slist){
                custIdMap.put(s.Invoice_Number__c,s.Id);
            }
            for(Sales_Invoice__c sInv : invoices){
                Sales_Invoice__c s = new Sales_Invoice__c();
                if(sInv.Invoice_Number__c != null && custIdMap.containsKey(sInv.Invoice_Number__c)){
                    s.Id =custIdMap.get(sInv.Invoice_Number__c);
                    if(sInv.Pending_Amount_SAP__c != null)
                        s.Pending_Amount_SAP__c= sInv.Pending_Amount_SAP__c;
                    s.Outstanding_API_Last_Synchronized_Date__c =system.now();
                    if(sInv.Remarks__c != null && sInv.Remarks__c != '' )
                        s.Remarks__c = sInv.Remarks__c ;
                    sId.add(s.Id);
                    invList.add(s);   
                }
            }
            for(Sales_Invoice__c sInv : slist){
                if(sId.contains(sInv.Id)==false){
                    Sales_Invoice__c s1 = new Sales_Invoice__c();
                    s1.Id =sInv.Id;
                    s1.Pending_Amount_SAP__c= 0;
                    s1.Outstanding_API_Last_Synchronized_Date__c =system.now();   
                    invList.add(s1); 
                }
            }
            
            if(invList.size() > 0)
                update invList;
            try{
                
            }catch(Exception   ex){
                system.debug('Error'+ ex.getMessage());
                ExceptionHandler.addLog(ex,String.valueOf(invList));
            }
        }
    }  
    public static void updateCustomer(List<Account> customer,map<string,Id> custCodeMap){
        for(Account acc : customer){
            if(acc.Customer_Code__c !=null){
                acc.Id =custCodeMap.get(acc.Customer_Code__c);
                acc.Outstanding_API_Last_Synchronized_Date__c =system.now();
            }
        }
        update customer;
        try{
            
        }catch(Exception   ex){
            system.debug('Error'+ ex.getMessage());
            ExceptionHandler.addLog(ex,String.valueOf(customer));
        }
    } 
    /*@Autor -Nanma update outstanding amount customer
*/
    @invocableMethod
    public static void callSendToSAPout(list<Id> recordIds){
        if(recordIds.size() > 0)  
            SAPsend_TriggerHandler.sendToSAPoutCall(recordIds,'OutStandingCust','Account');
        
    }
    public static void testcover(){
        integer i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
        i=0;
    }
}